### ISSUE TITLE
Google Drive Download Quota Exceeded from Loading Videos from Mounted Drive

### ISSUE THREAD

**Issue by andrewgraff** [googlecolab/colabtools#1020]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I am using a large number of video files stored in my google drive as a dataset for my google colab research work. Within my notebooks, I use opencv-python to load the videos through cv2.VideoCapture(). After loading the video files several times, google drive has imposed its download quota and cv2.VideoCapture() now fails to load the same videos the would load fine beforehand. If I navigate to the videos in google drive and try to download an individual video, I receive the message "Download quota exceeded for this file, so you can't download it at this time."

- Describe the expected behavior:
File accesses through google colab should not count toward the google drive download quota, as it limits my ability to access my dataset simply because the dataset is contained in video files. If it was stored in any other container, the repeated accesses would not have been flagged by google's download quota.

These files are not publicly shared and do not have a shareable link. So the only user accessing them is myself. I understand the purpose of the download quota for publicly shared videos, but these videos are private and only being used for academic research purposes. This is a pretty significant hinderance to anyone conducting video processing research using google colab.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1wZheDbNr3KNkcLx8Bf2TFksVQNbIGyZz

**Comment by blois** [comment]
What mechanism are you using to download the files from Drive? Is this Drive mounted to the filesystem?

**Comment by andrewgraff** [comment]
Yes, I am only mounting the drive in my colab notebook and accessing them through the filesystem.

**Comment by andrewgraff** [comment]
To see the Download Quota Error however, that is from navigating to the files in the google drive webpage, right-clicking, and selecting Download

**Comment by blois** [comment]
Drive does impose quotas based on the amount of data being downloaded, some discussion of it is at https://support.google.com/drive/thread/2035857?hl=en. It would be better to copy the file to local disk before loading multiple times or to experiment with smaller videos.

**Comment by Ryandry1st** [comment]
If the drive is mounted, does it still make sense to consider the data "downloaded"? Even in the discussion it only seems to be a problem due to the user sharing the link, not from colab reading the data and loading it onto the disk. For example, what if one wanted to use video with a NN, they would not read all of the videos at once and store them in RAM. They would iteratively load a few videos and process them before going on to the next set. 

I think it would make sense to not include the data loaded to drive as "downloaded" towards the quota unless the user then decided to locally download a copy from the connected runtime.

Alternatively, this could be something which is available by using the colab Pro version, although I would hope that it is possible in the free version!

**Comment by blois** [comment]
The filesystem read from a mounted directory still counts as a download. It's best to copy the file to a directory outside of the mounted Drive folder- you'll get much better file read performance as well.

**Comment by Ryandry1st** [comment]
What directory would you recommend? Only 30GB are available on disk with a GPU backend so you cannot obviously keep videos on disk. At the same time, there is excellent software available for pulling iteratively from mounted filesystem (tf.data) so that you do not have to keep all of it on disk. So performance is not really a problem so much as space is, which is the point of using a mounted drive.
