### ISSUE TITLE
webbrowser module does not working

### ISSUE THREAD

**Issue by harshdhamecha** [googlecolab/colabtools#1162]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
  `import webbrowser
   webbrowser.open_new_tab('www.google.com')`
- Describe the expected behavior:
   It should open a new tab of url www.google.com. Instead of that, it is giving me false as a output.
- The web browser you are using (Chrome, Firefox, Safari, etc.):
   Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
  https://colab.research.google.com/drive/1yFkp-GXUEkTY-PhN2pvRto8GygOJ3-mW#scrollTo=4DQOvtsK3jub

**Comment by tnovikoff** [comment]
Tracking internally at b/154955041

**Comment by jakevdp** [comment]
Hello – it is not possible to control your local web browser using Python code running on Colab.

The issue is that ``webbrowser.open`` accesses the webbrowser *on the machine which runs the code*; in this case, that machine is a Google Cloud VM that runs all Python code you execute on Colab.

The only way to control your browser from within Colab is via Javascript. For example, you can run:
```
%%javascript
window.open("http://google.com", '_blank');
```
and this will open a new browser tab (though in practice many browsers block such popups for security reasons).
