### ISSUE TITLE
Can't change Python version of runtime

### ISSUE THREAD

**Issue by Julia-Melgare** [googlecolab/colabtools#1164]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I need to use Python2 for the project I'm currently working on, however since I reset the runtime today (04/21/2020) [I no longer see the option to change Python version in the Notebook Settings, only hardware accelerator](https://i.stack.imgur.com/HEO30.png), and when running !python --version I get the output 3.6.9 (which is not what I need)

- Describe the expected behavior:
I expected to see the option of changing the runtime Python version in the Notebook Settings options.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Google Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1vqIxJUEfBYGU8xbeM1uSmvtqvj17eh8o

**Comment by jakevdp** [comment]
This behavior is intended.

Python 2 reached its end of life on January 1, 2020, and is no longer supported by the Python developer community. Because of that, Colab is in the process of deprecating Python 2 runtimes, and has been warning users of this each time they choose and connect to Python 2 since the middle of 2019. See https://research.google.com/colaboratory/faq.html#python-2-deprecation for details.

Because of this, we recommend moving any important work to Python 3. Although there is currently no way to choose Python 2 via Colab's UI, existing Python 2 notebooks will connect to a Python 2 runtime for the time being. So, for example, if you open a notebook like this one: https://colab.research.google.com/gist/jakevdp/de56c474b41add4540deba2426534a49/empty-py2.ipynb and execute code, it will execute in Python 2 for now. I would suggest following that link, and then choosing *File->Save A Copy In Drive* to get your own copy of an empty Python 2 notebook.

But please be aware that at some point in the future, Python 2 runtimes will be entirely unavailable in Colab, even for existing Python 2 notebooks.

A side note: you said you had been switching from Python 2 to Python 3 and back in order to restart your runtime: an easier option (that does not involve changing your runtime setting) is to choose *Runtime->Restart Runtime*.

**Comment by Julia-Melgare** [comment]
Thank you for the reply and your help. I do understand that Python 2 is soon to be completely removed from Colab, however I've been using it temporarily to work from home on replicating an older work that can only be run in Python 2 without having to use one of my physical machines that don't have enough computing power and resources.

**Comment by linda-farias** [comment]
I'm also having the same problem, because I want to run a job, but it only runs in python 2
