### ISSUE TITLE
Google sheets not working on gpu runtime

### ISSUE THREAD

**Issue by himanshu-attri** [googlecolab/colabtools#1173]
AttributeError                            Traceback (most recent call last)
<ipython-input-12-33ee9d8412a0> in <module>()
      1 from google.colab import auth
----> 2 auth.authenticate_user()
      3 
      4 import gspread
      5 from oauth2client.client import GoogleCredentials

4 frames
/usr/local/lib/python3.6/dist-packages/google/auth/_default.py in _load_credentials_from_file(filename)
    110 
    111         try:
--> 112             credentials = credentials.Credentials.from_authorized_user_info(info)
    113         except ValueError as caught_exc:
    114             msg = "Failed to load authorized user credentials from {}".format(filename)

AttributeError: module 'google.auth._cloud_sdk' has no attribute 'load_authorized_user_credentials'

**Comment by craigcitro** [comment]
Can you include a minimal, public notebook that reproduces this error?

(I'm guessing the issue is that you've managed to install a different version of `google-auth`.)

**Comment by kunderemp** [comment]
@craigcitro  and @tnovikoff , since I also encounter the same problem, I gave minimal public notebook here:
https://colab.research.google.com/drive/1jyksTdHqkKO24ptDPQ3mFz8X6G5tu938

In the first attempt, the first cell gave error message:
_ERROR: google-colab 1.0.0 has requirement google-auth~=1.7.2, but you'll have google-auth 1.14.1 which is incompatible._

In the 2nd attempt
the first cell did not give error message so I continue to run the next cell. 
The next cell give a link which redirected to login page and asked me to give access for Google Cloud SDK. After giving access, it gave long string which I should copied back to notebook. After copied the long String to the notebook than the error message appeared.

AttributeError                            Traceback (most recent call last)
<ipython-input-3-8ca9bcf71114> in <module>()
----> 1 auth.authenticate_user(clear_output=True)
      2 datadocument = gc.open('Catatan Data Covid 2019  Indonesia')

4 frames
/usr/local/lib/python3.6/dist-packages/google/auth/_default.py in _load_credentials_from_file(filename)
    110 
    111         try:
--> 112             credentials = credentials.Credentials.from_authorized_user_info(info)
    113         except ValueError as caught_exc:
    114             msg = "Failed to load authorized user credentials from {}".format(filename)

AttributeError: module 'google.auth._cloud_sdk' has no attribute 'load_authorized_user_credentials'

**Comment by craigcitro** [comment]
You need to restart the runtime after the `pip install` command; that's what the warning is telling you.

I've confirmed that if you *don't* restart the runtime, you'll see the error you're describing; if you do, everything works.
