### ISSUE TITLE
Detect dark mode in Colab CSS

### ISSUE THREAD

**Issue by shoyer** [googlecolab/colabtools#1214]
Is there a standard way (e.g., CSS variables) to detect dark mode in Colab?

I'd like the my HTML reprs to look good in both light and dark mode

(e.g., see https://github.com/pydata/xarray/issues/4024 for a similar issue with VSCode)

**Comment by blois** [comment]
You can use the `html[theme=dark]` selector.  In Colab we use this in combination with CSS custom properties to make theming a bit easier. For example:

```html
<style>
  html {
    --button-color: #333;
    --button-text: #AAA;
  }
  html[theme=dark] {
    --button-color: #AAA;
    --button-text: #333;
  }
  button {
    background: var(--button-color);
    color: var(--button-text);
    font-size: 16px;
  }
</style>
<button>click me</button>
```

https://colab.research.google.com/gist/blois/c2a4dc971d46080264362733427d1b41/themes.ipynb

You _could_ inspect the DOM to see the property names that Colab uses but I would strongly discourage using Colab's properties directly as we don't consider that a stable API.

**Comment by shoyer** [comment]
Thanks @blois, xarray will support Colab's dark mode in our next release :)

**Comment by drscotthawley** [comment]
I know this Issue is old and closed, but...any chance this changed since 2020?  
Because @blois's snippet doesn't change the "click me" button's colors when I switch themes (and/or Reload, and/or Factory Reset Runtime) when I run it in Colab.  
It's always a dark button with light text. 

(Found this issue when searching on how to detect dark mode in Colab)
