### ISSUE TITLE
gspread.authorize() fails

### ISSUE THREAD

**Issue by geniajh** [googlecolab/colabtools#1224]
##Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:  gspread.authorize() fails

- Describe the expected behavior: gspread.authorize() should not fail.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/1TNhhpdCpBDE0oZ67XLrhawCCE8QEgx4c

The issue is pretty much self-explanatory.  I use gspread library following the example in the colab example.  This part did not cause any trouble, but it does not work any more...

<img width="1379" alt="screenshot" src="https://user-images.githubusercontent.com/21032856/81373615-171a0a00-9138-11ea-9cdf-12f46ec45795.png">

**Comment by craigcitro** [comment]
Thanks for the report!

The issue here is that you need to restart your runtime after installing `gspread` -- it's updating `google.auth`, which is already loaded when you start colab.

You'll see the warning if you drop `--quiet` in the cell above; I noticed that's also what we use in our snippet, so we'll need to clean that up, too.

Internal tracking: b/156052307

**Comment by geniajh** [comment]
Thank you!  It works.  Yes, please update the tutorial snippet as well.
