### ISSUE TITLE
Update TensorFlow Addons to 0.11.2

### ISSUE THREAD

**Issue by seanpmorgan** [googlecolab/colabtools#1243]
Hi Colab-team,

Would it be possible to increase the version of TensorFlow Addons in the default environment of Colab. Since upgrading to TF 2.2 custom ops may unexpectedly crash. There have also been a lot of updates to Addons that would be great to provide users with.

- Describe the current behavior:
`tensorflow-addons == 0.8.3`

- Describe the expected behavior:
`tensorflow-addons == 0.10.0`which was built against TF 2.2.0 and will prevent https://github.com/googlecolab/colabtools/issues/1229 from happening

**Comment by seanpmorgan** [comment]
Hi, is there anyone we can speak to regarding this update?

**Comment by bhack** [comment]
@seanpmorgan If we have this long waiting queue here we need to enforce version in colab tutorial on our repo.

**Comment by metrizable** [comment]
@seanpmorgan This issue was filed a while ago and there have been a number of upgrades to our ecosystem including TensorFlow since then. I just successfully invoked `pip install tensorflow-addons` (we do not include it by default in the Colab runtime). If you are still experiencing issues, please file a new issue and provide a minimal reproducible notebook.
