### ISSUE TITLE
Install colab for offline use?

### ISSUE THREAD

**Issue by MyFakeHub** [googlecolab/colabtools#1374]
I would love it if I could download and install a `colab` package that lets me run local notebooks like jupyter.

Is there a way to do that? Is there a package I can install like `pip install colab` and then I could run `colab notebook` from terminal to run locally and offline my python notebooks?

**Comment by craigcitro** [comment]
There's no way to run the colab frontend locally.

If you'd like to use the colab frontend with a local runtime, see: https://research.google.com/colaboratory/local-runtimes.html

**Comment by lnryan** [comment]
Hello,

The only thing our team really needs from the collab libraries is the `auth` module as we want to preserve the individual login/token interaction and have this be specific to the individual's access rights (ie rather than binding to a service user). 

Is there an alternative google library that provides the same functionality? 


**Note:** I can respect that the collab team wants to encourage use of their in-the-cloud product; however we found it did not work well for our team within a large organization because the repo selection interface is buggy and assumes a separate repo for notebooks rather than notebooks within a related mono repo.

**Comment by jwvanderbeck** [comment]
So then how are we supposed to enable third party widgets when running locally if we can't run the colab module locally?
```
#@title Enable third party widgets
from google.colab import output
output.enable_custom_widget_manager()
```
I need to be able to run that but can't because I can't install colab package?

**Comment by 100rab-S** [comment]
@jwvanderbeck Exactly! 
In my case, I'm trying to use `tqdm` in notebook mode, which btw works fine with Jupyter Notebooks.
`from tqdm.notebook import tqdm`

But the notebook mode of `tqdm` does not work on the local colab connection. For that, I need to run
```
from google.colab import output
output.enable_custom_widget_manager()
```
Since the `google` package here is not available locally. I'm unable to...

@craigcitro What do we do here?

**Comment by sebbov** [comment]
If you can use Docker, try the _Colab Docker runtime image_ option at https://research.google.com/colaboratory/local-runtimes.html.  As explained there, the resulting runtime will include packages found in our hosted environment.

**Comment by sebbov** [comment]
There are no plans of open sourcing the `colab` package, or offering hosted features in the local setup besides Docker in general.  In case you give it another look, Docker has options that may help with the limitations you perceived. You can for instance map files from the host to the container, install packages in the runtime and keep those around across reboots, extend the image using your own Dockerfile, etc.  Nothing Colab specific -- Docker tutorials should be helpful.  It is a larger effort than just being able to install `colab` in your situation, unfortunately.

**Comment by 100rab-S** [comment]
@sebbov Thanks for clarification. Okay I'll look into it and see if I can make it work as required.
