### ISSUE TITLE
Requesting update the pymc3 package

### ISSUE THREAD

**Issue by HinLeung622** [googlecolab/colabtools#1383]
- Describe the current behavior:
`pymc3.summary(trace)` returns `TypeError: concat() got an unexpected keyword argument 'join_axes'`

- Describe the expected behavior:
A pandas dataframe should be displayed with summaries of variables in the trace

This issue is caused by pandas being updated to v1.0, but pymc3 was not, see this pymc3 issue for reference: https://github.com/pymc-devs/pymc3/issues/3805

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1RkrgAnDqdwA-Y3oHF1l1oq7gGW5nfbYy?usp=sharing

P.S. Could you also add the arviz package to Colab? It is needed for plotting traceplots of pymc3, currently I am having to download pymc3 traces from drive back to local and plot there.

https://github.com/arviz-devs/arviz

**Comment by metrizable** [comment]
@HinLeung622 Thanks for reporting the issue. We've upgraded both `pymc3` and `pandas` since it was filed and the bug no longer occurs.

![47VbCig3jrQ8dfR](https://user-images.githubusercontent.com/65414824/224060361-e293e2e5-82a1-4c52-97ab-d4305573f9c6.png)

We have additional upgrades of these and other packages planned in the near future. Stay tuned.
