### ISSUE TITLE
Issues with Colab

### ISSUE THREAD

**Issue by kathrinkajderowicz** [googlecolab/colabtools#1442]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

Hi Craig, sorry for not being specific earlier. The issue is that I cannot connect to the drive randomly. I will re-run the code one hour and it works fine (literally just mounting dataset), and then next hour it says that directory or file doesn't exist but it clearly does when I list the contents of my current directory. I come back in an hour, and the code runs. The issue is very sporadic. 

I've tried Chrome & Safari. One workaround to this issue I found a few days ago was that if I opened a new gmail account and redownloaded the data and opened an identical Colab notebook in the new account, it would work again.

**Comment by craigcitro** [comment]
Can you give more specifics about the failure, with a full stack trace?

In particular, for us to make any progress, here are the kind of things we need to know:
* are you calling `drive.mount` or using the "Mount Drive" button in the files pane?
* what error do you get?

In particular, I'm *guessing* that the problem is that you're hitting Drive quotas, at which point random drive operations (both mounting Drive and loading the notebook itself) will fail with quota-related errors. Unfortunately, there's nothing we can do there -- we have no control over the Drive API limits.

**Comment by craigcitro** [comment]
#1020 may also be useful to look at.
