### ISSUE TITLE
ipywidgets.Tab not working properly in Colab

### ISSUE THREAD

**Issue by nneibaue** [googlecolab/colabtools#1446]
**- Current behavior:**
I am trying to use the Tab widget from ipywidgets, but the children are all being rendered inside the first tab.
![image](https://user-images.githubusercontent.com/9022917/88461914-fde64700-ce64-11ea-92d9-b684325eec9d.png)

**- Expected behavior:**
The exact same code works fine in a Jupyter Notebook. Children are being rendered individually in different tabs.
![image](https://user-images.githubusercontent.com/9022917/88461889-cd9ea880-ce64-11ea-9116-70a9a389d93a.png)

**- Web browser:** Google Chrome

**- Link to minimal notebook that reproduces the issue:**
https://colab.research.google.com/drive/1sMHKvj7adqoTjA_g2X-b9-KuWZilikjJ?usp=sharing

**Comment by blois** [comment]
Thanks for the report- this should now be working.

**Comment by nneibaue** [comment]
Thanks...looks great!

**Comment by raven44099** [comment]
I must reopen this issue, because it is bugging around. The good news, the probelm is pinned down:
When I start google colab and run the `ipywidgets.Tab()` it shows it correctly, then I run two codes of line and the same `ipywidgets.Tab()` again, but it doesn't show it properly anymore.

<details><summary>Code:</summary>
<p>

```
import ipywidgets as widgets
tab_contents = ['P0', 'P1', 'P2', 'P3', 'P4']
children = [widgets.Text(description=name) for name in tab_contents]
tab = widgets.Tab()
tab.children = children
tab.titles = [str(i) for i in range(len(children))]
display(tab)
```
Then:
```
from google.colab import output
output.enable_custom_widget_manager()
```
Finally, which doesnt display (identical to above):
```
import ipywidgets as widgets
tab_contents = ['P0', 'P1', 'P2', 'P3', 'P4']
children = [widgets.Text(description=name) for name in tab_contents]
tab = widgets.Tab()
tab.children = children
tab.titles = [str(i) for i in range(len(children))]
display(tab)
```

</p>
</details>
