### ISSUE TITLE
NVIDIA driver error

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#1457]
- Describe the current behavior:
AssertionError: 
The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

when using GPU + torch==1.6
```
x = torch.randn(2, 2, dtype=torch.cfloat).to('cuda')
```

- Describe the expected behavior:
no error

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

**Comment by relotonp** [comment]
It works if you just use

     import torch

And use a factory reset runtime.

But if you need a different version of pytotch

    !pip install torch==1.5.0

the error still persists

**Comment by colaboratory-team** [comment]
CUDA libs & apps must match. The error in the original bug report is telling you you've installed a mismatched torch wheel.
#1454 tracked the upgrade to 1.6.0, and provides URLs to vary if you want other versions of torch, though make sure to match the CUDA lib version on the colab VM (currently 10.1 but subject to change in future).

**Comment by GenoXu** [comment]
Same error in ffmpeg with --enable-nvenc.
It worked just fine 3 days ago, but now it throws this error:

`[hevc_nvenc @ 0x55defbb87c00] Using device cuda0 (type cuda) with hevc_nvenc encoder.
[hevc_nvenc @ 0x55defbb87c00] Loaded Nvenc version 11.0
[hevc_nvenc @ 0x55defbb87c00] Driver does not support the required nvenc API version. Required: 11.1 Found: 11.0
[hevc_nvenc @ 0x55defbb87c00] The minimum required Nvidia driver for nvenc is 470.57.02 or newer
[hevc_nvenc @ 0x55defbb87c00] Nvenc unloaded`

I think this is because sdk version was updated in ffmpeg4 and ffmpeg5.
I tried updating Nvidia driver, but it's stucked at version: `460.32.03`

Please consider updating the driver.
