### ISSUE TITLE
Showing OAuth code while mounting Google Drive

### ISSUE THREAD

**Issue by E-Newman** [googlecolab/colabtools#1581]
A couple of days ago I noticed that Colab doesn't mask the OAuth code pasted into the field "Enter your authorization code" while executing drive.mount() . It used to be masked by dots. Is it a fine behaviour?

Minimal code snippet:
https://colab.research.google.com/drive/1di7MZROFFdUk4dFJiioV_Qz1Byc2PwcP?usp=sharing

**Comment by colaboratory-team** [comment]
Indeed, this is fine. OAuth authorization codes are one-time use only, so after a code is used in a drive.mount() call it is no longer usable for any other purpose.
This change was made to mitigate confusion arising from a copy/paste that was pasting something other than a security code into the input box (due to the copy not happening as expected).
Unrelated to the above change, another recent change is that once the mount is successful, the prompt+code will be cleared from cell output. This is done both to declutter notebooks of boilerplate and to hopefully help allay concerns such as the one in this report.

Thanks for checking!
