### ISSUE TITLE
pip installs wrong version of keras unless run twice

### ISSUE THREAD

**Issue by eyaler** [googlecolab/colabtools#1624]
i am using keras 2.2.5 (as later versions are silently broken). recently pip install on colab is installing a different version than requested, and i need to run the command twice to get the version i want. attaced sceenshot from fresh runtimes.

![image](https://user-images.githubusercontent.com/4436747/95325960-8bed9d80-08aa-11eb-9762-e77a4a76096e.png)
![image](https://user-images.githubusercontent.com/4436747/95325991-95770580-08aa-11eb-8a60-557834702eb8.png)

**Comment by craigcitro** [comment]
This is indeed confusing; the underlying issue is that we have two copies of keras installed (one for TF 1.x, and another for TF 2.x); when you run the single install command, it's removing the TF 1.x copy, but then discovering the TF 2.x copy and deciding it's done. 😕 

It's far from robust, but here's a workaround that at least gets you back to sanity for this package:
```
%tensorflow_version 1.x
import sys
!pip install --prefix {sys.path[0]} --upgrade keras==2.2.5
```
