### ISSUE TITLE
tf.keras.utils.get_file is not loading file

### ISSUE THREAD

**Issue by Themrpie** [googlecolab/colabtools#1663]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
data_dir doesn't load anything
- Describe the expected behavior:
data_dir should load a database of flower images
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Microsoft Edge
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
Is not loading, on the next step it gives an error:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.keras/datasets/flower_photos'

**Comment by JohannesBauer97** [comment]
This happens when you call `tf.keras.utils.get_file(...)` with a different `fname` then it is in the downloaded dataset.
I made an example using the flowers dataset from [this keras tutorial](https://www.tensorflow.org/tutorials/images/classification).

Working and not working example included here:
https://colab.research.google.com/drive/1-HIDQFZJF4Mly_yRT-Dv--HljytlkD-u?usp=sharing

When I lookup the [api docs](https://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file) I would say we're using it right. Even on my local machine it's working when I specify any `fname`. So for me it's a bug in Google Colab.

**Comment by colaboratory-team** [comment]
@JohannesBauer97 your "Not working example" behaves identically outside of colab in a:
```
$ docker run  -u $(id -u):$(id -g) -it tensorflow/tensorflow
```
so this doesn't seem like a colab issue.

@Themrpie impossible to help without the "minimal, public, self-contained notebook that reproduces this issue" requested in the issue template.
