### ISSUE TITLE
cannot mount gdrive

### ISSUE THREAD

**Issue by Charlie72** [googlecolab/colabtools#1692]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by Charlie72** [comment]
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:

When trying to execute the above code and copying and pasting the authorization code (manually) the code appears to be stuck in an infinite loop. I have tried this in Firefox and also in Chrome in both private and Incognito modes and also tried a variety of different things recommended on Git and Stackoverflow - nothing works. NB I have blanked out the authorization code for security reasons, I have tried the copy button and also manually copying the code and pasting, it still doesn't work.

Tks.

**Comment by colaboratory-team** [comment]
Thanks for the report. Can you share a screenshot of the cell output during the hang? Also, if you have many files in your Drive root directory, the mount operation may take [some time to complete](https://research.google.com/colaboratory/faq.html#drive-timeout).

**Comment by Charlie72** [comment]
Hi Colab Team,

Please see attached as requested. I only have about 35 files on my goggle
drive and only used 1.5Gb of the allocated 15.
I think I just need to specify the pathway correctly.

Tks.

Best Regards

Adam

**Comment by Suttsy3** [comment]
Hi,

I have also not had any success using the drive mounting function (specifically the drive.mount() call) over the last two weeks. I was able to mount properly (but not using the function, using the folder button on the sidebar) through Thursday of last week (wk 45), but since Thursday around noon I have not been able to successfully mount my drive (neither have friends trying to access the same notebook). This includes using the workaround to only copy the text using the cursor and pasting the code into notepad before copy/pasting into the prompt. The cell just forever buffers, when interrupted it looks like it is having issues with verifying/recognizing the authorization code? I've included an image of the interrupted cell response.

![image](https://user-images.githubusercontent.com/43011700/98551763-acbf5f00-226b-11eb-8349-213ddba15d4d.png)

Thanks,
