### ISSUE TITLE
Installing gym-2048 crashes colab session

### ISSUE THREAD

**Issue by niyuzheno1** [googlecolab/colabtools#1712]
- Describe the current behavior:

After installing gym-2048 and restarting the session, colab notebook crashes. 

- Describe the expected behavior:

Everything should go smoothly.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome.

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/154a670ZXjy39K54h-L7asmxnxGJKBowK?usp=sharing

**Comment by craigcitro** [comment]
The issue is that gym is requesting a numpy version that's too old for the version of matplotlib we have installed, which leads to import errors at startup. (This is what all the warnings in red are suggesting in the `pip` output.)

I'd try asking the package authors to fix their requirements, or follow the install with a `!pip install --upgrade numpy`.
