### ISSUE TITLE
how do I understand when colab reaches its limitation?

### ISSUE THREAD

**Issue by aliamiri1380** [googlecolab/colabtools#1743]
I was training a model and I waited for a long time and suddenly colab limit reached and I couldn't save my model.
it could be better if at least it showed me a warning before disconnecting the runtime

**Comment by metrizable** [comment]
@aliamiri1380 Resource utilization (for both CPU and GPU) can be viewed via the menu `Runtime > View Resources`

![Zc84vHzgkjVjY6Z](https://user-images.githubusercontent.com/65414824/231787888-bf192c0e-594e-4458-84f7-0830b808acbd.png)

As well, for people who have purchased compute units, we provide a view of remaining units available.

Since this issue was filed a while ago, please open a new issue to report additional requests or bugs.
