### ISSUE TITLE
Print Error in Colab 

### ISSUE THREAD

**Issue by CMA29** [googlecolab/colabtools#1744]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

Colab is not printing a complete print statement.

- Describe the expected behavior:

![image](https://user-images.githubusercontent.com/65372979/100550381-e108b880-3236-11eb-8276-7dc22e58fc59.png)

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by metrizable** [comment]
@CMA29 Thanks for reporting the issue. I am not able to replicate the extra line in the output between `True` and `Is pizza == "peperoni"? I predict False.` lines.

![tHTYZbfeL4baVUu](https://user-images.githubusercontent.com/65414824/230696180-bd57ccf3-c942-4489-bca6-e66491a08e4e.png)

Since this issue was filed a while ago, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
