### ISSUE TITLE
Session Timeout Under 20 Min  - Colab Pro

### ISSUE THREAD

**Issue by stefanjuang** [googlecolab/colabtools#1745]
- Describe the current behavior:
Colab Pro Timeout before finish building one library.
Tried both GPU and TPU Options.
Timeout happens regardless of whether a cell is running or not.
Timeout 5 times within an hour

- Describe the expected behavior:
Two weeks ago the same code can be built and run for 12 hrs+ on TPU High RAM Option.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

**Comment by stefanjuang** [comment]
Tried on Only CPU Option.
Colab Pro timeout in 11 min while running an infinite loop with RAM to spare

**Comment by zakindra** [comment]
same bro session  timeout under 25 Min

**Comment by youneedlifeV** [comment]
Same issue for me also

**Comment by matheus176** [comment]
same for me, i don´t know what´s happening with colab but since a few weeks ago i hit the usage limit within 15-20 minutes

**Comment by whoafridi** [comment]
same here. maybe bugs !

**Comment by stefanjuang** [comment]
After 17 days still the same issue.
Bump

**Comment by stackerofwheat** [comment]
same issue. even when creating new accounts.

**Comment by AamirVakeel** [comment]
Does this issue still exist?

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro and Pro+ subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback and mention this GitHub issue.

For paid subscribers, if you have billing questions you can contact colab-billing@google.com
