### ISSUE TITLE
Ticks and axes being not clearly visible while using dark theme

### ISSUE THREAD

**Issue by zylbergs** [googlecolab/colabtools#1796]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
my axes and tick label being too dark (almost not visible) during colabs dark theme.
I'm using seaborn visualization
- Describe the expected behavior:
axes and tick label being visible and match with the dark theme like jupyter
- The web browser you are using (Chrome, Firefox, Safari, etc.):
google chrome
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1B6PifepRHdYTSceIXV4vZmbrlk2YUgsp#scrollTo=r660YjIcyDBT

**Comment by blois** [comment]
Matplotlib can be switched into dark mode with:

```python
plt.style.use('dark_background')
```

See https://matplotlib.org/3.1.0/gallery/style_sheets/dark_background.html

**Comment by Psp29onetwo** [comment]
I found one solution for expanding the plot canvas a bit so that x and y ticks will get visible.

You need to add one line `plt.style.use('default')` after importing the matplot lib module in notebook.


<img src="https://i.stack.imgur.com/eIc32.png">

See my ticks are outside the canvas before.

<img src="https://i.stack.imgur.com/Yd7LZ.png">

After adding the line the tick got added to the canvas itself no further modification was needed.

<img src="https://i.stack.imgur.com/jNeEg.png">

As you can see in the above image this will pull the x and y ticks in the canvas to make it visible without changing or modifying ticks or plot color, it will make it easier to collaborate your work with others.


  [1]: https://i.stack.imgur.com/eIc32.png
  [2]: https://i.stack.imgur.com/Yd7LZ.png
