### ISSUE TITLE
Unable to cancel Colab Pro, Google team said they can't too.

### ISSUE THREAD

**Issue by JonathanSum** [googlecolab/colabtools#1801]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

![image](https://user-images.githubusercontent.com/21982975/103695132-e2718300-4f50-11eb-9623-108729181368.png)

For the option of stackoverflow, I can't because it has blocked me.

**Comment by tnovikoff** [comment]
Once you click on your Colab subscription in pay.google.com under the Subscriptions & services tab, click Manage and then you should see an option to cancel your subscription. You may need to scroll down to see the option to cancel the Colab subscription. 

![4uRpEbekhgN8TFj](https://user-images.githubusercontent.com/1750190/103709917-8ca8d500-4f68-11eb-96a9-e6f8aebded16.png)

Note that in order to find your Colab subscription in the Subscriptions & services tab, you will need to use the correct google account and the correct payments profile, within pay.google.com.

If you are unable to cancel the subscription yourself, you can email colab-billing@google.com and they can cancel your subscription for you. Include the order number from your receipt emails for fastest service from Colab billing support.

**Comment by JonathanSum** [comment]
This is just a note. I am not sure. I checked today and found out the cancel button exists. Before I can't find it and the Google team me that they can't too(see the first post I made).
