### ISSUE TITLE
can no connect "Sorry, no backends available. Please try again later"

### ISSUE THREAD

**Issue by MartinCastellano** [googlecolab/colabtools#1819]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:i can not connect ...Sorry, no backends available. Please try again later 

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by angel7qqpp** [comment]
I have the same issue!! How can we solve it?

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback

**Comment by angel7qqpp** [comment]
Thank you for the reply. I already sent feedback on Colab, but no one
responded and this issue still blocks me here. Is there any other help I
can get?
