### ISSUE TITLE
Colab pro not allocating more than 949 MiB out of 16 GiB.

### ISSUE THREAD

**Issue by BishwaBS** [googlecolab/colabtools#1834]
Bug report for Colab: http://colab.research.google.com/.

- I recently upgraded to colab pro. Since then, I haven't been able to get more than 949 MiB of GPU out of 16 GiB available GPU memory. I made sure i selected GPU and "high-ram" on the notebook settings.

I am training mask rcnn model. The code runs okay and starts to train the model, but gets stalled at the first epoch.

**Comment by sasukec2** [comment]
same here
![error 1](https://user-images.githubusercontent.com/109186646/179332394-a7c3bac2-f5b6-4815-81c7-ca4697cd8b1c.png)

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Before sending, please note a high RAM assignment refers to *system* memory (as returned by `!grep MemTotal /proc/meminfo`), not *GPU* memory (as returned by `!nvidia-smi --query-gpu=memory.total --format=csv`). All GPU chips have the same memory profile.

Please submit feedback in product within Colab at Help > Send feedback
