### ISSUE TITLE
Sorry, no backends available. Please try again later.

### ISSUE THREAD

**Issue by Ne0EX** [googlecolab/colabtools#1858]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: I unable to connect to any sessions. It's said "Sorry, no backends available. Please try again later."

- Describe the expected behavior: I read the issue#1287 but I want my account can be use again.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by pleabargain** [comment]
Getting the same 2 days in a row!
Sorry, no backends available. Please try again later.

**Comment by TatsuMaki01** [comment]
I am also getting the same issue.

**Comment by brillim** [comment]
Same for me: from yesterday I obtain same message.
There is a workaround ?

Thx

**Comment by Rafat97** [comment]
@colaboratory-team 

I am facing same issue. 
When was I trying to connect my runtime. They gives this error message-

![image](https://user-images.githubusercontent.com/21246862/128703159-b709bfb1-0f55-43e8-a90a-408f67f45948.png)

Can you please check? 
Thank you.

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback and mention this GitHub issue.
