### ISSUE TITLE
Colab consumes twice disk space as expected when reading/writing from gdrive

### ISSUE THREAD

**Issue by mfiro** [googlecolab/colabtools#1915]
Hi everyone!

- **Describe the current behavior**:
I have a tar file in my google drive which is around 19GB. After mounting the drive into the notebook, there is still 29GB free disk space in Colab, but I am not able to extract file directly like this. At some point the disk space becomes zero and it gives an full disk error

   `!tar -xf /content/drive/MyDrive/myfile.tar -C ./`

    And also the file is not compressed at all. The extracted file is as big as the tar file. With the current behaviour there is no way at all to unzip or extract a file more than 15GB. I even purchased Google drive storage with the hope that I can extract directly into the workspace. But it doesn't work.

- **Describe the expected behavior**:
Expected behaviour is if there is 29GB free disk space, I am able to extract a 28-29 GB file from gdrive directly into it. 

- **The web browser you are using (Chrome, Firefox, Safari, etc.)**:
Chrome

I don't know if what is happening is an expected behaviour, but it's really annoying.

**Comment by colaboratory-team** [comment]
Colab's implementation of mounting Drive uses a local cache that will evict contents as the disk fills up, but active use will prevent this eviction. You might be able to work around this issue by splitting your .tar file into parts, and extracting them serially (so that earlier parts' .tar files can be evicted from the cache after they're extracted).

This isn't great, but there are no plans to change how this integration works.

(also, note that purchasing Google Drive storage doesn't affect disk space in Colab; on the other hand, [Colab Pro](https://colab.research.google.com/signup) does offer more disk)

**Comment by chrisyeh96** [comment]
I am running into this exact same issue. However, the response from @colaboratory-team doesn't address why colab seems to consume *twice* the disk space as expected.

**Comment by colaboratory-team** [comment]
@chrisyeh96 the original report described untar'ing from Drive to the VM; the local read-through Drive cache ends up with a copy of the tar file, and the extracted contents from that tar file are also on the local VM's disk, consuming twice the size the tar file in total.

**Comment by jamm1985** [comment]
You can also use this trick: https://gist.github.com/jamm1985/df7b8c0abb346d3dbe403bf06ae4f46f
