### ISSUE TITLE
I have got a colab pro.  But I found I can't even  use colab.  It says:"Sorry, no backends available. Please try again later"

### ISSUE THREAD

**Issue by tiger-jie** [googlecolab/colabtools#1919]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by tiger-jie** [comment]
Your algorithm is so depressing

**Comment by taesiri** [comment]
I am experiencing a similar thing. Having a Colab Pro subscription, but my instance will terminate after 4 or 5 minutes. 
A friend of mine without a pro subscription has no problem!

**Comment by sander2825** [comment]
Same here. not even able to connect since subscribing to Colab pro

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
