### ISSUE TITLE
My Colab is running super slow and glitching 

### ISSUE THREAD

**Issue by Fareeda84** [googlecolab/colabtools#1984]
Bug report for Colab:  https://colab.research.google.com/drive/1HbStwG7wYLFvC6-jKR0N8Ua5_C_YlROb#scrollTo=YN7aTT8snjOQ.

- Describe the current behavior:
My Colab is running super slow and glitching. I am also getting a message to enable third party access but 
![Untitled_1](https://user-images.githubusercontent.com/57854708/116645330-b67b8100-a9c9-11eb-8b24-b5acfab51b0d.png)
![Untitled](https://user-images.githubusercontent.com/57854708/116645337-bc716200-a9c9-11eb-8ed9-a880bb863ed3.png)

my browser (Firefox) has already enabled third party access. 

- Describe the expected behavior:
Running fast

- The web browser you are using (Chrome, Firefox, Safari, etc.):
 Firefox, I also tried other browsers such as Chrome and Mircosoft Edge but still same problem

Also getting below message 
Automatic saving failed. This file was updated remotely or in another tab.

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by blois** [comment]
This error is from the browser attempting to do a lot of work- most likely either large amounts of outputs being emitted by the kernel or particularly complex outputs such as complex visualizations. This could also be caused by browser extensions- in these cases loading in an incognito browser window may resolve the issue.
