### ISSUE TITLE
Edit of code in Colab

### ISSUE THREAD

**Issue by 123nishant** [googlecolab/colabtools#1993]
HI Team, 

I have pulled a github repo into my Colab notebook and edited the python files using 'Colab'. 

Yet when I save it, the files are not getting updated. 
Can you  please help me out what might be the reason for the same ?

**Comment by sukhaniya** [comment]
hi 123nishant 
 you can sign in using your id and then perform changes. even I need a favour if your code get executed how to change the images I wanted to upload using my drive image I am not getting what is !wget and !mv plz help

**Comment by 123nishant** [comment]
!wget is to get the data from a particular link. 

All commands starting with '!' are Linux commands.

**Comment by UmerFakher** [comment]
Hi 123nishant, I am thinking this could be causing the similar issue and then the files 'appearing not to be updated' when opened in Colab. https://github.com/googlecolab/colabtools/issues/1975

What is your notebook called where you made edits and could you also view the jupyter notebook code in Raw through GitHub website to see near the top if it has an incorrect "name" at the top in the metadata.

Might look like this:
    "colab": {
      "name": "notebook_that_you_wanted_to_download.ipynb",
      "provenance": [],
      "toc_visible": true,
      "include_colab_link": true
    },

I am thinking that this "name" would not be the same as the actual name of your notebook that you made changes to/renamed.

**Comment by 123nishant** [comment]
Oh God !
You're right . 
I missed the version details there. 
The "name" was not same. 

Thank you @UmerFakher

**Comment by UmerFakher** [comment]
Ah well its good that fixed it. Super weird. I hope they fix this issue as I'm sure it gives people a lot of headaches! Basically to fix it I think they just need to make sure when you rename a notebook/save a copy to github, it changes the meta-data name as well, or since that may not be possible if you rename it outside of colab, then perhaps they should remove that redundant "name" attribute.

**Comment by 123nishant** [comment]
That's true actually @UmerFakher 

We would need to check through all versions just to check which one we need.

**Comment by UmerFakher** [comment]
Yes it is quite complicated when you have a have a few copies and people make commits. It seems sometimes you can't access your changes or open the notebook at all.https://github.com/googlecolab/colabtools/issues/1998 I just opened one with a GitHub repo just so they can see since you closed this one.
Anyways glad it worked!

**Comment by 123nishant** [comment]
Thanks !!
