### ISSUE TITLE
colab pro：no backends available

### ISSUE THREAD

**Issue by bknbkn** [googlecolab/colabtools#2012]
**Describe the current behavior**
When I connect colab pro， It return “Sorry, no backends available. Please try again later.”，I haven't used it even for a minute since I subscribed.

![image](https://user-images.githubusercontent.com/67318028/118251603-5f51d200-b4da-11eb-9162-734dfac35ff7.png)

Web console return this information:
![image](https://user-images.githubusercontent.com/67318028/118252474-63caba80-b4db-11eb-912c-4dc9d1d7efab.png)

**Describe the expected behavior**
Use colab pro successfully

**What web browser you are using**
Chrome

**Comment by tkmremi** [comment]
Same. I paid for this because i need to do math calcul for my thesis but i never had a backend available !!!

**Comment by sander2825** [comment]
Same here

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback.
