### ISSUE TITLE
My training stopped everytime on 20 hrs

### ISSUE THREAD

**Issue by Jeetendra-Shakya** [googlecolab/colabtools#2024]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
Hi my google colab prod - kicking me out after 20 hours when my training is running - as far i know it should run till my training complete otherwise what's the point of this paid service

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
It should run till training completed

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback.
