### ISSUE TITLE
Runtime disconnected 

### ISSUE THREAD

**Issue by fatajima** [googlecolab/colabtools#2038]
Runtime disconnected
Your runtime has been disconnected due to inactivity or reaching its maximum duration.
To connect to a new runtime, click the connect button below.

every 10 minute

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback.
