### ISSUE TITLE
I was never allocated a GPU.

### ISSUE THREAD

**Issue by Azure-Tang** [googlecolab/colabtools#2049]
**Describe the current behavior**
I tried immense times to apply for a gpu, but i got none. And my roommates was allocated for many times at the same time, so it's the problem not about resources!!!

**Describe the expected behavior**
i was supposed to be allocated a gpu?
**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback.
