### ISSUE TITLE
I have been using Colab for 6 hours (first time) and now "You cannot currently connect to a GPU due to usage limits in Colab."

### ISSUE THREAD

**Issue by HlexNC** [googlecolab/colabtools#2071]
I have been Using Google only for 6-8 hours to render my Blender model, and now I have acceded GPU limit?
I respected using Colab for at least 10 hours. But I can not for some reason.

Also every time I run the rendering code and turn my browser off. My animation breaks. I mean after the rendering stops, the animation doesn't open. I ain't a problem in my code. It is a problem in Colab. When I close my browser or turn my pc off, My animation breaks at the end. But when my browser is on it works normally. The internet says that Colab keeps the code alive when turned off for at least 90 minutes...

Browser: Brave

```
!wget https://download.blender.org/release/Blender2.92/blender-2.92.0-linux64.tar.xz

!tar xf blender-2.92.0-linux64.tar.xz

from google.colab import drive
drive.mount('/gdrive')

filename=('/gdrive/MyDrive/BlenderRenders/chair.blend')

!sudo ./blender-2.92.0-linux64/blender -b $filename -noaudio -E 'CYCLES' -o '//image_####' -s 1 -e 360 -a -- --cycles-device OPTIX
```

**Comment by hkmtechnology** [comment]
How to solve this problem, I am facing the same problem?

**Comment by HlexNC** [comment]
> How to solve this problem, I am facing the same problem?

For now, I'm using my second account. Hope this gets fixed soon. If this isn't resolved, I'm going to create a 3d account bruh

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback.
