### ISSUE TITLE
Colab Pro GPU limit, didn't run anything for 3 days, and now GPU limitation

### ISSUE THREAD

**Issue by farhadinima75** [googlecolab/colabtools#2101]
Hi everyone. I'm a Pro member and this month Colab limiting me too much with this message:
  
> " As a Colab Pro subscriber you have higher usage limits than non-subscribers, but availability is not unlimited. To get the most  out of Colab Pro, avoid using GPUs when they are not necessary for your work."

The funny part is, I didn't open colab for at least 3 days and now I'm still getting this message.

I think this is a bug because the standard version runs correctly without any issue. Am I right @CSEMike, @craigcitro , @jfsny ?
Thanks in advance.

**Comment by JDH1729** [comment]
I've had exactly the same problem, I will be raising a bug report myself.

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback.

**Comment by AdamTameemy** [comment]
I am facing the same problem!! have you managed to solve this problem?
