### ISSUE TITLE
  Resource exhausted: OOM when allocating tensor with shape  Exception in colab pro. Stop paying for colab pro

### ISSUE THREAD

**Issue by manojravuri** [googlecolab/colabtools#2103]
**Describe the current behavior**
I am getting this exception  Resource exhausted: OOM when allocating tensor with shape

I haven't used my colab pro in while. Not sure why it is throwing this error.

**Describe the expected behavior**

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback.
