### ISSUE TITLE
Can't connect to GPU backen

### ISSUE THREAD

**Issue by JDH1729** [googlecolab/colabtools#2108]
I recently took out a Colab Pro subscription, but I have been unable
to connect to a GPU for nearly a week; the error message says:

Cannot connect to GPU backend

You cannot currently connect to a GPU due to usage limits in Colab. Learn more

As a Colab Pro subscriber you have higher usage limits than
non-subscribers, but availability is not unlimited. To get the most
out of Colab Pro, avoid using GPUs when they are not necessary for
your work.

I understand there are still limits with Pro, but I have not been
using GPUs extensively, and not at all for the last few days now.

Bizarrely, I can still access the TPU, so I suspect this to be a bug rather than 
any breaking of limits.

I'm using Firefox, latest version.

**Comment by fabioo29** [comment]
I'm having the same problem... Any feedback on that?

**Comment by JDH1729** [comment]
I was able to log onto the GPU yesterday, but today it's back to saying it can't.

I have to say I'm not loving the lack of any customer care; so far all I have had is a link to some FAQs that didn't apply to my situation, then an email saying they're not really Customer support (despite having Customer support in their sig block!) and to raise a bug on GitHub, which seems to have been ignored. I wouldn't recommend anyone take out a Pro subscription if this is the best they can do.

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

As you're encountering this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback.
