### ISSUE TITLE
Colab not releasing disk space after deletions

### ISSUE THREAD

**Issue by PCdurham** [googlecolab/colabtools#2147]
**Describe the current behavior**
I am tiling images from Google Earth Engine (GEE) to the Colab (pro) disk.  When the code finishes with a GEE images, it makes a tar file on my drive and then deletes all the images with a rm *.tif.  But after the deletion, the disk space is not cleared.  I can confirm that the deletion does happen.  The linked image [here](https://drive.google.com/file/d/1lECJQn5vPh8qqiA3OseEL3ozaJHMR245/view?usp=sharing) shows the work in mid process.  There are only 8476 blocks but the disk space is up to 78Gb. There is another 3Gb file in /content/ but that's it. By my estimation, the small files are roughly 4.5Gb, so add to the the 3Gb file and a conservative 3Gb extra.  There should not be more than 50Gb in use.  To me that seems that it has just cumulated size since the start.

**Describe the expected behaviour**
I am aware that the disk space will have at least 38Gb in use.  But I would expect that after a deletion of my archived files, the disk space would return to this 38Gb level and not gradually creep up.

**What web browser you are using**
Firefox Ubuntu 20.04

**Comment by colaboratory-team** [comment]
Colab's Google Drive integration uses a local cache (see #1915 for some context).
If you `drive.flush_and_unmount()` and `!rm -rf /root/.config/Google/DriveFS` then available disk space should fall back to where it was before you started using Drive.
(we don't aggressively prune the cache because it's a performance win to have a pre-warmed cache for repeated reads)
