### ISSUE TITLE
Urgent help is needed!! Colab pro! 

### ISSUE THREAD

**Issue by AdamTameemy** [googlecolab/colabtools#2152]
I just upgraded colab to pro version which has more features than the free one. I did upgrade to get more processing time!! however, the session is disconnected after few hours. The following notification has appeared that I can not use GPU, which is really frustrating as colab pro should last 24 hours!! 
![Colab](https://user-images.githubusercontent.com/60998713/127190675-b9f5e61c-5c01-40c1-a9c1-0e0cc668b428.png)

I need to complete my work duties, however, this problem is really catastrophic for me. 
By the way, I have another colab pro account and it works just fine, however, the other one is not working ! 

Please, urgent help will be appreciated. 

**What web browser you are using**
(Chrome)

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback and mention this GitHub issue.
