### ISSUE TITLE
Is colab pro work for more 10h with tpu ? Because I am always disconnected

### ISSUE THREAD

**Issue by AlexandreBourrieau** [googlecolab/colabtools#2158]
Is it because I use TPU that I am always disconnected before 10h of colab pro ? Thanks for help

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits
