### ISSUE TITLE
Impossible use GPU as pro user

### ISSUE THREAD

**Issue by khalld** [googlecolab/colabtools#2160]
**Describe the current behavior**
I have been a google colab user for about 2 weeks, I bought the plan to work better on a university project. however about 1 week ago I "consumed" all the available gpu, consequently I decided to wait a few days to resume work. Result? The GPU and the runtime remain connected for a maximum of 2 hours and then they are disconnected, I can use a single session and working without gpu has become impossible. It seems absurd to me to be paying for something that I cannot use, I understand that once you use too many resources you have to have a break, but in this way it is becoming impossible. Anyone know how to fix?

**Describe the expected behavior**
understand how long I have to wait to get back at least 24h of active runtime

**What web browser you are using**
Safari

**Comment by hyolee1999** [comment]
Me too and I can not connect more than one session

**Comment by roddur007** [comment]
any update.....?? im having the same issue too... there is nothing cleare faq about GPU uses limits. 26 hours mean - 24h per month??
or can run a sesion 24h continuously after that it will close automatically but can login after few minute????

plz give a clear picture

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback and mention this GitHub issue.
