### ISSUE TITLE
Too many sessions problem when there is only 1 session

### ISSUE THREAD

**Issue by yebademCC** [googlecolab/colabtools#2181]
I'm having "Too Many Sessions" error when I have only 1 session running (I checked) and I want to open a second one. 

1. Is it possible that there is a sort of "shadowban" on google colab? 
2. I have been doing a lot of file uploads and downloads on google drive, would that be relevant?

**Comment by olaviinha** [comment]
I am regularly facing this issue as well, but I'm assuming it's intentional limitations after consuming a lot of resources for a long time with little interactivity. Recently I've been running some long processes, and had surprise periods of 6 hours, **every day**, with the Pro plant, where I have no access to GPU and can run only 1 session.

 If the notebook in your secondary session is using _High-RAM_ runtime type, try changing it to _Standard_.
