### ISSUE TITLE
I always cannot connect to the GPU backend with Colab Pro +

### ISSUE THREAD

**Issue by fuzihaofzh** [googlecolab/colabtools#2208]
I have subscribed the Colab Pro +. However, it seems to have a more strict limit on the GPU backend than Colab Pro. I always get the notice that I cannot connect to the GPU backend. I have waited for few days without launching any sessions. I just wonder why it is more strict than Colab Pro?

**Comment by WissamAntoun** [comment]
This happened to me when I tried to factory reset one of the two notebooks that I had open in colab pro +.

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly as a Pro user, please email support at colab-help@google.com

**Comment by fuzihaofzh** [comment]
I have bought the Pro+ version. I wonder why I paid a lot of money while getting nothing to use? I have waited for several days and it does not change.
