### ISSUE TITLE
Error when installing mayavi package

### ISSUE THREAD

**Issue by sugatoray** [googlecolab/colabtools#222]
## Error:  
```
failed building wheel for mayavi
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-f0ax2ih4/mayavi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-bpejj6pm/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-f0ax2ih4/mayavi/
```

So far I have tried installing the following dependencies first and that worked:  

```
!apt-get install vtk6  
!apt-get install libvtk6-dev python-vtk6
!pip install -U PyQt5
```
  
But then the following line throws the error mentioned above:  
> **`!pip install -q mayavi`**

Any help in this regard will be helpful. I have already raised [this issue](https://stackoverflow.com/questions/51393710/how-to-install-mayavi-on-colab) in Stackoverflow.com.

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem.

According to the [docs](https://docs.enthought.com/mayavi/mayavi/installation.html#installing-with-pip), you can install `mayavi` via pip:

```
!pip install mayavi PyQt5
```

I've had success doing so and importing `mayavi`:

![72UxjtD46gCkpMv](https://user-images.githubusercontent.com/65414824/234091734-cafba5e4-f379-42cc-a736-039e15045a07.png)

f you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
