### ISSUE TITLE
Not Getting any GPU other than K80

### ISSUE THREAD

**Issue by DKB0512** [googlecolab/colabtools#2229]
After I saw that Colab has started offering Pro+, I've been only getting K80s.
I have an google account which I never used for colab but whenever I try to get any GPU it always says K80.
I don't know why but I tried 15-20 times but still getting the same on an account which I never used for Colab.
Any fixes or Colab has implemented something that makes harder to get any GPU other than K80s for Free users?

**Comment by mmoghadam11** [comment]
same problem

**Comment by shashasha32** [comment]
Welcome to the peasant club my friend. It will be worst from now on day after day .After pro ++++++ , you will be lucky if you get even 1 CPU.

**Comment by xincui-math** [comment]
Do you know what is more interesting? 
I have two accounts, one has no subscription one has pro+. 
The one that has no subscription can access GPU, but my **pro+** got the following message.

**Cannot connect to GPU backend**
You cannot currently connect to a GPU due to usage limits in Colab. Learn more
As a Colab Pro+ subscriber you have higher usage limits than both non-subscribers and Colab Pro users, but availability is not unlimited. To get the most out of Colab Pro+, avoid using GPUs when they are not necessary for your work.

😆

**Comment by DKB0512** [comment]
Looks like they are now playing the money game where people have to pour more money to get better GPUs and even then some of them can't access them like @xincui-math said. But the sad part is how Free users like us (students) who wants to use those GPUs but can't access them due to Google giving priority more to Paid users.

It's same for every product, first they will let all free users try their product and then Boom a payment system where you will get better GPUs and those Free users will get screwed cuz they can't pay for that service anymore.

**Comment by trungnhanit1801** [comment]
I also have similar problems. I have registered Colab Pro package but still only get GPU K80

**Comment by richardxing** [comment]
Same here. I paid for Colab Pro+ and still only have K80.

**Comment by wrccrwx** [comment]
> Same here. I paid for Colab Pro+ and still only have K80.

Here is anther relative discussion on Reddit: https://www.reddit.com/r/GoogleColab/comments/pkew6t/what_processors_have_you_been_getting_on_pro/

**Comment by cperry-goog** [comment]
Consolidating to #2232
