### ISSUE TITLE
Unable to connect to GPU for more than 24h despite being Colab Pro+

### ISSUE THREAD

**Issue by rinabuoy** [googlecolab/colabtools#2232]
I am unable to connect to GPU for more than 24h despite being Colab Pro+. Is it a bug or something else ?

**Comment by xincui-math** [comment]
Same issue here. The funny part is if you use another regular non-pro colab account, you get GPU.

**Comment by rinabuoy** [comment]
Very disappointing indeed.

**Comment by kayhaves** [comment]
i have same issue, still no solution?

**Comment by rinabuoy** [comment]
Not at all. I regretted my subscription now. Nothing is transparent here

**Comment by xincui-math** [comment]
In the past 3 days, I have no GPU access at all.

**Comment by yzhuoning** [comment]
Same here. No GPU available as Pro+ user.

**Comment by buyudtx** [comment]
I have not been able to get the gpu for 4 days

**Comment by khoirularfin22** [comment]
I am unable to connect to GPU for more than 3 days

**Comment by demiantill** [comment]
I haven't been able to connect to a GPU for almost a week now. I think it's fair to say that most Colab Pro+ users would've expected Pro+ to be an upgrade from Pro. But in fact Pro+ has delivered a far worse service than Pro did prior to the last month or so despite costing more than 4 times as much.

**Comment by rinabuoy** [comment]
Still unable to connect to GPU after more than a week.

**Comment by ehzawad** [comment]
> I haven't been able to connect to a GPU for almost a week now. I think it's fair to say that most Colab Pro+ users would've expected Pro+ to be an upgrade from Pro. But in fact Pro+ has delivered a far worse service than Pro did prior to the last month or so despite costing more than 4 times as much.

I have been facing same issue for a week. As a colab pro + user, it is really, really exasperating!

**Comment by ehzawad** [comment]
> Still unable to connect to GPU after more than a week.

Same here dude. You're not alone!

**Comment by xincui-math** [comment]
@colaboratory-team

**Comment by xincui-math** [comment]
This is what I got from their customer service.

In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. GPU runtimes are prioritized by subscription tier, with Pro+ receiving highest priority, then Pro. During periods of heavy usage, we may not be able to allocate our most powerful GPUs to all subscribers. You can read more about Pro allocations here[1].
 
[1] https://colab.sandbox.google.com/notebooks/pro.ipynb#scrollTo=QMMqmdiYMkvi
 
Thanks,
--Colab Pro Customer Support

--------------------
The user experience of colab pro+ is pretty bad. I guess it is better for me to create several google accounts. It gives a far more stable service than my colab pro+.  What I got is a complete **block** from GPU access for around a week.

**Comment by rinabuoy** [comment]
It has been more than a week for me. I cannot quite make sense of this. Paying for being denied of service.

**Comment by cperry-goog** [comment]
Given the amount of traffic here on GitHub, I've composed a longer answer and am responding to and consolidating a variety of related tickets.

Over the past weeks, Colab has observed a sharp increase in demand, making it difficult to satisfy all concurrent demand with premium chips. We continue to prioritize our paid subscribers (Pro+, Pro) for high-end GPU assignments, and by and large, looking at aggregate numbers, and deep diving into specific cases that have been highlighted in our support channels, we observe Colab's GPU availability is well worth the subscription.

We are actively addressing concerns by bringing more GPU runtimes online; this adds a mix of chips into the fleet. New capacity has resulted in improvements over the last few days. Note that due to offering on-demand resources at scale, we cannot guarantee a specific chip to any user. We are actively building features that will give you flexibility in acquiring runtimes of your preference, though note that there will always be a tradeoff between cost and chip guarantees.

In cases where users have described issues with concurrent runtimes, note that for Pro+ users, we proactively issue a very long reservation when you start a GPU runtime to give you increased reliability, and this may make it difficult to initiate many concurrent sessions. We are designing ways to give you flexibility to choose between concurrency and length of session, but until then terminating sessions you're done with (using Manage Sessions) may unblock you.

I'm closing availability and concurrency related issues as there's not much by way of individual support we can offer on GitHub, and there don't appear to be any known issues with assignments.

**Comment by xincui-math** [comment]
@cperry-goog 

Nobody is providing their email account to get their benefits in GPU. Personally, I don't want to prioritize myself from other collab-pro + users by complaining here, since it is unfair.

There are two things quite confusing to me.
(1) More than 1 week of discontinues from GPU access is definitely ruining my user experience. 
(2) During the week, if you check all my other free tier colab, they have all have access to GPU.

Even though it is a sample estimation looks like 3 data points, however, I checked daily. There are indeed maybe 10-20++ data points. Law of large numbers told me that your access queue is probably p is not just a function of user ID, but also probably also based on monthly usage. 

To me, it is maybe better to use the rolling window criterion, since it will not totally destroy the user experience.

Thank you.

**Comment by rinabuoy** [comment]
@cperry-goog 

After almost two weeks without GPU, I was fortunate to connect to GPU for a few hours before hitting the usage limit again. If this sort of experience is expected for pro+ user,  I would not call it a 'priority'. By the way, thanks for your effort in resolving this issue and appreciate that. 

I guess I have been a bit tired of chasing for GPU for my pro+ subscription. The support (colab-billing@google.com) does not help much with respect to customer's concerns. 

By the way, enjoy the weekend, everyone !

**Comment by stas-sl** [comment]
Looks like their strategy is to make users unsubscribe because of bad service, and the issue will be solved. No users, no problems.

**Comment by Ghee36** [comment]
Why are they charging and taking customer funds for weeks that they aren't providing the service.  Colab Pro+ in any form outside of pay-per-day is scandalous due to their practices in withholding service without mind to withhold charging customers for denial of service or providing a freeze of credits. 

It is predatory to essentially temp-ban users arbitrarily/algorithmically while continuing to profit off of the period of revocation...

**Comment by chulochula** [comment]
> Given the amount of traffic here on GitHub, I've composed a longer answer and am responding to and consolidating a variety of related tickets.
> 
> Over the past weeks, Colab has observed a sharp increase in demand, making it difficult to satisfy all concurrent demand with premium chips. We continue to prioritize our paid subscribers (Pro+, Pro) for high-end GPU assignments, and by and large, looking at aggregate numbers, and deep diving into specific cases that have been highlighted in our support channels, we observe Colab's GPU availability is well worth the subscription.
> 
> We are actively addressing concerns by bringing more GPU runtimes online; this adds a mix of chips into the fleet. New capacity has resulted in improvements over the last few days. Note that due to offering on-demand resources at scale, we cannot guarantee a specific chip to any user. We are actively building features that will give you flexibility in acquiring runtimes of your preference, though note that there will always be a tradeoff between cost and chip guarantees.
> 
> In cases where users have described issues with concurrent runtimes, note that for Pro+ users, we proactively issue a very long reservation when you start a GPU runtime to give you increased reliability, and this may make it difficult to initiate many concurrent sessions. We are designing ways to give you flexibility to choose between concurrency and length of session, but until then terminating sessions you're done with (using Manage Sessions) may unblock you.
> 
> I'm closing availability and concurrency related issues as there's not much by way of individual support we can offer on GitHub, and there don't appear to be any known issues with assignments.

You are lying, as a colab pro+ users, you do always allocate specific GPU chip to me:- "No GPU"!!! The 5th day now, after I run my session several times within 24hrs, then no GPU. But I subscribed on 26th last month, just played around two days !!! Then no GPU. I finally used free Colab to finish my work.

**Comment by a11to1n3** [comment]
At least you have to return the money to us, otherwise you are nothing but a theft.

**Comment by aniruddhakal** [comment]
I'm facing the same issue. Despite being Pro+ user, can't access GPU since yesterday.
I only remember once out of 4 trials that the notebook was able to stay up for more than 12 hours.
I think Sagemaker Notebook would rather be much cheaper - very wide range of instance choices, cheaper spot prices and scalability as needed!

**Comment by transat** [comment]
Same issue here. I was getting GPU access on Colab Pro but have had no luck after upgrading to Pro +. I feel like I've been ripped off.

**Comment by chikalabouka** [comment]
I had the same issue, lost more than 200 compute units on a training that I redid 5 times. I am a subscribed to colabPro also and the session times out always after 24h. Will unsubscribe now and switch to another alternative.

**Comment by tarekseguir** [comment]
Imagine having a deadline for a project and not being able to access the GPU to train the models for a week. And even when you do get it, it only lasts for 2 hours. what a scam. The problem is that the free version gives you access to the GPU.

**Comment by Alifalisda** [comment]
hallo guys, my google collab is actually using GPU RAM 0.6 /40, do you have answer for the happening?
