### ISSUE TITLE
Colab Pro+ High Ram Mode Doesn't Work

### ISSUE THREAD

**Issue by I-Good-Vegetable** [googlecolab/colabtools#2258]
Browser: Chrome
Version: Colab Pro+
I bought colab pro+ and selected the high ram mode; whereas I only get 12G RAM. 
![image](https://user-images.githubusercontent.com/68672839/133911326-4644484e-2c8a-451f-b5f7-4c906e1b836b.png)
![image](https://user-images.githubusercontent.com/68672839/133911349-a0ba3da2-439e-4535-afc2-0fc133cda173.png)

**Comment by smourace** [comment]
same here

**Comment by chaiyan42** [comment]
I have same problem. I have upgraded to Colab Pro+, I tried to select both GPU+High Ram and TPU+High Ram but I still got only Ram 12 GB. My code is to run image processsing need RAM > 35 GB that why I paied for Colab Pro+. I am graduate student and plan to present my thesis next month. I am very disappointed with Colab Pro+.

**Comment by I-Good-Vegetable** [comment]
Please fix this issue ASAP. I really need it to present my work next week.

**Comment by RJN12** [comment]
same issue since last 4 days....not expected from google at least

**Comment by KimiHsieh** [comment]
Same issue, I just subscribed to the colab pro plus on Sep 18th,  I always get 13 g ram only even when I switch to high ram in GPU mode. It is very disappointed when you pay 50$/month and get such service which does not match the contract.

**Comment by zainuddin445** [comment]
please fix it ASAP

**Comment by I-Good-Vegetable** [comment]
For god sake, I cannot connect to GPU now. It's too unstable

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro and Pro+ subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback and mention this GitHub issue.

For paid subscribers, if you have billing questions you can contact colab-billing@google.com

**Comment by BLACKGSGO** [comment]
Why same words for this problem? More than five days whith only K80 on pro+ i have two accounts pro+ and is the same problem... My mom have a pro plan, and her have p100 or lower, but me, is only k80 why?
