### ISSUE TITLE
colab pro bug

### ISSUE THREAD

**Issue by dorinkutozi** [googlecolab/colabtools#2262]
I only connected the runtime for a few minutes, didn't do any coding, went straight to the backend

**Comment by cputester011** [comment]
This is happening with everyone. I'm done with colab pro.. I cant run T4 even for 1 hour. Thanks colab for ripping my money. No renewals.. Thank you

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro and Pro+ subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback and mention this GitHub issue.

For paid subscribers, if you have billing questions you can contact colab-billing@google.com
