### ISSUE TITLE
colab pro+ account cannot allocate high memory

### ISSUE THREAD

**Issue by hadisaadat** [googlecolab/colabtools#2263]
I have a colab pro+ account and It  does not allocate high memory, although I have chosen the high memory in the runtime type when I check the available memory in (GPU and TPU runtime types) it doesnt give me more than 13.6 gigabytes.

Since I usually get ~54gigabytes of memory as I expect, it sometimes fails (or let say many times) to deliver the promises of pro+ account. it gives me the standard ram.

I use Chrome Browser.

I have attached the screenshot.
 
![Screenshot from 2021-09-20 12-46-53](https://user-images.githubusercontent.com/11638577/133991775-9dd67909-d612-4d46-a76e-babfe6073233.png)
-

**Comment by I-Good-Vegetable** [comment]
Same here. Apparently, they cannot guarantee anything. I'm totally fine if they can increase the price, but I do need a stable env.

**Comment by I-Good-Vegetable** [comment]
Maybe they can have colab pro max plus : )

**Comment by hadisaadat** [comment]
@I-Good-Vegetable 
I agree I need an stable setup, but apparently the only stabilities on google side is charging your account they do not care about customer service and they don't feel responsible for the service the only thing they are extremely accurate on, is charging you

**Comment by zainuddin445** [comment]
why my pro+ can't have high memory

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro and Pro+ subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback and mention this GitHub issue.

For paid subscribers, if you have billing questions you can contact colab-billing@google.com
