### ISSUE TITLE
Sorry, No Backend Available, Please Try Again Later

### ISSUE THREAD

**Issue by dorinkutozi** [googlecolab/colabtools#2268]
![image](https://user-images.githubusercontent.com/25046644/134360267-f2de7e5d-5014-4e68-b539-5139d2345d0d.png)

I have not input data for rendering, 1 minute immediately reconnected, and I have subscribed to pro, it's still like a free plant

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro and Pro+ subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback and mention this GitHub issue.

For paid subscribers, if you have billing questions you can contact colab-billing@google.com
