### ISSUE TITLE
pro+'s gpu doesn't recover over many days

### ISSUE THREAD

**Issue by Pzeyang** [googlecolab/colabtools#2270]
why colab pro+'s gpu doesn't recover over 3 days??????????????????????????????????????

**Comment by Pzeyang** [comment]
I just use pro+ 2 days. why?????????????, What a disappointment!!!!!!!!!!

**Comment by olaviinha** [comment]
3 days? It's been weeks to me and many others. However, I'm also starting to suspect this is actually a bug and not intentional behaviour. It makes very little sense to me that a monthly paid service would be essentially unavailable for what you pay for, for the majority of that month.

**Comment by Pzeyang** [comment]
> 3 days? It's been weeks of "no GPU" to me and many others. However, I'm also starting to suspect this might actually be a bug and not intentional behaviour. This never occurred in the lesser Pro plan, and also it makes very little sense that a monthly paid service would be useless for the vast majority of that month, for what the majority of users are likely particularly paying for.
> 
> Somebody in Colab team should double-check that the limitations are working as intended.

No, it's not work yet.

**Comment by Pzeyang** [comment]
No, it's not working yet.

**Comment by Theivaprakasham** [comment]
I bought a Colab Pro+ account today and was shocked to note that I received a Tesla P4 GPU (4GB). The Max RAM I received was just 13GB. I tried restarting once again and was shocked to see the message _**"Sorry, no backends available. Please try again later"**_ . I haven't used Colab for the past two weeks and hence my resource quota should have been intact.

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro and Pro+ subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback and mention this GitHub issue.

For paid subscribers, if you have billing questions you can contact colab-billing@google.com

**Comment by olaviinha** [comment]
Are you not able to answer the question whether or not 9 days of total GPU restriction is an intended limitation or not? That would be helpful, just to know whether to report this same bug again or not.
