### ISSUE TITLE
Não foi possível atribuir um back-end Nenhum back-end com GPU disponível. Gostaria de usar um ambiente de execução sem acelerador?

### ISSUE THREAD

**Issue by ByFerxx** [googlecolab/colabtools#2283]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by ByFerxx** [comment]
Não foi possível atribuir um back-end
Nenhum back-end com GPU disponível. Gostaria de usar um ambiente de execução sem acelerador?
como resolvo isso, estou a muito tempo recebendo gpu t4 agora nada mais , e ainda estou no periodo de vigencia do plano

**Comment by eliasvasconcelos** [comment]
This problem repeat here in my colab

**Comment by jadsonlourenco** [comment]
# Google Colab is a SCAM! 

Simple like that.

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro and Pro+ subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback and mention this GitHub issue.

For paid subscribers, if you have billing questions you can contact colab-billing@google.com
