### ISSUE TITLE
Only 12GB RAM is allocated to Colab Pro+ (no high RAM)

### ISSUE THREAD

**Issue by ginward** [googlecolab/colabtools#2290]
**Describe the current behavior**
It is currently not possible for me to connect to high-RAM GPUs, although I am a Colab Pro+ user. 

```
from psutil import virtual_memory
ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))

if ram_gb < 20:
  print('Not using a high-RAM runtime')
else:
  print('You are using a high-RAM runtime!')
```

```
Your runtime has 13.6 gigabytes of available RAM

Not using a high-RAM runtime
```

<img width="374" alt="Screenshot 2021-09-26 at 16 18 51" src="https://user-images.githubusercontent.com/6193977/134799752-c73a3926-b3db-4944-9929-bc0b908688dd.png">

**Comment by jadsonlourenco** [comment]
# Google Colab is a SCAM! 

Simple like that.

**Comment by cperry-goog** [comment]
Thanks for reporting! In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro and Pro+ subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits

You could also try contacting colab-billing@google.com
