### ISSUE TITLE
no "background execution"

### ISSUE THREAD

**Issue by buyudtx** [googlecolab/colabtools#2292]
As a colab pro+ user,the session will not keep running at all  if the tab page is closed. After 40 minutes, I check the session and it was terminated.

**Comment by jadsonlourenco** [comment]
Yes, even without GPU.

**Comment by olaviinha** [comment]
I have observed this behaviour as well. 

For me the errors seemed to occur as timeouts when the notebook was connecting to APIs or downloading files – something that never occurs when I have the notebook open. My initial thought was that **perhaps** the background execution eventually goes into a mode as if it's entirely offline from the internet. Didn't report it because was unable to test more thoroughly what might be causing it then Pro+ subscription broke the whole Colab.

Might be way off here, but did your notebooks have anything similar (external connections somewhere), or should your notebooks work offline (as in the internet cable is disconnected from the machine running the notebook)?

**Comment by cperry-goog** [comment]
If there are consistent repro steps that break background execution, we'd love to see them.

We need account information to diagnose issues of this type, so for Pro+ support, try contacting colab-billing@google.com
