### ISSUE TITLE
ALL BLAMER IS MINER - PLEASE PROHIBIT MINING COIN IN COLAB

### ISSUE THREAD

**Issue by thien220996** [googlecolab/colabtools#2309]
I saw almost member blame Colab give them only K80 and limited time. They tell Colab is Scam. But most of them is Cryptocurrency Miner. I believe normal user will receive justice when Crypto mining banned. Keep patient and wait that day together. Thank you.
I had removed example picture, but you can see almost blamer had mining code script in their public repository. Anyway it is truth.

**Comment by jalukasjagykuntilisasi** [comment]
its use CPU not GPU

**Comment by thien220996** [comment]
Please play fair

**Comment by olaviinha** [comment]
Also block the spammers from this repository.

**Comment by jadsonlourenco** [comment]
Well, I think the Google Colab is a SCAM because:
I was a free user, then got one P4 GPU and the training ML get a bit better, so, someone said that V100 GPU was available in PRO+. 
Ok, subscribed to this plan. Got only K80, like the free version - background running without open tab is good - Then I decide to cancel the subscription to not renew next month, but want to use it until the subscription period finishes.
Guess what, after cancel the running instance stopped, one minute later, and I can't get any GPU, even K80, and it's not about "available" because on another account I get K80, on the free plan.

So, I still have more than 20 days to use the "PRO+" plan and it doesn't give me any benefit, if it is not a SCAM I'm crazy!
This service is not fair at all, Google should care that some countries have the "consumers protection law", like Brazil (PROCOM), a free service to denounce the SCAMS companies/services like that.

**Comment by soulspark666** [comment]
@thien220996 stop creating random feature requests here, google has already implemented techniques to block colab services that abuse it. If it is working now, it will be blocked later. Also, do you know if that script was used on a colab, since seems like you are just blaming him for crimes you cannot prove?

**Comment by soulspark666** [comment]
@jadsonlourenco this issue is there for a while and had been address here https://github.com/googlecolab/colabtools/issues/2232#issuecomment-922160127

**Comment by thien220996** [comment]
@jadsonlourenco Yes I agree with you. But if you use Colab early (2020) you will known free user can access P100 and unlimited session time with Pro. Now have too much people paid to mining coin in Colab. They will pay any amount to subscribe if mining have profit (ex: 50$ pro + mining 100$ in one month => OK). It is very unfair with normal user who paid to learn AI. So if user not stop mining and keep blaming i think Colab need to prohibit mining coin ASAP!

**Comment by olaviinha** [comment]
If you know a way to bypass Colab's mining detection, you should report it as a bug with details, probably.

**Comment by lopho** [comment]
I blame google TBH. Over promising, under delivering, vague ToS, nothing guaranteed, except a charge to your CC.

**Comment by arifaghafur** [comment]
I upgraded to pro+ and got K80, are u kidding me, this the features... 

Background execution
Notebooks keep working even after you close your browser.

Faster GPUs
Priority access to faster GPUs and TPUs means you spend less time waiting while your code is running.

Even more memory
Significantly more memory than ever before.

Even longer runtimes
Gives you the longest running notebooks in Colab so you are able to get your work done.

**Comment by cperry-goog** [comment]
Cryptocurrency mining is explicitly prohibited in Colab paid terms of service: https://colab.research.google.com/pro/terms

We have a variety of mechanisms to detect and prohibit mining, and we continue to invest in improvements here in order to deliver a reliable interactive compute environment for the rest of our compliant users. Thanks for calling this out.
