### ISSUE TITLE
colab pro plus wont connect to gpu backend because of colab limitation for two days

### ISSUE THREAD

**Issue by AseelAlshorafa** [googlecolab/colabtools#2320]
I started using colab pro plus three days ago, in the first day I just train a model using high ram GPU and it takes just about 4-5 hours, after that it wo'nt connect to my GPU it says Cannot connect to GPU backend You cannot currently connect to a GPU due to usage limits in Colab I didn't use it for more than 12 hours and the limitation have been for two days can I know where is the problem and how I can solve it thanks in advance for any help

**Comment by ModernTrips** [comment]
can not only confirm but also estimate from my logs that theres at least ~5/30 full days where im not reaching any gpu backend. none of the paid features are actually stable for longer then a week. I seriously hope this is due to some important upgrades or whatsoever, but the already taken answer "well its still good for the price" is simply a bummer, the other features like multiple notebooks, no browser runs and stable runs werent provided longer than 3 days in a row at any point this month. Personally, if i had been presented an honest featureset with a higher price - id really pay it! but if it keeps going like this this is honestly frustrating, especially since the service was an absolute bless in the beginning. that people need to open github issues because theres no useful customer support and / or answering of urgent complaints makes me wonder too.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
