### ISSUE TITLE
Google Cloud SDK authentication in Colab crashes TPU session when tensorflow tool was installed

### ISSUE THREAD

**Issue by raymond-dms** [googlecolab/colabtools#2412]
**Describe the current behavior**
auth.authenticate_user() crashed the TPU session with "your session crashed for an unknown reason", when "!pip install -q -U tensorflow-text" was run before it. Notebook ran under CoLab Pro+ with TPU.

**Describe the expected behavior**
without running  "!pip install -q -U tensorflow-text" first, "auth.authenticate_user()" + "gcloud init" run through without any issue. This flow has been ran for many months without any issue. Problem started roughly 1 day ago. 

**What web browser you are using**
Chrome

**Additional context**
[Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.](https://colab.research.google.com/drive/1gcZc-Zc0lUnmZiexyGCWja_K9wQ7R7pl?usp=sharing)

**Comment by craigcitro** [comment]
The problem here is that `tensorflow-text` is installing an old TF version, which causes confusion when trying to use the TPU. The version mismatch is because there's no 2.7 release of `tensorflow-text`: https://pypi.org/project/tensorflow-text/#history

Two options:
1. Install an rc: `!pip install --pre tensorflow-text`
2. Wait for a new `tensorflow-text` release.

**Comment by raymond-dms** [comment]
That must be it. Thank you so much, craigcitro . It does solve the crash issue. Greatly appreciate it.
