### ISSUE TITLE
Failed to assign a GPU backend

### ISSUE THREAD

**Issue by shivaniNK8** [googlecolab/colabtools#242]
I'm getting a no backend with GPU available error since a long time. How to fix this?

**Comment by AlexAseks** [comment]
You can try restarting the machine with the command ``` ! Kill -9 ``` (the machine takes a few minutes to be available again) then you need to reinstall all the dependencies, since everything becomes the same as before. Then you can make sure that it works with the following function:

```python
def mwInfo():
  ## Define Base Path as default and print current path
  import os, sys, tensorflow as tf
  print("Current Path: ", os.getcwd())
  print("Python Verson: ", sys.version)
  mode = "GPU"
  currentError = None
  try:
    gpuID = tf.test.gpu_device_name()
  except Exception as e:
    currentError = True
    print("GPU Error: ",e)
    gpuID = "GPU ERROR!!!"
  if gpuID == "" : mode = "CPU"
  print("Current GPU: ", gpuID)
  print("Current Mode: ", mode)
  return currentError
mwInfo()
```
If everything goes well, you should have something like this:
```
Current Path:  /content
Python Verson:  3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0]
Current GPU:  /device:GPU:0
Current Mode:  GPU
```
Very important: this solution does not always work, if it is the case, wait a few hours or try it again next day.


PD: Sorry my English is not very good, and I'm using a translator.
