### ISSUE TITLE
Colab Pro + Very High RAM option not available

### ISSUE THREAD

**Issue by thelastelectronbender** [googlecolab/colabtools#2473]
Hello, I was using Google Colab Pro and I needed higher RAM so I upgraded my account today to Google Colab Pro +. I need to have more than 15-20 GB RAM as it is promised but I can't have it. I can not see any "Very High or Higher RAM" type in Change Runtime Type menu. I paid money to have it, but right now I can't have it! 

I have limited time to execute training and get some results... Please help me.

user : mertceylaniu@gmail.com
Account type : Google Colab Pro +

**Comment by CharonWangg** [comment]
Same for me, always 12.69gb for high-ram runtime
user: charonwangg@gmail.com

**Comment by ChungNPH** [comment]
I have the same issue. Hope you check it for me.
user: hchung1997@gmail.com

**Comment by cperry-goog** [comment]
I can't comment on individual accounts publicly, but in every investigation I've covered, there are no known bugs in assignment logic; if runtimes are not available it's almost always a case of your quota being exhausted due to usage. We are working on ways to make this more transparent to you, as well as finding ways to help you keep getting your work done.
