### ISSUE TITLE
Colab pro+ has no high-ram

### ISSUE THREAD

**Issue by ChungNPH** [googlecolab/colabtools#2476]
I am using google Colab pro+ but can't use high-ram with gpu. I have also reflected via feed back. 
Please check it and hope to see your response soon.

**Comment by ChungNPH** [comment]
my account: hchung1997@gmail.com

**Comment by Amir-Mehrpanah** [comment]
The same issue here:
fakarimi101@gmail.com

**Comment by jupastro** [comment]
same issue on here juliopastor98@gmail.com

**Comment by cperry-goog** [comment]
I can't comment on individual accounts publicly, but in every investigation I've covered, there are no known bugs in assignment logic; if runtimes are not available it's almost always a case of your quota being exhausted due to usage. We are working on ways to make this more transparent to you, as well as finding ways to help you keep getting your work done.
