### ISSUE TITLE
Google Colab Error : Failed to get convolution algorithm.This is probably because cuDNN failed to initialize

### ISSUE THREAD

**Issue by nguaki** [googlecolab/colabtools#2496]
**Describe the current behavior**
Trying to install object_detection API in Collab.

**Describe the expected behavior**
Trying to install object_detection API in Collab.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome

**Additional context**
This problem seems to be recurring.  It existed since several years ago.
I would appreciate a clear explanation why this is happening.
Otherwise, I need to stop using Colab Pro and have rest of developers to stop using it since
it is causing total chaotic confusion and wasting too much of developer's time.

**Comment by craigcitro** [comment]
It's impossible to help without a minimal, self-contained public repro notebook describing the problem you're encountering.

**Comment by nguaki** [comment]
https://colab.research.google.com/drive/1QHuqtSM6wE-HZlTog3zYQ63kbg9UooUX

**Comment by craigcitro** [comment]
That notebook is private. (Sharing as a gist is often simpler for dealing with access control issues.)

**Comment by nguaki** [comment]
https://colab.research.google.com/gist/nguaki/fd4f8e3df24bdcf88779e3c776afda28/colab_gpu_tf_obj_detection.ipynb

Would you please get to the bottom of this?
We are deciding whether to continue with Google Collab or not.

Everything is  great except for this show stopping problem.

**Comment by craigcitro** [comment]
Thanks for the notebook -- I understand the issue now. The problem here is that you're installing a version of TF from PyPI, and the version you're getting is incompatible with the CUDA libraries we have installed in Colab runtimes.

You have a few options:
1. The lowest-friction would be to use the preinstalled version of TF; I'm not sure if that's workable with the other libraries you're looking to use.
2. You can build your own TF wheels, or find ones elsewhere online; it'll take some experimenting to find wheels compatible with Colab runtimes.
3. You can get full control over the CUDA versions and everything else in your image by using https://research.google.com/colaboratory/marketplace.html, which allows you to have full control over the VM.

This is "WAI (unfortunately)"; I'm going to close the issue, but happy to answer questions about the above if it's helpful.
