### ISSUE TITLE
Sorry, the backend is not available

### ISSUE THREAD

**Issue by hungwt** [googlecolab/colabtools#2556]
Sorry, the backend is not available

**Describe the current behavior**
I logged into colab and got the same problem

**Describe the expected behavior**
I have rerun it a few times but it doesn't work

**What web browser you are using**
is Version 97.0.4692.71 (Official Version) (64 bit)

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
