### ISSUE TITLE
Colab Pro - Only get less than 13GB ram when choosing High-RAM

### ISSUE THREAD

**Issue by machinelearninggo** [googlecolab/colabtools#2572]
I am using Colab Pro and it can steadily provide about 35GB RAM when I choose "High-RAM + TPU". 

However now when I choose it I can only get less than 13GB RAM. which is the same as standard mode. I am not opening multiple tasks. 

Could anyone help me with that? Thanks a lot!

![1642861659(1)](https://user-images.githubusercontent.com/75209437/150642550-880ff9dd-47de-4366-95ed-fc2ce54c3be0.png)

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
