### ISSUE TITLE
My colab pro+ can access only p100 gpu

### ISSUE THREAD

**Issue by jjonhwa** [googlecolab/colabtools#2574]
**Describe the current behavior**
My colob pro+ can access only p100 GPU. 
Three days have passed since the subscription, but only P100 GPUs will continue to be allocated.
My account is dirngka1@pusan.ac.kr

**Describe the expected behavior**
My subscription can work normally.

**What web browser you are using**
Chrome

**Additional context**
Is there anything I should do?
If not, I would appreciate it if you could solve it.

**Comment by Randy1435** [comment]
Hey, this is not a fix but I wouldn't recommend colab pro+, it's a waste of your money. Even 4 accounts with colab pro is way more worth it than one with colab pro+

**Comment by jjonhwa** [comment]
But I am constantly being assigned only P100 gpu in colab pro+.

**Comment by masc-it** [comment]
> But I am constantly being assigned only P100 gpu in colab pro+.

That's why is a waste of money.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback

**Comment by ID56** [comment]
@jjonhwa I am facing a similar phenomenon, though it hasn't been ten days yet. Were you able to ever get other GPUs later?

**Comment by jjonhwa** [comment]
@ID56 No. I was allocated P100 and T4 GPUs continuously and eventually I used Colab Pro after getting a refund.

**Comment by panchocodes** [comment]
Same issue :(
