### ISSUE TITLE
No non-GPU Colab access for three weeks straight

### ISSUE THREAD

**Issue by RyanCaesarRamos** [googlecolab/colabtools#2576]
**Describe the current behavior**
Without even requesting a GPU, I have not been able to access Colab for at least three weeks straight. Again, I'm not even requesting GPU runtimes (just standard CPU runtimes), and the last time I used a GPU runtime was December 2020.

**Describe the expected behavior**
To be given at least standard CPU runtime access, and if GPU overusage was an issue, for it to pass within two days as was the case with my past two years using Colab.

**What web browser you are using**
Chrome, Edge

**Additional context**
https://gist.github.com/RyanCaesarRamos/0a54dea4e2b3677603224726fe55c4c3

**Comment by Raghvender1205** [comment]
I am facing the Exact Same Issue. I am not able to connect to CPU, GPU, TPU runtimes with my Google Account for around 3 weeks now.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
