### ISSUE TITLE
mount failed: timeout during initial read of root folder due 10000+ images in the root folder

### ISSUE THREAD

**Issue by Sriharsha-hatwar** [googlecolab/colabtools#2587]
Accidentally, I had unzipped the images in root folder of the drive while doing some research. Now it is timing out whenever I try to mount the drive on colab. 

What are the tools that can be used to remove 10k+ files of the same extension from google drive? 
1. Not able to do cntrl+A as it only selects 50 files at once. 
2. Can not use colab itself to delete the files as it is not mounting. 
3.  My trash folder is empty so emptying the trash is not at all an option.

Additional context : 

Searched on Stackoverflow : https://stackoverflow.com/search?q=%5Bgoogle-colaboratory%5D+mount+failed%3A+timeout+during+initial+read+of+root+folder&s=6d870a2e-5d68-4b58-80e0-41316940b30b 

There were no solutions to resolve this. It would really help if someone can assist me on this to delete all the files from the drive and there are no options for that as well.

**Comment by LuigiSigillo** [comment]
If you add a try catch whenever you are loading the files for your dataset, it fails once but the second time uses some cache to speed up the reading, maybe you can solve in this way. I loaded 30k files with this trick

**Comment by cperry-goog** [comment]
This is a known issue: https://research.google.com/colaboratory/faq.html#drive-timeout

You'll want to reduce the amount of content in your folder.

**Comment by Sriharsha-hatwar** [comment]
It might be the same problem, but the issue is still not yet resolved. I do think the fix from the google-colab team is straight enough for this?

**Comment by Sriharsha-hatwar** [comment]
> If you add a try catch whenever you are loading the files for your dataset, it fails once but the second time uses some cache to speed up the reading, maybe you can solve in this way. I loaded 30k files with this trick

Hello @LuigiSigillo , can you please elaborate and provide a sample snippet?

**Comment by LuigiSigillo** [comment]
@Sriharsha-hatwar get_loader is the function that for me tries to load the datasets, you have to add your function that tries to load the data from drive.
 
```
try:
    loaders = get_loaders()
except FileNotFoundError:
    print("ERROR: Google drive not load properly large data, so we have to retry.")
    loaders = get_loaders()
```

**Comment by ankit-blip** [comment]
> change the default timeout can fix this issue. It takes about 5mins to load my 50K+ files in root path. Specifically, you should change the timeout param in mount method.
seems logical could you please elaborate more as to how to do this

**Comment by deanp70** [comment]
Posting with permission from @cperry-goog - we're collaborating with the Colab team to provide DagsHub Storage as an alternative to GDrive that is more scalable and built for use with large datasets. It's an S3-compatible bucket that has much simpler access controls, and can be mounted easily.

It might help avoid the issues above - [here's a link to an example notebook to try it out](https://colab.research.google.com/#fileId=https%3a%2f%2fdagshub.com%2fDagsHub%2fDagsHubxColab%2fraw%2f7a674bc098ac6a25e78ac89adb3527aee45fe278%2fDagsHub_x_Colab-DagsHub_Storage.ipynb)

We're looking for community feedback, so I'd love to get your input if it helps with the issue at hand.

(If you're curious, [DagsHub](https://dagshub.com) is a platform for ML teams which is why we think Colab should have a storage solution suitable for ML workloads)
