### ISSUE TITLE
Wrong CuDNN version on GPU environments.

### ISSUE THREAD

**Issue by lucajung** [googlecolab/colabtools#2600]
**Describe the current behavior**
To use the Tensorflow object detection API, CuDNN version 8.1 is required but only version 8.0.5 is loaded.
It might be helpful to provide a switch to easily change the version of it.

**Describe the expected behavior**
Version 8.1 is provided.

**Comment by jared-taylor** [comment]
This issue just started for me as well, commenting to follow

**Comment by mingweichua** [comment]
I'm having this issue as well

**Comment by mingweichua** [comment]
1. try 'factory reset runtime' in your colab runtime 
2. reinstall TensorFlow by issuing the command '!pip install tensorflow==2.8'
3. if you are doing object detection, please make sure your object-detection package is successfully built.
    --- cd to your research folder.. and rerun the command '!pip -m pip install .' make sure you these after you have issued the command stating that you installed the object-detection package successfully.
    
    Building wheels for collected packages: object-detection
  Building wheel for object-detection (setup.py) ... done
  Created wheel for object-detection: filename=object_detection-0.1-py3-none-any.whl size=1686356 sha256=4239c8ef9dd88fdf99bf1e52ffbd4be6ea3eed97638b489009e968e894101e70
  Stored in directory: /tmp/pip-ephem-wheel-cache-fc47s5u0/wheels/fa/a4/d2/e9a5057e414fd46c8e543d2706cd836d64e1fcd9eccceb2329
Successfully built object-detection
Installing collected packages: object-detection
  Attempting uninstall: object-detection
    Found existing installation: object-detection 0.1
    Uninstalling object-detection-0.1:
      Successfully uninstalled object-detection-0.1
Successfully installed object-detection-0.1

4. when you completed all above if you still encountered another error when u start training, especially on the 'cv2' 
kindly reinstall by issuing these commands.
!pip uninstall opencv-python-headless
!pip install opencv-python-headless==4.1.2.30

5. if memory exceeded, reduce your batch size, preferable to be in the power of 2.. 2^(n)..

hope it helps...

**Comment by hosungs** [comment]
This may not work always and may not be safe, but as a workaround for the time being, you may try running `!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2` and let us know if that fixes your issues. We (Google Colab team) may also upgrade the included CUDA/cuDNN package versions soon (internal tracking bug is b/223285386).

**Comment by hosungs** [comment]
@lucajung We are trying to figure out the best option to solve this issue (because we are limited w.r.t. upgrading CUDA/cuDNN versions in our runtime), which requires us to clarify exactly how the issue happens, so we are wondering if you could share a minimal repro notebook? Is it that you downgraded TF to 2.7 and encountered the issue, or if the cuDNN version issue happens with the default TF 2.8 installed?

FYI, all I could try to repro this was to run the tutorial at https://www.tensorflow.org/hub/tutorials/object_detection on our current GPU runtime (that's installed with TF 2.8 and cuDNN 8.0.5) and it just works fine for me. I'm not an ML practitioner myself, so I don't know how to find a repro example, and it'd be greatly appreciated if you provide one for us. Sorry if this is too late.

**Comment by lucajung** [comment]
@hosungs Thank you for your advice. I just tried my notebook again and now I don't get an error.

**Comment by ambitiousrahul** [comment]
> This may not work always and may not be safe, but as a workaround for the time being, you may try running `!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2` and let us know if that fixes your issues. We (Google Colab team) may also upgrade the included CUDA/cuDNN package versions soon (internal tracking bug is b/223285386).

not working at my end
