### ISSUE TITLE
pip dependency conflicts

### ISSUE THREAD

**Issue by nguaki** [googlecolab/colabtools#2604]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
This happen all of suddenly.
I do not understand the cause of this.

I execute these lines of codes:
if os.name=='posix':  
    print('getting protobuf-compiler')
    !apt-get install protobuf-compiler
    !cd Tensorflow/models/research && protoc object_detection/protos/*.proto --python_out=. && cp object_detection/packages/tf2/setup.py . && python -m pip install . 

Now, I am getting following error message:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.3.post1 requires numpy<1.20,>=1.16.0, but you have numpy 1.20.3 which is incompatible.
multiprocess 0.70.12.2 requires dill>=0.3.4, but you have dill 0.3.1.1 which is incompatible.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

Previously, I didn't see these error messages.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by NKdeE** [comment]
having a similar problem here using https://www.tensorflow.org/hub/tutorials/wiki40b_lm
copy on drive here: https://colab.research.google.com/drive/1EuN96da914UQG1y0-Xf6573LbBpfGw0F?usp=sharing

**Comment by NKdeE** [comment]
thank you. no, there were error messages as well on the colab, but the dependency problems have been fixed there in the meantime, so  i'm in the clear for now. see https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/wiki40b_lm.ipynb#scrollTo=pUypKuc3Mlpa
i'm new to this, but i'm using this for a literary project, needing this to be a stable module in a larger context, so i needn't go into the code too much, i've lost.. er, the habit. i suppose i'll have to figure out how to get it running on my own past end-of-life hardware, because i noticed my drive-copy got the same dependency issue (an update of the tensorflow package)? or are updates of packages like that rare in Py? i used to work in java, over 10 years ago, so i'm rather new to how things are being done here and now qua dependency and backward compatibility..
so some advice would be highly appreciated, thank you.

**Comment by craigcitro** [comment]
Awesome -- I'm going to close this, but will reopen if there are still issues.

Re: package versions: for Colab, we do regular package updates; if you want specific versions, our advice is to start your notebook with `!pip install`s that pin to specific versions.
