### ISSUE TITLE
Colab Pro runtime keeps disconnecting after running for less than 30 minutes.

### ISSUE THREAD

**Issue by abdelatifsd** [googlecolab/colabtools#2613]
I am working with Colab Pro. 

I keep getting this while actively working on the notebook:
Runtime disconnected
Your runtime has been disconnected due to inactivity or reaching its maximum duration.
As a Colab Pro subscriber you have access to longer runtime durations than non-subscribers do, but durations are still not guaranteed or unlimited.

In addition to that, the notebook keeps requesting to "prove I am not a robot" while actively using it. 

This is really frustrating as I remember having a better experience when I wasn't subscribed. It also is discouraging me from upgrading my subscription to Pro+.

**Comment by craigcitro** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. 

If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at `Help` > `Send feedback` and reference this github issue.
