### ISSUE TITLE
Unzipped files not visible on Google Colab

### ISSUE THREAD

**Issue by prantostic** [googlecolab/colabtools#263]
I am trying to unzip a zip file, however, the files are not visible even after successful extraction.
I am attaching a screenshot to look at.
![screenshot from 2018-09-10 01-07-57](https://user-images.githubusercontent.com/10927376/45268288-61e10b80-b497-11e8-8dcb-136d5d4696a5.png)

**Comment by fischman** [comment]
You're passing -v to unzip which tells it to only show you the contents of the zip archive, not actually extract anything, so it's not surprising nothing is extracted.
You're also passing -f which further tells unzip to only extract files that are already present on disk but for which there is a newer variant inside the zip file. So that's another reason it's not extracting anything.
Drop the -vf from the unzip line and you should be good to go.
