### ISSUE TITLE
Failed to execute cell. Could not send execute message to runtime: Error: await connected: disconnected

### ISSUE THREAD

**Issue by 1Neo1974** [googlecolab/colabtools#2631]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment]
Can you share a minimal public notebook if this reproduces consistently for you?

In general, factory reset should refresh the VM and resolve.

**Comment by JaimeOlivaresNV** [comment]
Hello, I am not the original poster, but have encountered a similar situation. If it's okay, I can share my own report here.

**Describe the current behavior**
Running multiple/all cells to execute in sequence results in "Runtime: Error: await connected: disconnected". Cell is silently stuck (no error message, but has the red play icon) and is stuck in an executing loop. The runtime icon at the top-right also changes to "Connecting" message.

This has consistently and only recently happened on my notebooks when using gspread to read Google sheets as dataframes.

Only way to resolve this on my end is to interrupt the runtime and run cells one-by-one.

**Describe the expected behavior**
Running multiple cells should allow each cell to execute and resolve in sequence. Allow gspread execution to complete as normal even when selecting Run All.

**What web browser you are using**
Google Chrome Version 99.0.4844.51 (Official Build) (64-bit)
Using a company account (email + endpoint verification)

**Additional context**
Unfortunately I cannot share any minimal notebook that has the same specifications as my work. I can share runtime logs if it helps, but I do not know what error message to look out for.

**Comment by cperry-goog** [comment]
Thanks; we'll need a minimal repro notebook to investigate further!
