### ISSUE TITLE
Colab pro+ graphics card model assignment

### ISSUE THREAD

**Issue by lvxingchang** [googlecolab/colabtools#2636]
As a Colab pro+ subscriber, during the month of the subscription period, the graphics card model assigned has always been P100, and V100 and A100 have never been assigned once during the subscription period, while other Colab pro+ subscribers can be assigned V100 every time, and sometimes even A100, so please ask why the same Colab pro+ subscribers are treated differently.

**Comment by MWNautilus** [comment]
Same here.
I purchased Colab PRO+ for two months after using Colab PRO previously: I never got a GPU assigned that was capable of offering more than 16 GB of RAM.

With this untimely amateur equipment (it is 2022), no serious scientific computation is possible e.g. when using bioinformatic ressources such as AlphaFold2 (see: https://github.com/sokrypton/ColabFold ) - especially when trying to work on multimer complexes (even of smaller proteins).

VERY disappointing.

**Comment by blois** [comment]
@lvxingchang - We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback

@MWNautilus - A high RAM assignment refers to *system* memory (as returned by `!grep MemTotal /proc/meminfo`), not *GPU* memory (as returned by `!nvidia-smi --query-gpu=memory.total --format=csv`). All GPU chips have the same memory profile.
