### ISSUE TITLE
Colab pro subscription.

### ISSUE THREAD

**Issue by StrOrx12** [googlecolab/colabtools#2686]
I bought colab pro subscription yesterday .I am now  displaying "Failed to attach backend." .I was training model on colab but it's only runned 4 hours. And than i am seeing this error. Help me please. Colab and so annoying. Sorry for my trash English.

**Comment by belarbi2733** [comment]
i have the same problem we pay then we can't use it

**Comment by belarbi2733** [comment]
@google-colaboratory

**Comment by StrOrx12** [comment]
> That's occurrence same to me also. Please contact by email [Colab-Billing@google.com](mailto:Colab-Billing@google.com) for quick response. @belarbi2733 @StrOrx12

I wrote this email earlier. They answered "Pro subscription doesn't come with customer service.". So i wrote here maybe someone helps me out

**Comment by StrOrx12** [comment]
Also free tier better than subscriptions. I am paying and not able to use that. So annoying

**Comment by Anantasak** [comment]
> > That's occurrence same to me also. Please contact by email [Colab-Billing@google.com](mailto:Colab-Billing@google.com) for quick response. @belarbi2733 @StrOrx12
> 
> I wrote to this email earlier. They answered "Pro subscription doesn't come with customer service.". So i wrote here maybe someone helps me out

Same to Pro+ they recommend us to using GCE marketplace. We are on going to alternative for comparison price.s

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
