### ISSUE TITLE
No backend with GPU available. Would you like to use a runtime with no accelerator?

### ISSUE THREAD

**Issue by prem5178** [googlecolab/colabtools#2733]
Not able to run any project. I have pro+ account

**Comment by saadz-khan** [comment]
I have been experiencing the same issue currently. It works on different accounts that I did not use. I have a Pro+ account and another Pro account that does not work with GPU backend. It does not feel like a timeout from using GPUs. All configuration are not connecting to any instance.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
