### ISSUE TITLE
Colab not connecting to backend

### ISSUE THREAD

**Issue by LUIS9799** [googlecolab/colabtools#2747]
Colaboratory is not connecting to backends, It gives a warning saying "No GPU backend available. Do you want to use a non-accelerator runtime?", when I hit connect it says "No backend available. Please try again later" and I've tried for more After 2 days, I'm not using colaboratory to mine cryptos.. I'm just using it to test some scripts in another execution environment than windows.

Connect to backends

Brave

**Comment by craigcitro** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at `Help` > `Send feedback`
