### ISSUE TITLE
Sorry, no backends available. Please try again later.

### ISSUE THREAD

**Issue by TheCaduceus** [googlecolab/colabtools#2753]
When I am trying to run any Google Colab notebook then it is just saying that "Sorry, no backends available. Please try again later." I am waiting from past 5 Days but it is still the same.
![image](https://user-images.githubusercontent.com/87380104/162991549-42de4be6-b2fd-4a20-b9f9-6e85957c0e86.png)

**Comment by craigcitro** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at `Help` > `Send feedback`
