### ISSUE TITLE
Start Google Colab Error : [Error 401: invalid_client]

### ISSUE THREAD

**Issue by TangTieuLinh** [googlecolab/colabtools#2767]
When I setup Google Colab with code:

!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

And terminal shows:

E: Package 'python-software-properties' has no installation candidate
Selecting previously unselected package google-drive-ocamlfuse.
(Reading database ... 155455 files and directories currently installed.)
Preparing to unpack .../google-drive-ocamlfuse_0.7.27-0ubuntu1~ubuntu18.04.1_amd64.deb ...
Unpacking google-drive-ocamlfuse (0.7.27-0ubuntu1~ubuntu18.04.1) ...
Setting up google-drive-ocamlfuse (0.7.27-0ubuntu1~ubuntu18.04.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?...... 

I clicked the URL and received an error:
Authorization Error
Error 401: invalid_client
The OAuth client was not found. 

Then I log out and re-login again but the 401 error still occurs. I also try it with another account on another browser but was not successful. Please, help me.

**Comment by craigcitro** [comment]
The problem here is that we've changed the way we handle credentials ([motivation](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#disallowed-oo)); the result is that you can't extract the `client_id` and `client_secret` from the credentials.

You could try using a [different auth approach](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-&-Authorization) or asking upstream about support for GCE metadata service credentials in google-drive-ocamlfuse.
