### ISSUE TITLE
Fastest way to copy files from google drive to local dir

### ISSUE THREAD

**Issue by flipflopbboi** [googlecolab/colabtools#280]
I find that copying files from google drive to a local machine directroy can be very slow.
MY calculation suggests copying speed of about 50kB/sec, whereas when downloading stuff through `wget` speed is well over 1MB/sec
any ideas around this? thank you

**Comment by fischman** [comment]
Mounting your Google Drive as shown in https://colab.research.google.com/notebooks/io.ipynb#scrollTo=u22w3BFiOveA should get you much faster copies.
(also, since your Google Drive will be mounted as a file-system in the VM where your code runs, you might be able to avoid the copy entirely, simply pointing your code at that mounted directory/file location)

**Comment by fischman** [comment]
50kB/sec is orders of magnitude slower than my testing sees (assuming you're using the same drive.mount() helper I referred to above). 
A typical reason for such a slowdown is using many many small files/directories instead of a few large files.
If you archive (zip/tar/etc) the data and store it in a small number of files in Google Drive, and then copy only those over, does that solve your problem?

**Comment by flipflopbboi** [comment]
good idea, indeed i am copying over thousands of small images ~20kB each ; will try that and update results here, thanks!

**Comment by fischman** [comment]
Sounds good. Feel free to reopen/open a new bug if you see issues.
