### ISSUE TITLE
I also get an error using a Colab service that doesn't include a GPU or TPU as a Colab Pro member.

### ISSUE THREAD

**Issue by 110wuqu** [googlecolab/colabtools#2809]
error message:
Sorry, there is no back end available, please try again later. details

**Comment by sebbov** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback.
