### ISSUE TITLE
Getting a P100 even on Pro+

### ISSUE THREAD

**Issue by Mustang272** [googlecolab/colabtools#2812]
I bought colab pro+ last month and haven't even used GPUs all that much. But today I noticed that despite paying $50/month I still get a P100, which just a year ago was available even with regular colab occasionally. This is false advertising. Other issues have also mentioned that Pro+ has the strictest banning policies and even caps the VMs at 12GB RAM. What am I missing here? Am I paying more to receive less?

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
