### ISSUE TITLE
Update MathJax to version 3

### ISSUE THREAD

**Issue by mhucka** [googlecolab/colabtools#2822]
- [ ] **Is your feature request related to a problem? Please describe.**

Google Collab is a terrific system, and it's wonderful that it supports LaTeX syntax for mathematical expressions using MathJax. However, the current version of MathJax implemented in Google Collab appears to be version 2.  Version 3 of MathJax provides some capabilities are currently impossible to get in Collab, such as the braket macros (e.g., `\ket{x}`) which are used in the context of quantum computing such as Google's own [quantumlib](https://github.com/quantumlib).

**Describe the solution you'd like**

It would be helpful for users if Google Collab updated whatever code is uses to load MathJax, so that it loads version 3 instead of version 2. 

If there is a backwards compatibility issue, perhaps the _Settings_ dialog in Google Collab could have a checkbox letting the user select the version of MathJax they get. 

**Describe alternatives you've considered**

[A comment by @blois](https://github.com/googlecolab/colabtools/issues/2286#issuecomment-1021462155) on issue #2286 ("It should be possible to enable MathJax running in the output of a specific cell by emitting HTML with the MathJax script tags & configuration") made me look for a way to do that. I _thought_ I found the answer in [another comment by @blois](https://github.com/googlecolab/colabtools/issues/975#issuecomment-583678411) on issue #975, namely, to attach some code to `post_run_cell`.  So I tried the following:

```
from IPython.display import Math, HTML

def load_mathjax_in_cell_output():
  display(HTML("<script src='https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg-full.js'></script>"))
get_ipython().events.register('post_run_cell', load_mathjax_in_cell_output)
```

If I open a new Google Collab notebook, paste the above into a cell, run the cell, then create a text cell below it, and type `$\ket{x}$` into it, the result is not rendered. It is evident that the construct is not recognized as a valid MathJax construct, even though [it's part of MathJax 3](https://docs.mathjax.org/en/latest/input/tex/extensions/braket.html?highlight=braket).

**Additional context**

I put an example notebook online at  <https://colab.research.google.com/drive/1E9eGVikLqKgqi6r-mij3DRNMqMcV_OXc?usp=sharing>

The following is a screenshot of this notebook demonstrating the results described above:

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/1450019/169715822-07e73d6b-f961-4303-8fdd-4e07a0dada63.png">

Other people have asked about MathJax 3 support:
* In January, a [user made a comment on issue #2286](https://github.com/googlecolab/colabtools/issues/2286#issuecomment-1021104971) requesting MathJax version 3 support
* A question in StackOverflow in July 2021 basically asked how to do the same: <https://stackoverflow.com/q/68572293/743730>

**Comment by blois** [comment]
The `get_ipython().events.register()` trick is for markdown in outputframes, which are currently (confusingly?) using KaTeX for performance reasons.

So this does render as you expect:
```python
from IPython.display import Markdown
Markdown('$\ket{x}$')
```

Upgrading MathJax for markdown cells involves a larger migration which we've been looking at as part of https://github.com/jupyterlab/jupyterlab/issues/272.

**Comment by mhucka** [comment]
Has this been closed because the version of MathJax has been updated?

**Comment by blois** [comment]
MathJax has not been updated for text cells- the recommendation if you need a specific version is to emit markdown in outputs.

There is no concrete upgrade plan for MathJax in text cells- can re-open the bug is that's specifically what you're looking for.

**Comment by westurner** [comment]
From https://github.com/quantumlib/Cirq/issues/5981 :

> And also Dirac braket notation w/ MathJax and Jupyter would be real nice:
> 
> * https://docs.mathjax.org/en/latest/input/tex/extensions/braket.html
> * https://docs.mathjax.org/en/latest/input/tex/extensions/physics.html
> * https://stackoverflow.com/questions/21122210/how-do-i-get-mathjax-to-enable-the-mhchem-extension-in-ipython-notebook
>   * `$$\requre{braket}$$` in the first line of a markdown cell in colab doesn't seem to be working, but I haven't spent much time on it
>   * `$\require{enclose} \enclose{circle}{x}$` works in colab
>   * `$\require{braket} \braket{1|0}$` does not seem to work in colab
>   * `$\require{physics} \braket{1|0}$` does not seem to work in colab
> * https://github.com/jupyterlab/jupyter-renderers (MathJax 3,)
> * https://github.com/ipython/ipython/blob/main/IPython/core/display.py
> * https://github.com/ipython/ipython/blob/main/IPython/core/display_functions.py#L207-L240
> * https://gist.github.com/sametz/6db971a36d7bc3acdd169ade80c5a7ee

**Comment by uber-lumiere** [comment]
@blois when you wrote  ... recommendation if you need a specific version is to emit markdown in outputs.
Does output mean the results of a code cell ... 
or have anything to do with Widget Outputs with a capital [0]

**Comment by vincentvigon** [comment]
Could this be reopened?

From @blois's own comment, posted the day after it was closed:

> MathJax has not been updated for text cells- the recommendation if you need a specific
> version is to emit markdown in outputs.
>
> There is no concrete upgrade plan for MathJax in text cells- can re-open the bug is
> that's specifically what you're looking for.

Text cells are specifically what several of us are looking for, so: yes please.

The reason this matters beyond the original braket-macro request is #3192 — open since
October 2022, labelled `bug` and `triaged`, tracked internally as b/163141894, and still
unfixed nearly four years later.

On macOS with Chrome, the default HTML-CSS output processor prefers locally installed
fonts, picks up the partial system STIX family, and breaks `\mathcal`, `\mathbb`, square
roots, accents (`\hat`, `\tilde`, `\bar`), extensible delimiters, `\overbrace` /
`\underbrace` and spacing — all from that single cause. Every workaround proposed in that
thread converges on the same action: switch the output processor to CommonHTML by hand.
And since the menu setting does not persist across page loads, that has to be redone every
time a notebook is opened or even reloaded.

MathJax 3 outputs CHTML by default. Upgrading the text-cell renderer would therefore make
the manual workaround unnecessary and close that entire class of bugs, instead of fixing
one macro at a time. It would also bring text cells in line with output frames, which
already use a modern renderer.

This affects teaching material in particular, where the notation is not exotic — normal
distributions, square roots, hats on estimators — and where the audience cannot be asked to
configure a renderer by hand.
