### ISSUE TITLE
Runtime colab

### ISSUE THREAD

**Issue by REXX-dev** [googlecolab/colabtools#2838]
Why i cant use this colab for long runtime? Im just currently using for 3mnts then disconnect getting no backends

Im using it for rendering video 3d

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
