### ISSUE TITLE
Cant connect to gpu

### ISSUE THREAD

**Issue by romakhokhlov** [googlecolab/colabtools#2882]
Hey im using collab pro and it says i can connect to gpu cause of limits. Whats wrong i pay for subscribtion and want a full available of gpu

**Comment by colaboratory-team** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
