### ISSUE TITLE
Unable to connect to GPU

### ISSUE THREAD

**Issue by chirucodes** [googlecolab/colabtools#2897]
I am unable to connect to GPU.

**It is showing an error as below:**

_**Cannot connect to GPU backend**
You cannot currently connect to a GPU due to usage limits in Colab. [Learn more](https://research.google.com/colaboratory/faq.html#usage-limits)
As a Colab Pro subscriber, you have access to fast GPUs and higher usage limits than non-subscribers, but if you are interested in priority access to GPUs and even higher usage limits, you may want to check out [Colab Pro+](https://colab.research.google.com/signup/pricing?utm_source=dialog&utm_medium=link&utm_campaign=gpu_assignment_failure_very_pro)._

**The out put of !nvidia-smi is as below**

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

**Comment by colaboratory-team** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
