### ISSUE TITLE
I upgraded to Pro+ But it is said My GPU RAM is still 16GB

### ISSUE THREAD

**Issue by kouketu03** [googlecolab/colabtools#2898]
Ive been trying  to use VQGAN+Clip.
And I have a memory error.
I upgrade to Pro+ But it is said I just have 16GB memory.
How can I fix it ?

The Colab I'm Using:
https://colab.research.google.com/drive/1Lu4VaUkIJZkpTEbg2pe95q9PDoQ5ltk9#scrollTo=4CR49Fu3j4o

<img width="414" alt="スクリーンショット 2022-07-03 11 43 19" src="https://user-images.githubusercontent.com/43922276/177022427-ac15aac5-3bef-4f1c-9990-8f6e90986cc3.png">

<img width="1052" alt="スクリーンショット 2022-07-03 11 27 31" src="https://user-images.githubusercontent.com/43922276/177022357-545957d7-1772-427f-b48a-6c412ae33bae.png">
B

**Comment by colaboratory-team** [comment]
We are not able to address resource assignment issues from GitHub. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Before sending, please note a high RAM assignment refers to *system* memory (as returned by `!grep MemTotal /proc/meminfo`), not *GPU* memory (as returned by `!nvidia-smi --query-gpu=memory.total --format=csv`). All GPU chips have the same memory profile.

Please submit feedback in product within Colab at Help > Send feedback
