### ISSUE TITLE
Colab Pro+ only allocate p100?

### ISSUE THREAD

**Issue by BaoLocPham** [googlecolab/colabtools#2952]
It's been two day since I paid for my colab pro+. I need GPU's power for my personal project, it's got deadline tho. 
Last month, I haven't experienced this such annoying. 
Is colab banned me because of overuse or what? If so why you don't tell me anything?
Paid $50 a month and got only p100 is such a waste of money.

**Comment by fbarretto** [comment]
Same here. I've had a V100 at my first notebook, then only P100s and T4s.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback and reference this issue
