### ISSUE TITLE
Colab PRO Plus does not work as expected

### ISSUE THREAD

**Issue by mrm8488** [googlecolab/colabtools#2987]
I have a colab PRO Plus account for 2 weeks and I only get P100 GPUs. I have another account (PRO PLUS too) in the company where I work and I get V100 and A100 (sometimes).

What is  happening?

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
