### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by mdaa-amine** [googlecolab/colabtools#2993]
**Description**
in order to get ride of the cybersecurity I used Colab to help me estimate some data about hashes and how fast can a hacker crack my account on social media or if someone tries to break my website admin page, using hashes, therefore, I tried cracking hashes in Colab and see Haw that is possible, so I can protect my self.   

**Describe the expected behavior**
as I know from the first lines of the faqs page >> https://research.google.com/colaboratory/faq.html. that Colab is free of charge
But when I run the Colab notebook with Hashcat setup the runtime got stopped and I couldn't run any other Colab notebook. with my account. a popup with the message **Sorry, no backends available. Please try again later.** appear every time
**What web browser you are using**
(Chrome)
what can I do to get Colab run again even with None accelerator(GPU/TPU)?

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
