### ISSUE TITLE
Sorry, no backends available

### ISSUE THREAD

**Issue by hmghaly** [googlecolab/colabtools#3002]
For a few days, whenever I try to connect google colab to my google drive, I get this error:
Sorry, no backends available. Please try again later.
[More info](https://research.google.com/colaboratory/faq.html)

I thought it is a temporary issue but now it's almost a week, what is the problem and what should I do?

The cell I'm trying to run is:
from google.colab import drive
drive.mount('/content/drive')

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
