### ISSUE TITLE
Colab pro account getting disconnected every few minutes

### ISSUE THREAD

**Issue by Aaquila** [googlecolab/colabtools#3006]
My collab pro account gets disconnected when I'm running some lines (doesn't matter what) or code or even when it is unused for a few minutes. This was not the case before.

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
