### ISSUE TITLE
Google's Transfer learning tutorial does not work with GPU enabled

### ISSUE THREAD

**Issue by ejboettcher** [googlecolab/colabtools#3016]
The tutorial does not run by itself without you injecting code if you are using the GPU as default.
You either have to switch to Non GPU, switch to TF 2.7 or change libcudnn8-dev to libcudnn8 (via `!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2`).

The purpose of the tutorials is that it should just run in colabs so that you can focus of the material and not trouble shooting the environment. It is really hard to trouble shoot the environment when you are not given a build eg requirements.txt file with library dependancies.

Google Tutorial
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/images/transfer_learning_with_hub.ipynb

My Gist
https://colab.research.google.com/gist/ejboettcher/941018debe5072ab638087ea2cc6d30a/transfer_learning_with_hub.ipynb

Fails at 
```bash
result = classifier.predict(grace_hopper[np.newaxis, ...])
result.shape
```

**Comment by colaboratory-team** [comment]
The fix is rolling out now, so you may not see the issue on a new runtime. Until its fully rolled out, as you noted, either of the following should fix it:

!pip install -U tensorflow==2.8.2

or

!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2

Either work-around requires a restart of your runtime.

**Comment by colaboratory-team** [comment]
The fix for this should now be fully rolled out, closing.
