### ISSUE TITLE
Unable to get GPU allocated for Colab Pro

### ISSUE THREAD

**Issue by rajans** [googlecolab/colabtools#3034]
I am a Colab Pro user but when I try to connect to a runtime with gpu is keep giving me error:

"Failed to assign a backend
No backend with GPU available. Would you like to use a runtime with no accelerator?
[More info](https://research.google.com/colaboratory/faq.html#gpu-availability)"

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
