### ISSUE TITLE
GPU has a permanent limit in Google Colab

### ISSUE THREAD

**Issue by UltimateAmitieKaiNiC** [googlecolab/colabtools#3045]
Remember that Google Colab's GPU limit only takes one day to be lifted, but it is still not lifted after a day. Is the GPU permanent limit?

**Comment by cperry-goog** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
