### ISSUE TITLE
Cells output disappear

### ISSUE THREAD

**Issue by tsiq-maxime** [googlecolab/colabtools#305]
It looks like opening a notebook in Colab removes all the cells output. 

To reproduce: 
 - Save jupyter notebook after running some cells
 - Upload to google drive
 - Open with Colab

When first opening the file, the output appears but soon the file on google drive will be overwritten by a new version that does not have the outputs.

**Comment by tsiq-maxime** [comment]
Yes, I wrote a very simplistic notebook to test this. 

Here is the notebook as created and saved in jupyter notebook

![screen shot 2018-10-16 at 09 37 38](https://user-images.githubusercontent.com/39531734/47003563-6e582400-d127-11e8-9bb7-b726bb4630ad.png)

Here is the file after a few minutes in colab:

![screen shot 2018-10-16 at 09 38 43](https://user-images.githubusercontent.com/39531734/47003577-787a2280-d127-11e8-83cb-9f67376ed18c.png)

When I download it and look at the json, I can see that all the outputs have disappeared and the execution count is back to 0

**Comment by tsiq-maxime** [comment]
Here is a simpler way to reproduce the issue.

- Go to the [Hello, Colaboratory](https://colab.research.google.com/notebooks/welcome.ipynb) notebook.
- Click "copy to drive"
- Now if you wait a minute and reload the notebook, the cells output will have disappeared.

**Comment by blois** [comment]
Can you try from a Chrome incognito window?

This is very unexpected behavior.

**Comment by tsiq-maxime** [comment]
Tried on an incognito window, I observe the same behaviour

**Comment by blois** [comment]
If the notebook is shared as 'view' or 'comment' then they will not be able to modify the document.

If you are still seeing this, in your preferences do you have 'New notebooks use private outputs (omit outputs when saving)' enabled?

**Comment by tsiq-maxime** [comment]
I tried your suggestions:

Sharing as view or comment works on the condition that the person who created the document never opens it again (because he can still edit it), so it is not practical.

Enabling or disabling the "New notebooks use private outputs" option does not seem to make a difference for this problem

**Comment by meiler** [comment]
Hi, I talked to everyone on my team and no one had "New noteboks use private outputs[...]" enabled. 

We're seeing this problem only in some cases (maybe 1/3) - but I haven't been able to create a coherent steps to reproduce. 

I'll gladly have a look at the one you shared if you give me access. Otherwise I'll get back when/if we find steps to reproduce. 

Thank you

**Comment by blois** [comment]
Updated the link, apologies!
https://colab.research.google.com/drive/1IOt60rGf27czSeibaMyYOZJr3OfgGV9o

When this happens, do all outputs get removed? Is it possible that the file is being updated outside of Colab?

**Comment by TheCrazyT** [comment]
For some reason you can't even change the "private-output" setting back.
I once setted the settings to skip outputs in a notebook.
Later I created a copy of that notebook. and removed the setting.
But it does not seem to have any effect. (well it stores the setting, but if you share the link the outputs do not appear on the shared link)
Not shure what I'm supposed to do now.
The notebook info also shows that "private outputs are disabled" although the setting shows it different.

**Comment by thierryherrmann** [comment]
I had the same problem: even if I unchecked the "Omit code cell output when saving this notebook" in the notebook settings.
But here's what I've discovered (might be a workaround):

When my shared my initial notebook, no cells outputs were visible by the recipient. So I discovered the "Omit code cell output..." option, unchecked it, resaved the notebook: outputs still not visible by the recipient (this is the problem)

Then I've done a *copy* of the notebook (while the option was unchecked) with "File -> Save a Copy in Drive". I shared that copy and THEN the outputs were visible. So the issue seems to be related to *when* the option is unchecked.

Now I just need to remove the original notebook, rename the copy with the name of the original and the problem is fixed. Kind of a hack, but definitely I could reproduce the original problem described here.

**Comment by cperry-goog** [comment]
File a new issue if you encounter this again.

**Comment by clannoronha** [comment]
> Disable Urban VPN extension if you have installed, in my case that was the problem.

Yes.... This solved my issue... Thanks a lot

**Comment by khalliltekil** [comment]
> Disable Urban VPN extension if you have installed, in my case that was the problem.

thanks a lot that work for me

**Comment by akhiltu** [comment]
> Disable Urban VPN extension if you have installed, in my case that was the problem.

Bro tried everything installed the VPN today

**Comment by amirhosseindavoody** [comment]
> Disable Urban VPN extension if you have installed, in my case that was the problem.

This solved my issue.

**Comment by clannoronha** [comment]
Ok thanks

**Comment by jinu2** [comment]
> Disable Urban VPN extension if you have installed, in my case that was the problem.
Finnaly, solved my issue.
