### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by amalia0007** [googlecolab/colabtools#3050]
Trying to use a method from the package 'pyspark.ml.classification import LogisticRegression' but it gives me an error and i don't know how to solve it:
Py4JJavaError                             Traceback (most recent call last)
[<ipython-input-29-229e47f4bcc0>](https://localhost:8080/#) in <module>
      3 lr = LogisticRegression(featuresCol = 'features', labelCol='x')
      4 
----> 5 model= lr.fit(train_data)

5 frames
[/usr/local/lib/python3.7/dist-packages/py4j/protocol.py](https://localhost:8080/#) in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o448.fit.
: java.lang.OutOfMemoryError: Java heap space

**Comment by mayankmalik-colab** [comment]
This looks like out of memory issue to me. You need more memory to perform the operations. Can you train/test with smaller dataset? Otherwise, you can also try increasing the default `driver memory` and `executor memory` in spark configuration. There are a different ways to do that. I think you'll have more luck asking it on Stackoverflow.
