### ISSUE TITLE
troubles imporint python modules from succesfully installed third party libraries. Better understanding of virtual machine file system.

### ISSUE THREAD

**Issue by maurolabella** [googlecolab/colabtools#3061]
**Describe the current behavior**
I succesfully install a third party library though I can not import modules from it. !cd command does not work as well.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
i should import python modules from the newly installed library.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Microsoft Edge
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub https://colab.research.google.com/gist/maurolabella/0ed368d9d86db78d4aa84491049f8b77/doctr_from_source2.ipynb
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by mayankmalik-colab** [comment]
- In order to change a directory, `!cd` would not work as expected. This is because shell command is executed in a temporary subshell. However, you can use `%cd` magic command to have a lasting effect. For more details, you can read [shell related magic commands](https://jakevdp.github.io/PythonDataScienceHandbook/01.05-ipython-and-shell-commands.html#Shell-Related-Magic-Commands).
- Though I haven't used this package myself, I just tried installing from PyPI and importing worked fine.  Can you try installing from PyPI and not via github repo.
`!pip install python-doctr` # would require a restart
`from doctr.io import DocumentFile`

**Comment by maurolabella** [comment]
Thank you very much! I was not aware of your answer till now, so sorry I did not thank you before.


Sent from Yahoo Mail for iPad


On Thursday, September 15, 2022, 5:05 PM, mayankmalik-colab ***@***.***> wrote:



   
   - In order to change a directory, !cd would not work as expected. This is because shell command is executed in a temporary subshell. However, you can use %cd magic command to have a lasting effect. For more details, you can read shell related magic commands.
   - Though I haven't used this package myself, I just tried installing from PyPI and importing worked fine. Can you try installing from PyPI and not via github repo.   
!pip install python-doctr # would require a restart   
from doctr.io import DocumentFile
