### ISSUE TITLE
Backspace one space at a time, not a tab

### ISSUE THREAD

**Issue by shuoooo** [googlecolab/colabtools#308]
When I am coding in colab. It seems that I can only backspace one space at a time, instead of backspacing a tab. It's not efficient. Is there a way to address this problem?

**Comment by meeotch** [comment]
+1 for this.

A workaround is to hit shift+tab to tab backwards a level.  But it feels like this behavior should be bound to backspace, since you're way more likely to be trying to move back by one indentation level than to start some new in-between indentation level that's one space off from the previous one.

I guess maybe nobody notices because the default tab width is only 2 spaces, so they just hit backspace twice.
