### ISSUE TITLE
google colab can not compute a modular multiplicative inverse using python 3.8 and newest version 

### ISSUE THREAD

**Issue by Ghoudi12** [googlecolab/colabtools#3100]
Google colab can not compute a modular multiplicative inverse using python 3.8 and newest version 

I use Chrome,

https://colab.research.google.com/drive/1vhTYiO_8Pj9R0M0OPHyRmBjcX5gur1qV?usp=sharing

**Comment by colaboratory-team** [comment]
Upgrading the python binary will not change which version of python that your runtime is connected to; code cells will still run in Python 3.7. Note that your notebook works if you instead invoke the newly-upgraded python binary directly:

```
!python -c "print(pow(38, -1, 97))"

23
```

We generally don't recommend that you try and upgrade the python version, since it leads to confusing results like this, and may result in other things breaking since everything else in the runtime still expects Python 3.7
