### ISSUE TITLE
Suggestion - Ban stable diffusion and undo the colab credits change

### ISSUE THREAD

**Issue by KimberleyJensen** [googlecolab/colabtools#3147]
Like google banned deepfakes they should ban stable diffusion and undo the credit system. 

Google colab was the only way for me and many others to use a gpu for school work. The credit system doesn't give enough time per month and i cant buy extra credits or a gpu.

**Comment by buoyrina** [comment]
Agree

**Comment by mitrandirr** [comment]
I wish somebody in this corporation would give a damn about these complaints, but they won't because they've never done it before.
I'm from Iran and the government has recently banned the internet, now by dealing with this issue my research program has been completely disrupted. unfortunately, nobody cares in California.
_

**Comment by domarquez** [comment]
me me me

**Comment by domarquez** [comment]
not agree

**Comment by cperry-goog** [comment]
We have no plans of banning stable diffusion or changing the pricing model at this time.
