### ISSUE TITLE
Unable to connect the code run on the previous notebook

### ISSUE THREAD

**Issue by Ammar-Azman** [googlecolab/colabtools#3168]
Let say that I ran `import pandas as pd` on the first block. 

Then I ran `df = pd.read_csv('some_file.csv') ` on the second block. 

It always happened that after running the second block, it showed pandas is not imported yet though I have imported it on the first block for numerous time. It's like everything need to be run on the same block like script which destroyed the purpose of notebook. 

Please fix this.

**Comment by mco-gh** [comment]
This is a property of all [Jupyter notebooks](https://jupyter.org/), which is the type of notebook served by Colab. An important thing to understand about this class of documents is that they are stateful, i.e. the behavior of running any given cell is a function of what you've already done during that session, where a session can be thought of as a long lived connection to the resource that actually runs the code in your cells.

When a session is restarted for any reason, either explicitly or due to a timeout or other resource exhaustion, the session reverts to a blank slate. That's why you can't always assume that an arbitrary cell in a notebook can be run without first setting up the dependencies. 

What can be confusing is that sometimes the notebook appears to be stateless, because the session persists long enough that it seems like everything remains intact and you can repeatedly execute arbitrary cells, but that's not going to work across session boundaries.

What I like to do is consolidate most of the dependencies into a small number of cells near the top of my notebooks. Then, if I know a session has restarted or I discover that's happened because I see errors related to uninitialized dependencies, I know to run those "setup cells".

**Comment by cperry-goog** [comment]
Thanks Marc, closing
