### ISSUE TITLE
The following values were not passed to `accelerate launch` and had defaults used instead:

### ISSUE THREAD

**Issue by DjTecmo** [googlecolab/colabtools#3169]
The error warns me: "To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`."
but, how do i do this? what and where the hel is this config?
This error is predescesor of an error of a next cell  in the section "Inference" that gives me the error

OSError: Error no file named model_index.json found in directory /content/drive/MyDrive/stable_diffusion_weights/TECMO.

**Comment by mco-gh** [comment]
The missing file is because your notebook is trying to load the weights for an ML model from a file in Drive that can't be read (perhaps Drive is not mounted, the file doesn't exist, has the wrong permissions, etc.).

The other part of your question seems like a dup of [3170](https://github.com/googlecolab/colabtools/issues/3170). For that, see my comment [here](https://github.com/googlecolab/colabtools/issues/3170#issuecomment-1285205599).
