### ISSUE TITLE
Starting week of 11/14/22, INTERVAL types in BQ to_dataframe() call cause notebook kernel crash

### ISSUE THREAD

**Issue by wlongabaugh** [googlecolab/colabtools#3231]
**Describe the current behavior**

Starting this week, it appears timestamp INTERVAL types coming out of BigQuery cause the Colab kernel to crash 100% of the time when being converted to a dataframe. This snippet reproduces the crash (plug in your own project ID):

```
from google.colab import auth
from google.cloud import bigquery

auth.authenticate_user() 
bigquery.Client('<your-project-id>').query("SELECT MAKE_INTERVAL(second => 1) as duration").to_dataframe()
```
When this is run, I get a Google Colab notebook kernel crash reported: "Your session crashed for an unknown reason". Logs are uninformative.

**Describe the expected behavior**
I expect a dataframe that matches the result when run in BQ:

```
duration
0-0 0 0:0:1
```
Lacking that, the error should be handled gracefully, and not with a kernel crash.

**What web browser you are using**
Chrome  Version 106.0.5249.61 (Official Build) (x86_64)

**Additional context**
The above snippet is all that is needed. I see  from release notes 11/11/22 that google-cloud-bigquery was upgraded from 1.21.0 to 3.3.5 (!!). It appears current BQ Python libraries do not support INTERVAL types in dataframes [BQ issue 826](https://github.com/googleapis/python-bigquery/issues/826)

**Comment by colaboratory-team** [comment]
Sorry about the breakage. We did recently upgrade the google-cloud-bigquery package, as 1.21.0 is over 3 years old.

As you noted, this seems to be an issue with the bigquery library itself. https://github.com/googleapis/python-bigquery/issues/836 is a good issue to follow. I wouldn't expect a fix soon, since it hasn't seen much movement in the past year, but I'll try and reach out to see if they can at least make this throw an exception instead of crash the runtime

For immediate fixes, it seems to just be the dataframe conversion that doesn't work. You can still iterate over the results in other ways:

```
from google.colab import auth
from google.cloud import bigquery

auth.authenticate_user() 
res = bigquery.Client('PROJECT').query("SELECT MAKE_INTERVAL(second => 1) as duration").result()
for row in res:
  print(row.duration)
----------
0-0 0 0:0:1
```

You can also downgrade to the old version (make sure you restart your runtime afterwards)

```
pip install google-cloud-bigquery==1.21.0
```

This will result in some incompatible packages, which you can also resolve by downgrading if they are ones that you care about

**Comment by colaboratory-team** [comment]
I may have spoken too soon, it looks like upgrading pyarrow makes it work:

```
!pip install pyarrow==9.0.0
```
```
from google.colab import auth
from google.cloud import bigquery

auth.authenticate_user() 
bigquery.Client('PROJECT').query("SELECT MAKE_INTERVAL(second => 1) as duration").to_dataframe()
--------
0 | <DateOffset: days=0, microseconds=1000000, months=0, nanoseconds=0>
```

I'll work on upgrading that package in our base image so you don't have to manually upgrade

**Comment by wlongabaugh** [comment]
Thanks for the analysis and the fix!

**Comment by colaboratory-team** [comment]
pyarrow upgrade has landed, closing this out
