### ISSUE TITLE
bin() function error with list comprehension

### ISSUE THREAD

**Issue by Lableue** [googlecolab/colabtools#3242]
code
-> 
arr1 = [9, 20, 28, 18, 11]
arr2 = [30, 1, 21, 17, 28]

bin_list = [arr1[i] | arr2[i] for i in range(len(arr1))]
bin_list = [bin(num) for num in bin_list] <- raising Error

**Describe the current behavior**
 a list container consisting of int -> a list consisting of bit by bin() function
but, raising Error take turns these -  TypeError: 'int' object is not callable   or   'str object is not callable

**Describe the expected behavior**
after this code,       bin_list = [bin(num) for num in bin_list]

bin_list have bits are str type

**What web browser you are using**
Chrome

**Comment by mco-gh** [comment]
This code sequence works fine for me, both in the Python repl and a Colab notebook *the first time only* but subsequent trials fail because you've altered the bin_list, which is referenced on both sides of the assignment statement. If you want to make this operation idempotent, I'd recommend using different variables for the source list and the converted list.
