### ISSUE TITLE
AttributeError: module 'mahotas' has no attribute 'regmax' in Google colab

### ISSUE THREAD

**Issue by SudeepAJ** [googlecolab/colabtools#3324]
So I just wanted to see how 'regional maxima/minima' works so I installed mahotas library using !pip in google colab. The collab is  nicely showing no error when type our the function but when I run it it is showing it doesn't exits. 
![image](https://user-images.githubusercontent.com/85752005/210162717-a4f63577-8c43-4086-b7fd-bc75cb074337.png)

**Comment by metrizable** [comment]
Thanks for using Colab. I see that you are attempting to install `mahotas` via pip, exercising some functionality from that package, and running into an `AttributeError` on invoking `mahotas.regmax`.

While working through replicating your issue, I discovered a few things.

First, I successfully installed `mahotas==1.4.10` and worked through one of the [examples](https://github.com/luispedro/mahotas/blob/v1.4.10/docs/source/distance.rst) that uses the `regmax` functionality. However, in the demo, it is invoked as `mahotas.morph.regmax`, which may be relevant to your use case, as well.

![5DBTs8cEpiXbTX3](https://user-images.githubusercontent.com/65414824/210834198-c3d6beb8-7fa3-4ae7-b853-8b672b1d4eb2.png)

Second, from what I can tell, it appears that the `mahotas` [pre-compiled wheel](https://pypi.org/project/mahotas/1.4.13/#files) for version 1.4.13 for Python 3.8 was compiled using a particular `numpy` version that's incompatible with the one pre-installed on Colab. Further, the `mahotas` package has only declared an [unpinned dependency](https://github.com/luispedro/mahotas/blob/v1.4.13/requirements.txt#L1) on `numpy` so that even when `mahotas` is installed via pip, a version of `numpy` that it may require is not brought in. If you wish to use version `mahotas==1.4.13` on Colab, I'd recommend filing an upstream issue with the `mahotas` package maintainers in this regard.

![8iDQNrNXHAVQLnf](https://user-images.githubusercontent.com/65414824/210834934-6a7c16ff-e2d1-495f-8788-fa2da7dde597.png)

I only explored a small subset of the functionality of `mahotas` versions 1.4.10 (with success) and 1.4.13 (had the issue mentioned above), so YMMV.

**Comment by mayankmalik-colab** [comment]
It seems like `mahotas.regmax` works fine in `1.4.12` and not in latest - `1.4.13`.  So, you can also use `mahotas.regmax` by installing the prev version.  
 `!pip install mahotas==1.4.12`.
