### ISSUE TITLE
found a bug in collab I'm getting this error when running step 2 in colab tools PIFuHD_simplified_v1

### ISSUE THREAD

**Issue by SpaceCadet007** [googlecolab/colabtools#3345]
I'm getting this error when running step 2 in colab tools PIFuHD_simplified_v1

error: OpenCV(4.6.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:801: error: (-215:Assertion failed) !_img.empty() in function 'imwrite'

**Comment by SpaceCadet007** [comment]
I'm getting this error when running step 2 in colab tools PIFuHD_simplified_v1 
any suggestions..?

Goal: Image to 3D model (PIFuHD)

**Comment by metrizable** [comment]
Thanks for using Colab. Can you share a minimal repro notebook? I searched and found a few `PIFuHD_simplified_v1` notebooks in the wild, but from their contents, they appear to be using very old dependencies (e.g. `torch==1.6.0+cu101`).

**Comment by Thidney** [comment]
Here is a link [https://colab.research.google.com/drive/1NzP4oI_KighbpfEEVCnYKZ0lfzDpqTyE?usp=sharing#scrollTo=8KHPtNWwObj-](PIFuHD_simplified_v1).
I have same problem as SpaceCadet007.

**Comment by metrizable** [comment]
Thanks @Thidney for the example notebook.

On inspection, I see that it specifies several outdated dependencies, as well as shell syntax that swallows errors. Of note, I see use of an old version of `torch`, which was built against CUDA 10.1. Some functionality may not work correctly in this case, especially if it relies on GPU, since the Colab runtime ships with CUDA 11.x. I'd recommend working with the notebook author to upgrade the notebook to be more compatible with the current Colab runtime.

I also tried to execute the notebook and ran into the error posted by the OP:

![Screenshot from 2023-01-23 17-06-20](https://user-images.githubusercontent.com/65414824/214192171-0b6f7b41-dd94-4797-8aab-91ed5483a2a9.png)

Digging a bit, I see the error occurs trying to write to a file, but the source image is empty:

![Screenshot from 2023-01-23 17-05-24](https://user-images.githubusercontent.com/65414824/214192385-1b2f403e-a5b2-4340-ad2d-8f9aef5c346f.png)

Investigating this a bit more, the `$image_url` is not resolving to a valid path:

![Screenshot from 2023-01-23 17-05-06](https://user-images.githubusercontent.com/65414824/214192700-f3748806-ad15-4eba-beff-1fd27f2ff136.png)

Updating the older shell syntax to use `'{}'` rather than `'$...'` for interpolating Python variables, given that `$` [parsing functionality was updated in IPython](https://github.com/ipython/ipython/pull/10545) and for Colab [in #3017](https://github.com/googlecolab/colabtools/issues/3017), does fix one error but reveals another -- that the image being fetched is gone: 

![Screenshot from 2023-01-23 17-17-40](https://user-images.githubusercontent.com/65414824/214193351-6da70ba9-bc4d-4785-8bfa-db2e37b2811f.png)

Given these issues and the outdated dependencies specified, working with the notebook author on an upgrade is probably the best path forward.
