### ISSUE TITLE
Tensorflow version is inconsistent between Colab container and TPU worker

### ISSUE THREAD

**Issue by ychfan** [googlecolab/colabtools#335]
Some Ops will cause the error "No OpKernel was registered"

**Comment by craigcitro** [comment]
Can you share a sample notebook that's giving you this error?

**Comment by ychfan** [comment]
Here is one [example](https://colab.research.google.com/drive/1ynY2_d4YwRY4Zu7E8UEu0_M9wPPyIwVg)

**Comment by gitosaurus** [comment]
I believe the problem is that you're using `Estimator` with a TPU; instead, use `TPUEstimator`, following these instructions for [converting from `Estimator` to `TPUEstimator`](https://cloud.google.com/tpu/docs/using-estimator-api#converting_from_tensorflow_estimator_to_tpuestimator).

Out of curiosity, why did you think it was a version mismatch?

**Comment by ychfan** [comment]
Why `TPUStrategy` does not work in colab, it can be found in the [example](https://github.com/tensorflow/tpu/blob/master/models/experimental/distribution_strategy/resnet_estimator.py) from official tpu example repo.

For version mismatch,
In my [example](https://colab.research.google.com/drive/1ynY2_d4YwRY4Zu7E8UEu0_M9wPPyIwVg), returned error is `Registered kernels: <no registered kernels>`, for my understanding, the error is from TPU worker, and the TF on TPU worker does not include `InfeedEnqueueTuple` op.

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystems including TensorFlow since then, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
