### ISSUE TITLE
High RAM Usage Issue in Colab

### ISSUE THREAD

**Issue by geocine** [googlecolab/colabtools#3363]
**Describe the current behavior**
System ram usage peaks when loading Stable Diffusion diffusers model (my case). **This was not happening before the Ubuntu update** https://github.com/googlecolab/colabtools/issues/3327. I have not changed any dependencies on my end nor any code that will trigger this. Also a number of people have reported the issue in several places.

https://github.com/googlecolab/colabtools/issues/3348#issuecomment-1396419855
> I just tested that notebook. That wheel is still compatible with the current version of Colab so I don't think it is the problem here. I found out that the RAM usage go unusually high when the program load Stable Diffusion checkpoint even though it only has 2GB in size. This bug also only appeared when I used current Colab runtime version. - [Fannovel16](https://github.com/Fannovel16)

https://github.com/googlecolab/colabtools/issues/3348#issuecomment-1398721406
> @metrizable Since the last few days, the RAM usage is inexplicably high in Colab, especially when using Stable Diffusion, what changed ? - [TheLastBen](https://github.com/TheLastBen)

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7003
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6957#issuecomment-1398483390
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6957#issuecomment-1401564726
https://github.com/TheLastBen/fast-stable-diffusion/issues/1404
https://github.com/geocine/sd-easy-mode/issues/1
https://github.com/googlecolab/colabtools/issues/3372

Issues that _could be_ related:
https://github.com/googlecolab/colabtools/issues/3364
https://github.com/googlecolab/colabtools/issues/3368

**Describe the expected behavior**
System RAM usage should be normal during inference.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
https://colab.research.google.com/github/geocine/sd-easy-mode/blob/main/EasyMode_Stable_Diffusion.ipynb
 1. Setup > Train <-- System RAM goes back to normal after train
 2. Generate <-- Notice System RAM is unusually high (problem)
 3. Save <-- System RAM peaks . Colab crashes due to insufficient System RAM (problem)

**Comment by metrizable** [comment]
@geocine Thanks for using Colab. I understand that you are experiencing crashes with the example notebook you supplied when executing the `Save` cell.

I examined the notebook you provided and, although I haven't been able to replicate your issue, I have modified one line in the Setup cell of the notebook to use an updated pre-compiled wheel as it seems the notebook you supplied is using an outdated one:

Original pre-compiled wheel (`v0.0.15`) created Dec 23, 2022 prior to #3327 that appears outdated
```
XFORMERS_URL = 'https://github.com/geocine/dreamstall-binaries/releases/download/cxx-p38-txx-linux/xformers-0.0.15.dev0+4c06c79.d20221205-cp38-cp38-linux_x86_64.whl'
```

A pre-compiled wheel (`v0.0.16`) created Jan 18, 2023 shortly following #3327
```
XFORMERS_URL = 'https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.16/xformers-0.0.16+814314d.d20230118-cp38-cp38-linux_x86_64.whl'
```
After running the Generate step, I noticed two things 1) an error `module 'triton.language' has no attribute 'constexpr'` which looks mildly concerning, and 2) RAM usage was in the high range:

![7wm9vds68PNn6pd](https://user-images.githubusercontent.com/65414824/214359021-8431106d-f4a2-48f2-9ae8-0fa6e8fe7d3b.png)

I investigated the RAM utilization, but came up with nothing conclusive. I then executed the Save cell successfully:

![Screenshot from 2023-01-24 08-52-57](https://user-images.githubusercontent.com/65414824/214365923-c07ce14b-4c94-4bbf-b75b-e9409186d43f.png)

Although I wasn't able to reproduce the crash, this may be due to any number of factors, including 1) using an updated wheel as mentioned above, 2) uploading only a small corpus of images, 3) a delay between executing Generate and then executing Save (when I was investigating memory usage, although I have doubts that this plays a role).

**Comment by geocine** [comment]
@metrizable  Thank you for looking into this with details of your findings. I tried your solution but it still crashes. The number of training images during training should not matter as the System RAM goes down after training. 

Try to generate 4 images 2 consecutive times before executing save. This issue was reported by one of my users, which I can also reproduce. https://github.com/geocine/sd-easy-mode/issues/1. For now I added a workaround.

**Comment by MedicDoesStuff** [comment]
This is basically the same problem i've been experiencing with saving models after the Ubuntu update, it has really been bugging me and i hope it'll get fixed off later soon.

**Comment by geocine** [comment]
Is there a way to force clear system ram without restarting the runtime using `system.exit()` ?

**Comment by metrizable** [comment]
@geocine We recently released a change to how we use tcmalloc in the latest Colab runtime. Executing the "Getting started with Diffusers" [notebook](https://github.com/huggingface/notebooks/blob/main/diffusers/README.md), we see an improvement in RAM utilization over our earlier release:

![Bryqws75ZqjMqku](https://user-images.githubusercontent.com/65414824/217333517-24d5ab73-9027-4605-824e-7ed2d2f2e88a.png)

I also ran the example notebook you provided end-to-end successfully, including saving (I did make one modification to the  latest notebook by commenting out the call to `exit()` in the Save cell):

![5CXNghE7TTTCw5G](https://user-images.githubusercontent.com/65414824/217358016-602733d2-f80b-462d-a092-70e0f81043eb.png)

**Comment by remybonnav** [comment]
Please please please a fix :)

**Comment by Omenizer** [comment]
Yes, this is painful. Can't buy new compute units if this persists :(

**Comment by EvanWiederspan** [comment]
We believe the RAM issue from the original comment to be resolved now with the tcmalloc change mentioned above. If you are still seeing issues, please file a new issue with a repro notebook

**Comment by remybonnav** [comment]
This is not fixed, 
When loading one model  after the other the RAM stil l reach over 12GB and crash 8models are only 2 GB).. This never happened like 3 or 4 weeks ago,  using https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by Aryazaky** [comment]
This is still plaguing me. Had to restart session every time.
