### ISSUE TITLE
Previously working code returns 'int' object is not callable, on different runtime.

### ISSUE THREAD

**Issue by andrewJohnson92413** [googlecolab/colabtools#3367]
During a runtime the day prior, the code below worked flawlessly

numList = [12, 75, 150, 180, 145, 525, 50]
x=0
while x<len(numList)+1:
  print("yes")
  x=x+1

The output was as you would expect, it printed on the 'yes' message until x was more than len(numList)+1.

However, today in my CompSci class I reused the same basic function, just with swapped varibales and it returned me with an error saying, " 'int' object is not callable". To make sure I wasn't just doing something wrong, as I'm new to coding, I checked the code from yesterdat, listed above, and it returned the same error. Upon stopping my runtime and creating a new one, the code worked again without issue. Im not sure how this happened but any insight would be great.

I am using Google Chrome.

**Comment by mco-gh** [comment]
That sequence works fine for me. Can you share a reproducible notebook that manifests the problem you're seeing so I can try to help?

**Comment by EvanWiederspan** [comment]
One feature of Python is that you can re-assign built-in functions to be whatever you want. From the error, I would assume that you either set `len =` or `print =`, and now your above code is calling those functions which have been replaced with an int. Generally you should never assign variables with the same names as built-in functions, to avoid situations like this. 

Running the "Restart Runtime" command resets all variables, so your above block worked since the functions were no longer overridden
