### ISSUE TITLE
Cell Magic %%time in Colab Python Jupyter Notebook does not report wall clock time correctly.

### ISSUE THREAD

**Issue by lvwarren** [googlecolab/colabtools#3374]
**Describe the current behavior**
When I use the cell magic %%time command it does not report elapsed wall clock time correctly.

**Describe the expected behavior**
When I execute a single cell prefaced with %%time, it reports a wall clock time of 15.7 microseconds when 25-30 seconds have actually elapsed. It does this on several kinds of commands.

**What web browser you are using**
Chrome and Firefox behave the same.

**Place this code in the cell of a Colab Python Jupyter Notebook**
%%time
from google.colab import drive

to obtain:
<img width="697" alt="Screen Shot 2023-01-26 at 9 59 17 PM" src="https://user-images.githubusercontent.com/589358/215007769-aee9b9d0-c9d4-463d-9bf5-f84ec08aa3b9.png">

**Comment by cperry-goog** [comment]
We think some of the discrepancy is waiting for kernel assignment. Can you confirm?

**Comment by lvwarren** [comment]
That was my hunch going in, but I wanted to hear it from the hive.

I tried thinking of ways that this error could be defeated, the number being presented is basically how long the kernel has existed, after the timing request has long since expired. It's down in the bowels of provisioning, above my pay grade.
________________________________

**Comment by EvanWiederspan** [comment]
If the first cell you run connects you to a new runtime, it's going to take a while since it has to connect to a VM and start up a kernel, which won't be reported by %%time since the code technically hasn't run yet. If you want %%time to give a more accurate number closer to how long it has been for you, I would run another cell first to make sure that you are connected to an active kernel first
