### ISSUE TITLE
I can connceto to a GPU for around one or two week

### ISSUE THREAD

**Issue by sergiogonzalezch** [googlecolab/colabtools#3396]
**Describe the current behavior**
All start when i tried to make a dreamboth for train a style after that the next day I use to merge models, but around the wensday i cant connect to GPU

I can connect with the cpu and tpu, but i feel scary... I didn't nothing wrong... (Well may be some furries....) Please what i can do.

Browser Firefox and Chrome.

**Comment by EvanWiederspan** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
