### ISSUE TITLE
Kernel restarted in the middle of program execution

### ISSUE THREAD

**Issue by bigghostshadow** [googlecolab/colabtools#3554]
I used Chrome and run the program but in the middle of the program it restarted. It happened 3 times. I use google collab pro +. I bought the service to run this specific program which is time-consuming and memory greedy. but it failed to run the program. resources are reduced but the program could not be run fully. due to kernel restart all variable values were lost.

https://colab.research.google.com/gist/bigghostshadow/d6e1a6fb90229cc89f6ec6d362c496ab/code_v9_all_dl_and_4-ml-classifiers_trainable.ipynb

**Comment by EvanWiederspan** [comment]
Could you provide the logs from Runtime -> View Runtime Logs after the kernel restarts? It may be due to running out of memory, which in that case we won't be able to fix much.

I also see a NameError in the notebook you shared, is that the place where the code stops running? If so, that's a code issue, and you'll need to update your code to ensure that x_train is defined
