### ISSUE TITLE
"This Colab is available only for paid plan users" on-off switch for developers

### ISSUE THREAD

**Issue by camenduru** [googlecolab/colabtools#3591]
Hi Colab Team! 👋 First, thanks for the Colab Project ❤

I enjoy converting AI projects into Colab notebooks 😀 you can find more here: https://github.com/camenduru
and this project https://github.com/camenduru/stable-diffusion-webui-colab has become super popular 🥳 and it looks like the GPU go brrrrrrr 🤣
 
Thanks to Chris Perry for the clear explanation of why we are getting the scary 😱 message: https://twitter.com/thechrisperry/status/1649189902079381505

![image](https://user-images.githubusercontent.com/54370274/233510506-79054d7d-896d-4eff-90a5-bfb6410fcb8d.png)

Is it possible to make this message clearer, such as 'This Colab is available only for paid plan users' instead of making it seem like the Colab developers made something suspicious? 😋 

and for the feature "This Colab is available only for paid plan users" on-off switch for developers!

Thanks ❤
https://twitter.com/camenduru

**Comment by kieranxsomer** [comment]
I'm fully agreeing on this, I was aware that Chris had stated the same thing that these SHOULD be available for paid users, as far as he was aware.  Though as of tonight a custom colab I was using for Web UI kept disconnecting without even giving me a captcha.  I wasn't even given a "this code is against ToS" - though i am now again a paid user,  as I topped up my points.  This is extremely expensive for me as it is for many people - and while I understand FULLY why in some ways Free tier must sort of look elsewhere - it's only A1111 that seems to be gotten hit.

My query along with i'm sure others like Camenduru is on top of this, why not Easy Diffusion? Why Not Invoke?  Could colab explain why it's a1111? is it the Gradio instances? IS there something inheritley in A1111 extensions that takes up too much resources..

Why can't there be a workaround instead of a functional "half ban" or "termination"?

**Comment by Joseph7695** [comment]
So anything A1111 is a no go ? Or can we use it "interactively" by calling the api's from within the colab environment somehow, instead of using the webui

**Comment by cperry-goog** [comment]
We've updated the wording of the big scary prompt, and yeah, I'm thinking about how to better position this for folks, thanks for the feedback!

**Comment by volnet** [comment]
The decision to offer a free plan was an early action, and nobody could have foreseen the rapid development of AI. As a company, Google has its own financial guidelines. Although we often treat this "enterprise" as an individual, the team responsible for running and maintaining the product may indeed need to make necessary trade-offs within their existing resources.

They might have noticed the sudden surge in demand through system monitoring and promptly responded. This decision falls within their management scope. Otherwise, they would need to "request new resources, triggering a series of approval processes" or "inevitably affect other users in situations of resource conflict." Therefore, I understand the actions of the Google Colab team.

Of course, as fans of Google, we have boundless aspirations and hope that Google will respond with an entrepreneurial spirit and fulfill its initial free commitment. However, different departments within a large enterprise inevitably face actions that are "unrelated to them," unless the matter has become a public event, impacting the company's image and other aspects. Otherwise, I don't think anyone would pay attention to it.

**Comment by camenduru** [comment]
Hi @cperry-goog 👋 Please do not add open-source developers' names to your unethical list.

```
!wget contains_words_from_your_unethical_list.ipynb
%run contains_words_from_your_unethical_list.ipynb
```

Also, what is the point of your unethical list? I don't get it.
