### ISSUE TITLE
Runtime Disconnects automatically For No Reason After 3 or Less Minutes (Using fast-stable-diffusion model)

### ISSUE THREAD

**Issue by Daaihere** [googlecolab/colabtools#3644]
ERROR
I currently use google colab along with fast-stable-diffusion but every time when I turn on WebUi, it can't stay working for 2 minutes, and it disconnects by itself, so I have to download the entire repository again to use it again for 2 minutes (or less).

before this did not happen, I could stay connected as long as I wanted, I don't know if the problem must be due to the use of the GPU or something else, but the Ram Memory is always good, and there is no apparent error, I always ran it the same way, but this problem started the day before yesterday, I think there may be an update on colab.

browser                        PLEASE SOLVE IT ASAP 

Chrome

**Comment by Aberisque1278** [comment]
Same issue, I believe google is cracking down on their colab use for webui, no more free to play really. Would also appreciate some greater insight from those with more information.

**Comment by quintendewilde** [comment]
@cperry-goog why does mine keep crashing even when I pay premium. Just connection error.
Everytime I use render in stable diffusion for more then 3 hours.. I'm paying for something that doesn't work and where I get zero feedback or help from?

My chrome page with the colab (not the gui page) freezes with the background color of the theme.

Computer settings prevent the chromepage or laptop to fall asleep. So the problem is with Google.
