### ISSUE TITLE
Error when running colab notebook: TIMEOUTTraceback (most recent call last) <ipython-input-21-7ad3668e6b58> in <module>()

### ISSUE THREAD

**Issue by shyamalschandra** [googlecolab/colabtools#367]
I just checked the timeout problem with google and I get only 4+ results that are not useful.

https://www.google.com/search?safe=active&source=hp&ei=91sJXMmMFIqnrgSjvp_oCw&q=TIMEOUT%3A+Timeout+exceeded.+%3Cpexpect.pty_spawn.spawn+object+at+0x7f6343c21190%3E&btnK=Google+Search&oq=TIMEOUT%3A+Timeout+exceeded.+%3Cpexpect.pty_spawn.spawn+object+at+0x7f6343c21190%3E&gs_l=psy-ab.3...281.281..564...0.0..0.263.464.2-2......0....1j2..gws-wiz.....0.L17e0oGUeWo

Here is the colab notebook:

https://colab.research.google.com/drive/1klvJqGQOhirsMsLGIkPuG5vKVMiozAoA

**Comment by metrizable** [comment]
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem including an upgrade to Python 3.9 since then (I see the supplied reproducing notebook uses Python 2.7), if you are still experiencing the issue, please file a new issue with a minimal reproducible notebook.
