### ISSUE TITLE
Automatically scraps all the files after time interval.

### ISSUE THREAD

**Issue by Lucifer0070** [googlecolab/colabtools#3701]
I purchased colab for performing MD simulation Gromacs, AFter around 6 hours the file that are created are cleared by the colab, and the server starts showing busy, as I try reconnecting It automatically scraps all the data. I tried multiple times but lost around 4 gb of data after every try. 

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by EvanWiederspan** [comment]
We do automatically delete runtimes after a period of inactivity, so it might be that you are just getting assigned a new runtime because your old runtime was deleted. We usually recommend either saving files in Drive for long-term storage, or using a Marketplace VM (https://research.google.com/colaboratory/marketplace.html), which will never be deleted automatically by Colab
