### ISSUE TITLE
Can not use GPU after subscribing Colab Plan

### ISSUE THREAD

**Issue by DzungLeQM** [googlecolab/colabtools#3713]
Hi, I have subscribed a Colab Paid Plan. I followed the step Runtime > Change runtime type > GPU > A100/T4/V100 but there is a notice that GPU type is not available. I'm using Chrome.
How can I connect to GPU and use it? Thank you!

![image](https://github.com/googlecolab/colabtools/assets/134642718/79c6fbe1-6f7e-4236-8080-8924418f0933)

**Comment by DzungLeQM** [comment]
Oh, after trying to reconnect many time, I can connect to GPU now. Why can I not connect before?

**Comment by colaboratory-team** [comment]
There are 3 types of GPU accelerators that are currently available on Colab: A100, V100, and T4 (in the decreasing order of performance). The bottom notification message tells that the requested (selected) GPU type (A100 in this case, if you didn't change the selection on the GPU type dropdown) wasn't available at the time (due to high demand) and the next available GPU type (in this case V100) was being tried, which was successfully connected in this case, and thus you got a V100 GPU, as can be seen in your cell execution result. So you were getting GPU all the time, but initially V100 instead of the selected A100 (due to high demand on A100), and finally got A100 after reconnecting many times. Due to the limited availability, it's unfortunate that a requested accelerator type is not available like this and Colab does perform fallbacks to the next available accelerators. Hope this helps. Thanks.
