### ISSUE TITLE
Unable to change billing country?

### ISSUE THREAD

**Issue by sudoku-lord** [googlecolab/colabtools#3734]
Hi,

I'm from the US but currently on a visit to India. In order to run my Colab notebook, I need to purchase some computing units, but I'm blocked from doing so because whenever I try to add my payment card the country is listed as "India" with no option to change it. My Google home country is already set to the US and I have a payment method in my Google account already, but none of that is registering on Colab.

I really need to run my code, but am totally blocked from doing so. Is there any way I can change the billing country so I can purchase the units and run my notebook?

Thanks!

Edit: here's a [related issue](https://github.com/googlecolab/colabtools/issues/2857), but it was closed with no resolution

**Comment by cperry-goog** [comment]
Billing country is set in your payments profile, you'll need to update your payments profile or create a new one with Google Pay. https://support.google.com/paymentscenter/answer/9028746?hl=en

**Comment by sedlund** [comment]
same - doesnt work

**Comment by JuliusFx131** [comment]
you closed it but cannot still work! google, why is it so painful to offer business to you!

**Comment by sedlund** [comment]
I believe its because the US doesn't have laws that allow Google to steal your data from your notebooks like it does your gmails.  But if are physically outside the US in a country that has laws that forbid it, it opens Google up to lawsuit if they steal your data, so they need to be sure they are not sued.

**Comment by r4ravi2008** [comment]
I have the same issue

**Comment by sedlund** [comment]
I think to get around the the issue you'd have to set up a new Google account with a US vpn or IP with a payment method not in your other Google accounts and not linked to your Android device that Google payments is tracking.

From my testing it is using Android gps or likely the SIM card country from Android device you linked to the account to force your billing currency / location.

**Comment by JacobH140** [comment]
same issue on July 25, 2025, worked around with vpn

**Comment by MartinSundin** [comment]
I have the same issue on 17-04-2026. Seems like the card needs to be from the same region as where you initially created your google account (even if that was 20 years ago!).

The solution is to create a paid google cloud account, create a GPU runtime in Vertex AI, and select 'connect to google cloud run'. But that is another can of worms. E.g. if you have exhausted your free GPU quota, you cannot just create a paid account and get more GPU since you don't have a billing history with GCP, etc., etc. So those free credits you get when you sign up are basically worthless :(

**Comment by casua132** [comment]
same issue now
