### ISSUE TITLE
Standard matplotlib graphs are way too big

### ISSUE THREAD

**Issue by bruno-gpa** [googlecolab/colabtools#3747]
The standard size of matplotlib has gotten much bigger than usual. Both plot and font sizes are so big that they can barely fit in the screen, as can be seen in the image below:
![image](https://github.com/googlecolab/colabtools/assets/70606968/a6241beb-f48a-48c5-81c9-88806fc40efe)
This is how graphs used to be:
![image](https://github.com/googlecolab/colabtools/assets/70606968/d38d808e-a949-40d7-bd1d-878ae02b7f3f)
What can be done to fix this issue?

**Comment by metrizable** [comment]
@bruno-gpa Thanks for filing the issue. The behavior you're seeing is likely due to an IPython upgrade to 7.34 that rolled out at the [end of March](https://github.com/googlecolab/backend-info/commit/fe6de9060ea8173da366129432b61a05db8948fd).

If you would like plots of a particular size, you can configure it in matplotlib, and you can set your desired default plot size with, say, something like:

```
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (5, 4)
```

![4CL26MEmFKkodfx](https://github.com/googlecolab/colabtools/assets/65414824/2cf02577-71b5-4232-9d4e-84e9140f81e6)

**Comment by bruno-gpa** [comment]
The solution you suggested does the same as 
`plt.figure(figsize=(8, 4))`
It only reduces the size of the plot, while the plot title, labels, ticks and axis titles are still much bigger than usual, so the overall plot looks very out of scale.
