### ISSUE TITLE
Cannot use SURF in v4.7.0.

### ISSUE THREAD

**Issue by lywg** [googlecolab/colabtools#3750]
Hello,

I tried to do feature matching at Google Colab, using SIFT, SURF, ORB.

I know that the Colab do not support downgrade of OpenCV version, and cannot use SIFT and SURF in latest version.
But, I can use SIFT by using cv2.xfeatures2d.SIFT_create().

Then, why cannot use SURF? It doesn't work using cv2.xfeatures2d.SURF_create() at Colab.

My cv2 version is 4.7.0 and I use Chrome browser.

**Comment by cperry-goog** [comment]
Do you have a minimal repro notebook?

**Comment by lywg** [comment]
Yes, maybe this.

https://github.com/lywg/OpenCV/blob/main/Feature_Detection.ipynb

**Comment by metrizable** [comment]
@lywg Thanks for providing a repro notebook. I see from the error message that it's indicating the feature is patented,  excluded from default OpenCV, and that in order to enable this feature, OpenCV will need to be recompiled with a compile flag set.

```
error: OpenCV(4.7.0) /io/opencv_contrib/modules/xfeatures2d/src/surf.cpp:1026: error: (-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library in function 'create'
```

![B2Bj89rtFp8WBfF](https://github.com/googlecolab/colabtools/assets/65414824/615e2657-2462-4662-8e91-28a06f96ea9c)

I believe there are some [answers](https://answers.opencv.org/question/201938/how-can-i-set-opencv_enable_nonfree-cmake-option-and-rebuild-the-library-in-function-create/) on the OpenCV forum that may provide leads on doing so.

**Comment by MJAHMADEE** [comment]
This error occurs because the Surf algorithm is patented and requires specific configuration to be enabled.

To resolve this issue and make it possible to use the Surf algorithm in the Google Colab environment, please refer to the following GitHub repository and the accompanying Google Colab notebook:

https://github.com/MJAHMADEE/SURF

The repository provides a comprehensive solution to this problem, ensuring that the Surf algorithm can be used without encountering the aforementioned error. The Google Colab notebook within the repository contains detailed instructions and the necessary setup to get you started.

We hope this helps you overcome the issue and continue your work seamlessly.
