### ISSUE TITLE
the session gets terminated immediately, the session times out within a few mins of running the code. It shows a runtime error, a red color icon appears and then it stops working, please fix this bug, it has been present for almost a week now 

### ISSUE THREAD

**Issue by tshreyansh76** [googlecolab/colabtools#3813]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by alexman128** [comment]
I am getting the same behavior as the OP, obviously with a different notebook, I am trying to execute the fine_tune function for a unet_learner model and after some seconds I get the session terminated message and restarting the environment message, the expected behaviour is that it should finish the execution without restarting.

The notebook I use is like below, I am using the Google Colab Pro

https://github.com/alexman128/Guadalajara/blob/master/niitest2.ipynb

**Comment by cperry-goog** [comment]
Can you submit feedback in product and reference this issue?
