### ISSUE TITLE
No one note for Stable Diffusion from github don`t work from this day on my collab pro service

### ISSUE THREAD

**Issue by elenaabrandy** [googlecolab/colabtools#3858]
**Describe the current behavior**
Today I just wanted to continue working on my project, doing everything the same as yesterday, I launched a copy of the notebook taken from the official github link - protogen x3.4 https://github.com/camenduru/stable-diffusion-webui-colab

Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x5aaa1b46b740 

**Describe the expected behavior**
I just wanted start Automatic 1111 from link https://github.com/camenduru/stable-diffusion-webui-colab

**What web browser you are using**
Yandex

**Additional context**
https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/nightly/protogen_x3_4_webui_colab.ipynb

**Comment by agscontact** [comment]
I am running into same issue while trying to run this notebook - https://github.com/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by mayankmalik-colab** [comment]
We have [upgraded Ubuntu to 22.04](https://github.com/googlecolab/colabtools/issues/3778). You might want to upgrade your notebook to be compatible with it. However, you can still use Colab’s fallback runtime version for a few more days. Please check the section `Colab’s fallback runtime version` on the link above.

**Comment by slowargo** [comment]
That's because you are using a very old version of libtcmalloc. Prior to libtcmalloc 2.6.2, aligned_alloc() is not hooked. However, new glibc/gcc in the new runtime may use it to allocate memory. Since these allocations are not handled by tcmalloc, it produces the error when the memory is freed, which is handled by tcmalloc.
The simplest solution is to use the libtcmalloc shipped with the colab runtime, or just don't use it.
