### ISSUE TITLE
pd.to_csv save columns order is wrong

### ISSUE THREAD

**Issue by LilyZWuZz** [googlecolab/colabtools#393]
the columns order is different with local. It should follow columns order in DataFrame

**Comment by craigcitro** [comment]
Can you share a notebook demonstrating the unexpected ordering?

(Colab doesn't intervene here, so I'm guessing the difference is due to either python or pandas versions.)

**Comment by LilyZWuZz** [comment]
I use default pd. code like this:
res = pd.DataFrame()
res['id] = pd.Series(range(10))
res['label'] = pd.Series(range(10))
res.to_csv('tmp.csv',index=False)
expected result is 'id', 'label', actual result is 'label', 'id'

**Comment by kevinanewman** [comment]
I have the same problem, with a very simple dataframe:
Python 3.6.7
pandas 0.24.2

summary_dataframe = pd.DataFrame(columns={'Cycle', 'Work hp-hr', 'Work kW-s'})
summary_dataframe.loc[summary_dataframe.__len__()] = ['blah', 1, 2]
summary_dataframe.to_csv('cycle_summaries.csv', index=False)

Header in file comes out wrong, data is correct.  Header came out 
     Work kW-s | Work hp-hr | Cycle

to_excel() has the same problem.

[cycle_summaries_csv.txt](https://github.com/googlecolab/colabtools/files/3080484/cycle_summaries_csv.txt)

**Comment by kevinanewman** [comment]
I fixed mine this way:

change
summary_dataframe = pd.DataFrame(columns={'Cycle', 'Work hp-hr', 'Work kW-s'})
to
summary_dataframe = pd.DataFrame(columns=['Cycle', 'Work hp-hr', 'Work kW-s'])
defining columns as a list instead of a set... 

When the csv writer creates a list of columns from a list then the order is maintained but when the csv writer creates a column list from a set then the order is indeterminate
