### ISSUE TITLE
Cant buy colab pro - cant change billing country

### ISSUE THREAD

**Issue by lukakostic** [googlecolab/colabtools#3942]
Cannot change country when adding card:

![image](https://github.com/googlecolab/colabtools/assets/41348897/99ea994a-da6e-46b7-b03e-8121ca327b57)

This issue https://github.com/googlecolab/colabtools/issues/3734 suggests changing country in payments.google.com profile, but thats already correct:

![image](https://github.com/googlecolab/colabtools/assets/41348897/8a203ee6-d317-4522-8fad-8c361a6bd34b)

Its all the same gmail account.

**What web browser you are using**
Firefox 114.0.1 64bit

**Comment by colaboratory-team** [comment]
Thanks for reporting. Tracking internally with b/296410240.

**Comment by colaboratory-team** [comment]
This is in fact because Colab paid offerings are not yet available in your country (Serbia). Please see the image below for the list of countries where Colab paid offerings are available. The list is also available in the FAQ section of the [Colab signup page](https://colab.research.google.com/signup/pricing) with the question title `Where is the paid version of Colab available?`. Sorry that the UI/UX might be misleading in this case. We'll consider improving the UI/UX to avoid confusion like this.
![Colab paid offerings available countries](https://github.com/googlecolab/colabtools/assets/38081706/d3e1db3c-d6b5-4f7b-b586-9704c89a1379)

**Comment by dvostro** [comment]
Same , I am from Turkey and cannot change country when adding card , I already changed payment profiles country , but it s not helped , pls any advice?

**Comment by colaboratory-team** [comment]
@dvostro - Turkey is in the list of countries where Colab paid offerings are available, so you should be able to add a payment method with the correct country setting. In fact, the country should be set to Turkey automatically if your Google account's country is already set to Turkey and also if you are connecting from within Turkey. Would you confirm if that's the case? If it's still not working as expected, would you please submit a feedback by clicking `Help > Send feedback` from the Colab homepage so that we can look into this more? Please mention this Github issue in your feedback. Thanks.

**Comment by usholanb** [comment]
what if I want to set bulling address to United States while not being in the US? @colaboratory-team

it set's it to other counties automatically and I can't control it.

**Comment by fgadaleta** [comment]
same

**Comment by spencerwjensen96** [comment]
I have the same issue. Living in the UK, billing address in the US.

**Comment by alist** [comment]
Likewise, needing while abroad…

**Comment by lauraluebbert** [comment]
Has this been solved? I have the same issue (trying to sign up for Colab Pro while abroad in Spain but billing address in the US - the billing country is set to Spain and cannot be changed even when using a VPN).

**Comment by arpajik** [comment]
Same here.

**Comment by pbotsaris** [comment]
same, traveling and can't buy credits?  Can you please solve this?

**Comment by simonstax** [comment]
I am travelling in the US but I live in the UK. I cannot buy credits in the US using my UK card, even though I have UK payment profile.

**Comment by nikolagojakovic** [comment]
Has this been solved for Serbia?

**Comment by vihanga-bandara** [comment]
Why is this still not solved, I am having the same issue as well

**Comment by evavasileska-svg** [comment]
same for Macedonia, my paying profile is set to Macedonia and I'm able to pay for Google one but not for Colab
