### ISSUE TITLE
Session restarts after a crash while displaying an image 

### ISSUE THREAD

**Issue by SOB845** [googlecolab/colabtools#395]
So, basically I was trying OpenCV2 library for the first time and I have this image which I want to observe using `cv2.imshow()` function. 
When I run the code the session crashes and restarts itself; in other words, my program cannot open the image and I believe it's a bug.
I'll be thankful for any kind of help.

**Comment by colaboratory-team** [comment]
This is a crash in opencv. The underlying issue is that Colab runs in a browser, and so does not have an X server. But, opencv's `imshow` function requires X, and crashes if it is not available.

The backend logs provide a hint:
WARNING	: cannot connect to X server

A fix here would require a change in opencv2 to be more tolerant of environments without X. For now, a work-around is to disable images using a different library that supports notebook outputs. For example, if you have an image in a file called `image.png`, run:

```
from IPython.display import Image
Image('image.png')
```
