### ISSUE TITLE
i cant switch my runtime type to high RAM even though ive allready subscribe google pro

### ISSUE THREAD

**Issue by firdauzcn007** [googlecolab/colabtools#3967]
Describe the current behavior:
I have been prompted to connect to higher RAM runtime and crashing.
And now i have only 12GB RAM and can't change to higher RAM runtime anymore because i cant find toolbox to change it in "change runningtime type".

Describe the expected behavior:
i can freely change my RAM.

The web browser you are using (Chrome, Firefox, Safari, etc.):
Safari and Chrome

<img width="1552" alt="Screen Shot 2023-08-25 at 16 05 53" src="https://github.com/googlecolab/colabtools/assets/139759288/74e738a6-a5a5-4833-b6e9-9b53d27d9f36">

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by colaboratory-team** [comment]
Hello, there might be some confusion here. The Resources pane on the right says "You are not subscribed", but you have "Available: 67.4 compute units", which implies that you made a "Pay As You Go" purchase, not a "Colab Pro" purchase. Could you please confirm? The high memory runtimes are available only for Pro or Pro+ subscription customers, not for Pay As You Go customers. If you did make a "Colab Pro" purchase, please submit a feedback (through `Help > Send feedback` on the Colab homepage) so that we can investigate further with your account details. Please mention this Github issue in your feedback if you submit one. Thanks for using Colab.
