### ISSUE TITLE
NLTK dispersion plot not displaying the graph

### ISSUE THREAD

**Issue by specbug** [googlecolab/colabtools#397]
NLTK dispersion plot for a text, as displayed [here](https://www.nltk.org/book/ch01.html#fig-inaugural) , only seems to plot the axis and labels and doesn't plot the actual dispersion data points in the graph ,as shown in the figure below.

![image](https://user-images.githubusercontent.com/27699970/51423562-3c53d380-1be8-11e9-94c1-d35d77638c7f.png)

**Comment by alexoru4** [comment]
Same

**Comment by InonS** [comment]
@specbug have you been able to use other NLTK plots, such as `draw()`? I am just getting the `TclError: no display name and no $DISPLAY environment variable` and would be happy to know how to work around it

**Comment by metrizable** [comment]
Working through the NLTK examples from [here](https://www.nltk.org/book/ch01.html#fig-inaugural), I'm able to produce the Lexical Dispersion plot:

![64rcS6guGUkYqhC](https://user-images.githubusercontent.com/65414824/229943243-5ed0768c-180f-423b-9e0b-9f86ff562ea9.png)

Since this issue was filed a while ago, if you are still experiencing the issue, please open a new bug and provide a minimal reproducible notebook there.

**Comment by ranger-13** [comment]
Same problem here... Did you find a solution to your problem? Thanks!

**Comment by ShakaAmilcar876** [comment]
Hi... yes.. I did. I think the target labels are not in the correct order.
The solution is to reverse them.
I'm attaching a Google Colab file that has the correct code.

**Comment by ranger-13** [comment]
Hi, thanks very much for this... Did you attach the file, though? I don't see it in my phone! Best.Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : ShakaAmilcar876 ***@***.***> Date : 24/06/2025  16:41  (GMT+01:00) À : googlecolab/colabtools ***@***.***> Cc : ranger-13 ***@***.***>, Comment ***@***.***> Objet : Re: [googlecolab/colabtools] NLTK dispersion plot not displaying the graph (#397) ShakaAmilcar876 left a comment (googlecolab/colabtools#397)
Hi... yes.. I did. I think the target labels are not in the correct order.

The solution is to reverse them.

I'm attaching a Google Colab file that has the correct code.

**Comment by ShakaAmilcar876** [comment]
Yes..I attached it as an email attachment. I will do that again.
I am attaching it as a jupyter notebook and as a python file.
So, two attachments.

**Comment by ranger-13** [comment]
Hi, oddly, I haven't been able to access an attachment (just can't see it anywhere...).
I resolved my issue, which may have been slightly different from yours, since I was getting no graphic output, by creating a file ~/.config/matplotlib/matplotlibrc with the following lines
`backend: TkAgg`
`interactive: True`
Thanks again for your help.
