### ISSUE TITLE
Google Cloud SDK library not working

### ISSUE THREAD

**Issue by yiga2** [googlecolab/colabtools#4]
To avoid cross-posting, see https://stackoverflow.com/questions/47603155/google-cloud-libs-not-working-on-colaboratory

In a nutshell, I understand there is way to interact with other `GCloud components` (GCS or bq) but I want to experiment with the libraries that I would end up using in production. 
In the spirit of '**same code runs everywhere'** on GCP, am I missing a required package in colab to make `google.cloud` work ?

**Comment by craigcitro** [comment]
Answered on SO, but to also update here: 

The issue here is that the version of `google.cloud` you pick up after `!pip install google-cloud` is newer than the one on the container by default. However, we've already loaded that module at runtime, so when you try to import the new one, we get a conflict.

A workaround is to restart the kernel after install, which works, but is far from satisfying.

I think the right fix on our side is to simply install `google-cloud` as part of Colab, which would remove the need for you to think about this in the first place. 😁

**Comment by yiga2** [comment]
@craigcitro thanks ! Makes perfect sense. Workaround makes me a happy camper so I leave it up to G to close (and add as a feature request to your last point)
