### ISSUE TITLE
TypeError: 'float' object is not callable

### ISSUE THREAD

**Issue by sar23rajh** [googlecolab/colabtools#4017]
**Describe the current behavior**
I am trying to run the code but is always showing the error: TypeError: 'float' object is not callable, however, I tested the code less than 2 hours ago and was working perfectly fine, it is happening with all the code lines, no matter how I edit it, what I delete or include, even being correct and with no float added, is showing the same error

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
Edge

**Additional context**
res = int(abs(53 - 57))
print(res)

this code for example, is showing this error:

TypeError                                 Traceback (most recent call last)
[<ipython-input-61-9a641e0b3c1d>](https://localhost:8080/#) in <cell line: 2>()
      1 res = int(abs(53 - 57))
----> 2 print(res)
      3 

TypeError: 'float' object is not callable

**Comment by EvanWiederspan** [comment]
I suspect that at some point, you set `print` to be a float value. This overrides the built in function so that it can no longer be called. Calling `Runtime -> Restart Runtime` should get you back to a good state, and I'd recommend ensuring that you're not overriding built in functions going forward
