### ISSUE TITLE
Unable to import autokeras after pip install

### ISSUE THREAD

**Issue by KHariHaraChaitanya** [googlecolab/colabtools#4020]
I imported tensorflow and installed autokeras in my notebook. Installation of autokeras is successful. But when I imported autokeras as ak, I see an error as follows: 
AttributeError                            Traceback (most recent call last)
<ipython-input-3-85d187d68977> in <cell line: 1>()
----> 1 import autokeras as ak

4 frames
/usr/local/lib/python3.10/dist-packages/autokeras/engine/tuner.py in <module>
     28 
     29 
---> 30 class AutoTuner(keras_tuner.engine.tuner.Tuner):
     31     """A Tuner class based on KerasTuner for AutoKeras.
     32 

Expected behaviour: Import of Autokeras should be successful 

web browser: Chrome

URL to the notebook : https://colab.research.google.com/drive/1C5UYuFqEiqpOxYDt-1Jp9vhGsUrEcs0o?usp=sharing

**Comment by EvanWiederspan** [comment]
Since the import error mentioned an unknown field in keras-tuner, I tried installing an older version of that and it seems to work:

```py
!pip install autokeras keras-tuner==1.3.0
import autokeras
```

The core issue here is that autokeras needs to either be updated to work with the newest version of keras-tuner, or they need to add a restriction to their setup.py so that pip knows to install the older version when auotkeras is installed. I would file an issue with autokeras to get that resolved

**Comment by KHariHaraChaitanya** [comment]
That worked for me. Thank you!
