### ISSUE TITLE
ImportError: cannot import name 'Buffer' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)

### ISSUE THREAD

**Issue by karlajimenez02** [googlecolab/colabtools#4065]
I'm trying to run a code with Pandas profiling, a code that was already fine, out of nowhere, from one day to the next this error appears: ImportError: cannot import name 'Buffer' from 'typing_extensions' (/usr/local/lib/ python3.10/dist-packages/typing_extensions.py)
 
I already updated the pandas profiling but the error continues

**Comment by GenesisOfTime** [comment]
typing_extensions.Buffer appears to have been added to Python 3.12. Your Python version is 3.10. You'll likely run into another error anyway if you update your Python to 3.12 since pandas-profiling is deprecated. Use ydata-profiling instead. It's the same package but it now goes by a different name. You should install the package using its new name. For example, type !pip install ydata-profiling

and then you could do 
from ydata_profiling import ProfileReport

For more info:
https://github.com/python/typing_extensions/blob/main/CHANGELOG.md
https://pypi.org/project/pandas-profiling/
https://github.com/ydataai/ydata-profiling

**Comment by liuzhengx** [comment]
I'm having the same error when import NNI.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-20-552f1bc60374>](https://localhost:8080/#) in <cell line: 5>()
      3 import torch.nn.functional as F
      4 
----> 5 import nni
      6 # if module 'snappy' has no attribute 'compress', !pip install python-snappy
      7 from nni.nas.nn.pytorch import LayerChoice, ModelSpace, MutableDropout, MutableLinear

9 frames
[/usr/local/lib/python3.10/dist-packages/typeguard/_importhook.py](https://localhost:8080/#) in <module>
     20     from collections.abc import Buffer
     21 else:
---> 22     from typing_extensions import Buffer
     23 
     24 if sys.version_info >= (3, 11):

ImportError: cannot import name 'Buffer' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)

---------------------------------------------------------------------------

Any help?

**Comment by HostFuture** [comment]
+1

**Comment by cperry-goog** [comment]
Thanks @GenesisOfTime appreciate this explanation.

**Comment by soroush-bn** [comment]
I faced the same error on colab, with restarting session and running !pip install -U pandas-profiling I could resolve the error.

**Comment by nikifori** [comment]
> I faced the same error on colab, with restarting session and running !pip install -U pandas-profiling I could resolve the error.

It did not work for me. I still have the issue @karlajimenez02 mentioned.

**Comment by ChaitanyaAwasthi** [comment]
I tried updating **typing_extensions**, then restarted my session, and after that, I ran "**from typing_extensions import Buffer**"directly. It worked.
