### ISSUE TITLE
%%timeit make the cell never ends

### ISSUE THREAD

**Issue by Harvey13** [googlecolab/colabtools#4122]
Hello 
When I add the **%%timeit** magic functions, the for loop never ends : it start again endless

NEVER ENDS:
```
%%timeit
for cpt in range(10):
  for i in range(10):
      print(f"{cpt+1}  {i + 1}:")
```

IS OK:
```
for cpt in range(10):
  for i in range(10):
      print(f"{cpt+1}  {i + 1}:")
```

I'm using Chrome Version 118.0.5993.118

**Comment by EvanWiederspan** [comment]
I ran this a few times and don't see the issue; timeit is definitely slower, since it will run the code many times in order to get timing data, but it completed for me in less than 10 seconds several times

**Comment by Harvey13** [comment]
https://github.com/googlecolab/colabtools/assets/2869765/3a5f8904-2c59-4268-9569-61a7119a6ad6

the loops should have printed 10x10 lines, not more than 5000...

**Comment by EvanWiederspan** [comment]
`%%timeit` will run the whole cell many times in order to get an average of the runtime statistics, so you'll see the print output from each one. You can see this with an even simpler cell:

```py
%%timeit
print(1)
```

If you want it to only run once, you can use `%%timeit -n 1 -r 1`. See https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-timeit

**Comment by Harvey13** [comment]
@EvanWiederspan Thanks, I misunderstood the function.  I should have read the online help.  Sorry
