### ISSUE TITLE
pip install tensorflow<2.15.0 makes GPU inaccessible

### ISSUE THREAD

**Issue by Tetra-quark** [googlecolab/colabtools#4235]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

I am using a library that depends on `tensorflow<=2.10.0`. I've tested both `pip install tensorflow==2.10.0` and `pip install tensorflow==2.11.0` and they result in the GPU becoming invisible to tensorflow. With the preinstalled tensorflow 2.15.0 the GPU has no issues being located. 

I believe issues #4230 and #4233 are most likely referring to this same problem. 

Update: 
It appears lots of the same kinds of problems are being reported and they are also related to CUDA and google-auth-oauthlib... Such as #4224 and #4227

```
!pip install tensorflow=2.10.0

import tensorflow as tf
print(f"TensorFlow Version: {tf.__version__}")
print(f"GPU device: {tf.test.gpu_device_name()}")
print(tf.config.list_physical_devices())
```

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

The GPU should be found by tensorflow regardless of version. The output should look something like this:

```
TensorFlow Version: 2.xx.0
GPU device: /device:GPU:0
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

Firefox

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by loewenm** [comment]
I will also confirm that I am experiencing this issue.

When downgrading to tensorflow to any version <2.15, the GPU become unavailable.

You can see this right away with the following command:

`tf.config.list_physical_devices('GPU')`

If you use tensorflow 2.15 (i.e. 3 patches above the latest stable release which is currently 2.12), then the above command will return an available GPU device.

Importantly, because TF 2.15 is unstable, it is actually not usable. There are issues wrt transfer of shape information between layers in neural network models. Consequently, downgrading to tf 2.12 (the latest stable) or lower is required to actually use tensorflow at present.

I believe much of this might be related to the recent upgrade of CUDA that Colab pushed through. TF 2.12 relies upon 11.8, but Colab upgraded to 12.2 for some reason...

Again, 2.12 is currently the latest stable release as shown in the following image.
![image](https://github.com/googlecolab/colabtools/assets/19495222/c68d8ca0-6c9e-4fdb-a37c-20b82053c581)

I'm hoping the Google Colab team with work diligently to fix this issue.

**Comment by mayankmalik-colab** [comment]
We are aware of the fact that tf < 2.15 would not be able to access GPU as we recently upgraded CUDA to 2.12. I would recommend using tf 2.15. However, if you still want to use tf<2.15, you can use fallback version of Colab for a few more days as mentioned [here](https://github.com/googlecolab/colabtools/issues/4214. )

**Comment by loewenm** [comment]
> We are aware of the fact that tf < 2.15 would not be able to access GPU as we recently upgraded CUDA to 2.12. I would recommend using tf 2.15. However, if you still want to use tf<2.15, you can use fallback version of Colab for a few more days as mentioned [here](https://github.com/googlecolab/colabtools/issues/4214.)

Thank you for the suggestion @mayankmalik-colab . However, TF 2.15.0 is a broken build and unstable. As of the date of this post, v2.15 is not even listed on the official website (https://www.tensorflow.org/versions). The latest stable version is v2.12, while v2.14 is being rapidly adopted.

I am not saying this out of zest. I have tried v2.15.0 and there are runtime issues with the build. It does not pass shape along information between layer appropriately (when using subclassing) and even errors out when trying to read a dataset.shape() function during runtime.

**Comment by Tetra-quark** [comment]
`!apt update && apt install cuda-11-8` before installing the lower version of TensorFlow (in my case 2.10.0) solved the problem for me.

**Comment by loewenm** [comment]
@Tetra-quark are you able to utilize the GPU when downgrading to cuda 11.8? I've tried this, but the GPU become unavailable. Everything just runs on the cpu.

**Comment by mayankmalik-colab** [comment]
Follow updates on #4214.

**Comment by throughheavenandearthimtheonlyone** [comment]
> `!apt update && apt install cuda-11-8` before installing the lower version of TensorFlow (in my case 2.10.0) solved the problem for me.

Thanks ! you saving me
