### ISSUE TITLE
Command print() prints content between triple-quotes

### ISSUE THREAD

**Issue by Pretentiousmage86** [googlecolab/colabtools#4277]
The code is below.

'''005 print 탭과 줄바꿈
다음 코드를 실행해보고 \t와 \n의 역할을 설명해보세요.

print("안녕하세요.\n만나서\t\t반갑습니다.")'''
print("안녕하세요.\n만나서\t\t반갑습니다.")

"""\n : New line (Enter), \t : Tab"""

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

It prints :

안녕하세요.
만나서		반갑습니다.
'\n : New line (Enter), \t : Tab'

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

I expected that :

안녕하세요.
만나서		반갑습니다.

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

![image](https://github.com/googlecolab/colabtools/assets/155705622/db906a14-ed77-4ca6-93b4-6af9993cbc78)

The contents between """ or ''' are printed, but only contents after # is hidden.
ChatGPT 3.5 said that it would be an issue of Google Colab.

**Comment by EvanWiederspan** [comment]
This is expected behavior.  What's happening is that by default, IPython will print out the last value executed in a cell. So since your cell ends with a string value, """\n : New line (Enter), \t : Tab""", IPython prints that automatically

You can see this in a simple example, just run a cell like the following that has nothing but a string or a number:

```
"text"
```

```
3
```

and these values will be printed in the output

If you don't want that last string to be printed, you can either assign it to a variable, move the string higher in the cell so that it's not the last statement, or make it a comment instead

**Comment by Pretentiousmage86** [comment]
Thank you for your kind explanation. It helps a lot.

If it is an intended feature of Colab and would be useful in some circumstances that I don't know yet, couldn't be referred to as a bug.

The given sample "text" prints 'text', 3 prints 3, and """\n : New line (Enter), \t : Tab""" prints '\n : New line (Enter), \t : Tab'. 
So the feature might be modifying quote or triple-quote symbols at the both sides of the last string into single-quotes I guess. 

If it is correct, sorry for opening this for an issue.
