### ISSUE TITLE
Collab AI not loading Civitai links for custom models

### ISSUE THREAD

**Issue by jwabc123** [googlecolab/colabtools#4332]
**Describe the current behavior**
When I attempt to have collab download my list of models, they do not load.  Instead of the names of the models, the number associated with the civitai extension is displayed.  For instance, the page will display "Starting download of '119057'" instead of "starting download of [model name]."  When I open the AI browser window none of the models are available for use.  For some time now, some models would load properly, while others would not load, as in the case described above.  However, as of now no models are loading.  The problem persists when I restart my browser, empty cache and cookies, etc.  

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
The models should download correctly from the civitai links provided.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Firefox
**Additional context**
Gist
https://colab.research.google.com/gist/jwabc123/ed0474db388b7ce8cef89135a7d5ba0f/cagliostro-colab-ui.ipynb

**Comment by Fahadxx** [comment]
Same issue, suddenly happened less than 24 hours ago like suddenly, here is what I understand so far:
- models do "download" yet when using verbos it shows that its weirdly EXTREMELY faster than usual suggesting that it didn't 
- they all are downloaded as login.72 (iterative) 
- they are then listed under Hypernetworks instead of Models, loras, etc.. 
- LoRas made by me and stored in google Drive work perfectly fine still unlike civitai links

I assume the issue is login related from civitai's side like a new requirement or something but if anyone got a solution it'll be highly appreciated

**Comment by EvanWiederspan** [comment]
I would reach out to the original code author instead, it's not clear that this is an issue with Colab itself
