### ISSUE TITLE
Colab Pro->Colab Free

### ISSUE THREAD

**Issue by cevparlak** [googlecolab/colabtools#4369]
**Describe the current behavior**
My Colab Pro account behaves like free account.
It is stopping to run after 3 hours while using Hi-RAM and can only open without GPU

**Describe the expected behavior**
It should run longer than 6 hours upto 12 hours.

**What web browser you are using**
Chrome, Firefox, Edge

Order number
COL.7240-4386-9163-34268
Payments profile ID: 6772-5032-3023

**Comment by colaboratory-team** [comment]
This is actually working as expected, because once a subscriber's purchased compute units are depleted, their ongoing usage will be treated & restricted the same way as free users, which is as stated in the Runtime - View Resources pane ("You currently have zero compute units available. Resources offered free of charge are not guaranteed. Purchase more units [here](https://colab.research.google.com/signup?utm_source=resource_tab&utm_medium=link&utm_campaign=payg_learn_more).").
