### ISSUE TITLE
cannot use gpu

### ISSUE THREAD

**Issue by prabal-1221** [googlecolab/colabtools#4383]
**Describe the current behavior**
i first connected gpu then i disconnected it. then i immediately tried to reconnect, it says "You cannot currently connect to a GPU due to usage limits in Colab".

**Describe the expected behavior**
it should simply reconnect, as today i didn't use it.

**What web browser you are using**
chrome

**Comment by EvanWiederspan** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
