### ISSUE TITLE
Questions about google colab pro plus ?

### ISSUE THREAD

**Issue by ghost** [googlecolab/colabtools#4384]
1. If I'm running my program using Google Colab Pro Plus and my computer crashes and have to force a restart, will my program continue running, or will it stop (assume that I have sufficient compute units) ?

2. In what scenarios does Google Colab Pro Plus disconnect and not use background execution ?

Thanks

**Comment by cperry-goog** [comment]
Background execution continues as long as:
1) Your runtime is actively executing (if it errors out and idles then the runtime will be recycled)
2) You had paid compute units
3) No more than 24 hours have elapsed since initiating the runtime

It's a good idea to periodically write out your data to a safe storage location as some users can encounter unpredictable errors.

**Comment by cperry-goog** [comment]
runtime is terminated, all data is deleted.

**Comment by cperry-goog** [comment]
It should! If it doesn't it's a bug ;)
