### ISSUE TITLE
Github does not render my commited notebook from Colab

### ISSUE THREAD

**Issue by mirpouya** [googlecolab/colabtools#4405]
I noticed that my files get committed from my Google Colab Pro to my GitHub, but GitHub does not render them to visualize. This problem is very new, it happened today in 2024-Feb-27, yesterday it was not the case.
When I want to see the files which I committed from Colab, I face this:

![Capture](https://github.com/googlecolab/colabtools/assets/96938754/bbc2005e-de31-4179-92ce-1991ff00b72b)
![colab](https://github.com/googlecolab/colabtools/assets/96938754/2d1c0d5f-ab1b-4e44-bdde-178168fe4931)

I tried different browsers including Chrome and Firefox, I also tried incognito windows as well. GitHub doesn't render my file in either of them.

**Comment by katlyn-edwards** [comment]
Failing notebook example: https://github.com/mirpouya/Human-Emotion-Detection-with-various-CNN-models/blob/main/tt100k_data_preparation.ipynb

Github says "Failed to render code block"

The request that never completes loads when I open it in a new tab: 
https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&bypass_fastly=true&color_mode=auto&commit=012dee6a0547163450261a13f0640079607db733&device=unknown_device&docs_host=https%3A%2F%2Fdocs.github.com&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d6972706f7579612f48756d616e2d456d6f74696f6e2d446574656374696f6e2d776974682d766172696f75732d434e4e2d6d6f64656c732f303132646565366130353437313633343530323631613133663036343030373936303764623733332f74743130306b5f646174615f7072657061726174696f6e2e6970796e62&logged_in=true&nwo=mirpouya%2FHuman-Emotion-Detection-with-various-CNN-models&path=tt100k_data_preparation.ipynb&platform=mac&repository_id=758730707&repository_type=Repository&version=122

This issue seems like something to report to GitHub and is unrelated to Colab.
