### ISSUE TITLE
Checkpoints are not being saved in google drive while training a model on google colab

### ISSUE THREAD

**Issue by Hemanth-Boyapati** [googlecolab/colabtools#4426]
I am training a model on google colab and saving checkpoints in my google drive for every epoch. While training I could see the checkpoints being saved in the colab files section, but when I check my drive, I couldn't see any saved checkpoints.

**Comment by deanp70** [comment]
Posting with permission from @cperry-goog - we're collaborating with the Colab team to provide DagsHub Storage as an alternative to GDrive that is more scalable and built for use with large datasets. It's an S3-compatible bucket that has much simpler access controls, and can be mounted easily.

It might help avoid the issues above - [here's a link to an example notebook to try it out](https://colab.research.google.com/#fileId=https%3a%2f%2fdagshub.com%2fDagsHub%2fDagsHubxColab%2fraw%2f7a674bc098ac6a25e78ac89adb3527aee45fe278%2fDagsHub_x_Colab-DagsHub_Storage.ipynb)

We're looking for community feedback, so I'd love to get your input if it helps with the issue at hand.

(If you're curious, [DagsHub](https://dagshub.com/) is a platform for ML teams which is why we think Colab should have a storage solution suitable for ML workloads)
