### ISSUE TITLE
torch is missing dependencies 

### ISSUE THREAD

**Issue by arenasys** [googlecolab/colabtools#4491]
The python torch package is missing all of its nvidia dependencies: `nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvtx-cu12`. 
So installing any package that depends on torch will result in all of these getting downloaded (unnecessarily?), which takes a while.

**Comment by mayankmalik-colab** [comment]
We removal of these cuda deps was intentional. From 2.2.x, torch started installing CUDA dependencies that conflict with JAX's CUDA dependencies. Because of that, we install torch 2.2.x without those CUDA dependencies (and instead rely on system CUDA). Installing any package that requires torch will attempt to install those CUDA dependencies. The installation can be slow. To avoid the delay, we have started caching the CUDA wheels in our image. You can already see the changes and it is a lot faster now.

**Comment by Azharhn** [comment]
The python torch package is missing all of its nvidia dependencies: nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvtx-cu12.
So installing any package that depends on torch will result in all of these getting downloaded (unnecessarily?), which takes a while.
