### ISSUE TITLE
Google Collab shows incorrect credits (units left)

### ISSUE THREAD

**Issue by harish-bn** [googlecolab/colabtools#4509]
**Describe the current behavior**
My collab subscription is showing zero units left inspite of purchasing pay-as-you-go for 100 units as well as monthly Pro subscription should add 100 more units. Totally 200 units should be displayed but showing zero units left. Kindly fix this bug and allow me to spin GPU for my academic project completion (ASAP)

**Describe the expected behavior**
I should be able to spin A100 GPU since I should be having 200 units in my credit. But that is not happening

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Tried on all browers Chrome, Edge

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
Just check and fix my credits balance (should have 200 units in my subscription)

**Comment by colaboratory-team** [comment]
We can't diagnose a credit-related issue on Github, so please submit an in-product submit (`Help > Send feedback` from https://colab.research.google.com/). Also please note that A100 is not guaranteed because of the capacity issue, as mentioned [here](https://github.com/googlecolab/colabtools/issues/4445#issuecomment-2012925057).
