### ISSUE TITLE
importing featuretools gives error

### ISSUE THREAD

**Issue by AtharKharal** [googlecolab/colabtools#452]
Gives import error on this simple code even!
`
!pip install featuretools==0.6.1
!pip install pandas==0.24.1

import numpy as np
import pandas as pd
import featuretools as ft
from featuretools.primitives import make_trans_primitive
import featuretools.variable_types as vt
`

**Comment by colaboratory-team** [comment]
When you install featuretools 0.6.1, pip upgrades tornado to version 6.0, which is incompatible with Colab:
![uzwzskuq3ua](https://user-images.githubusercontent.com/38081706/53654074-ac02a880-3c01-11e9-90b4-2ede5a1414bd.png)
Unfortunately there is no easy way to sidestep this requirement.

**Comment by colaboratory-team** [comment]
If you explicitly pin the version of tornado that colab requires, then the installation and import will work correctly:
```
!pip install tornado==4.5.3 featuretools==0.6.1 pandas==0.24.1
```
Be aware that this may cause some issues with using the featuretools package if it has incompatiblities with tornado 4.5. Also note that you will have to restart your runtime in order to use the updated pandas package within the notebook:

![pocmrdym490](https://user-images.githubusercontent.com/38081706/53658632-276a5700-3c0e-11e9-84f7-9c92732b9754.png)

**Comment by metrizable** [comment]
@AtharKharal Since this issue was filed a while ago, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.
