### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by gdmaru** [googlecolab/colabtools#453]
Dear all,

I was trying to download BERT model from googleapis but now it's not working. Please help. Below is my code in Colab.

!wget https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip;/

**Comment by craigcitro** [comment]
This isn't a Colab issue, but as it happens, I think you've got a spurious `;/` at the end of that URL.

**Comment by gdmaru** [comment]
Hi, even if I tried below, it's still not working. 

!wget https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip

Same error. 

Above worked yesterday......

**Comment by craigcitro** [comment]
The first command there is working fine for me; can you `Runtime` -> `Reset all runtimes` and try again?

**Comment by gdmaru** [comment]
Nope. I reset all runtimes and tried this again. but I got the same error.

BTW, why you're closing this error while there is still error?

**Comment by craigcitro** [comment]
I'd closed because I assumed the stray `;` was the problem; thinking it through, of course, that'll get passed on to the shell (and give you an error about / not being an executable I suspect).

To confirm:
 * are you using a local runtime?
 * If you reset all runtimes and run just that cell, what's the full error you receive? Can you share a notebook showing just that error?

**Comment by gdmaru** [comment]
Hi Craig,

I found the problem. I think the problem is my local setting in colab. Thanks for your help.

**Comment by craigcitro** [comment]
No sweat! Glad you're unblocked.
