### ISSUE TITLE
Runtime error with opencv2 image display

### ISSUE THREAD

**Issue by domarps** [googlecolab/colabtools#458]
Here is a Minimum working example which shows the error.

![image](https://user-images.githubusercontent.com/7057078/53751403-0e0d1900-3e61-11e9-849b-d56c4e5ade03.png)

Runtime Logs

Timestamp | Level | Message
-- | -- | --
Mar 4, 2019, 9:37:31 AM | WARNING | WARNING:root:kernel 4f183b4d-b017-4af2-99c2-f1805a2b7631 restarted
Mar 4, 2019, 9:37:31 AM | WARNING | WARNING:root:kernel 4f183b4d-b017-4af2-99c2-f1805a2b7631 restarted
Mar 4, 2019, 9:37:31 AM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Mar 4, 2019, 9:37:29 AM | WARNING | : cannot connect to X server

**Comment by craigcitro** [comment]
Yes, the problem here is that the Colab runtime doesn't have an X server running.

For now, the workaround I can offer is to avoid calling `cv2.imshow`; https://stackoverflow.com/a/48738145 has a sample of how to sidestep this.

I'm leaving this issue open for tracking (and will dupe others against it).

For our internal tracking: b/127300928

**Comment by metrizable** [comment]
To support `cv2.imshow` functionality in colab, for example use:

```
from google.colab.patches import cv2_imshow

cv2_imshow(img)
```

You can also choose to reassign: `cv2.imshow = cv2_imshow`
