### ISSUE TITLE
i pay for google colab pro but no i dont have code generator

### ISSUE THREAD

**Issue by art-solutions** [googlecolab/colabtools#4633]
i pay for google colab pro but no i dont have code generator, how can activat collab ai??

**Comment by EvanWiederspan** [comment]
We have not rolled out AI features to all countries yet, so you may be in an area where it's not enabled. We're working to expand to more areas.

Otherwise, you may not have consented to our AI features yet. If you are in a region where AI features are allowed, you should see this page in Settings where you can consent and start to use the features

![Screenshot 2024-06-13 9 39 37 AM](https://github.com/googlecolab/colabtools/assets/1982079/0b3df47b-92c4-484e-83fa-a5397cbb05c2)

**Comment by art-solutions** [comment]
thanks evan, plz note that in your subscribe pro plan that the ai assistance not for all country and mention wich country,  i subscribe just that i can use this function : (
