### ISSUE TITLE
files.upload() times out

### ISSUE THREAD

**Issue by eyaler** [googlecolab/colabtools#467]
when issuing files.upload(), if you wait for too long in the gui, the backend will timeout and continue the run, while the frontend stays open. (tested on firefox and chrome). moreover there is no indication for the user anout the timeout

**Comment by metrizable** [comment]
@eyaler Thanks for filing the issue. Unfortunately, I am not able to reproduce it.

Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem since then, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook and a comment on what you mean by "wait too long in the gui" or a screencast reproducing the behavior.
