### ISSUE TITLE
files.download() fails in firefox when run in a new section

### ISSUE THREAD

**Issue by eyaler** [googlecolab/colabtools#468]
files.download() fails in firefox when run in a new code section.
can be fixed by adding e.g. print() before the download in the same code section
in chrome it works ok (although in a private chrome tab this was needed)

**Comment by LanceNorskog** [comment]
Yeah, I'm getting this too. I create a a 50kb file, then download.
I have to add at least 5 seconds of "settle time" between creating the file and downloading. Otherwise I get this stack trace in Firefox:
---------------------------------------------------------------------------

MessageError                              Traceback (most recent call last)

<ipython-input-20-cc44965972f7> in <module>()
----> 1 files.download(filename)
      2 get_ipython().system('pwd')
      3 get_ipython().system('ls -l')
      4 get_ipython().system('sleep 5')
      5 from google.colab import files

2 frames

/usr/local/lib/python3.6/dist-packages/google/colab/_message.py in read_reply_from_input(message_id, timeout_sec)
    104         reply.get('colab_msg_id') == message_id):
    105       if 'error' in reply:
--> 106         raise MessageError(reply['error'])
    107       return reply.get('data', None)
    108 

MessageError: TypeError: NetworkError when attempting to fetch resource.

Looking at _message.py, I find this code:
    if reply == _NOT_READY or not isinstance(reply, dict):
      time.sleep(0.025)
      continue

I assume that this is sleeping for 60 secs * 0.025 or 1.5 seconds. I would suggest using an increasing timeout in this loop.

I then wrote a loop that ignores this exception and re-runs the download immediately. That fails repeatedly.

It really feels like Colab has an instability in the file service handling the Unix directories in your VMs. Like creating a file is not transactionally safe, that you are using optimistic concurrency and we are beating the usual settle time.

Cheers!
