### ISSUE TITLE
Problem PyTorch/XLA TPU Profiling in Google Colab

### ISSUE THREAD

**Issue by alekseybaev** [googlecolab/colabtools#4769]
I am engaged in machine learning in Google Collab. I use the environment with TPU. Previously, I used the following code for configuration: !pip install cloud-tpu-client==0.10 torch==2.0.0 torchvision==0.15.1 https://storage.googleapis.com/tpu-pytorch/wheels/colab/torch_xla-2.0-cp310-cp310-linux_x86_64.whl This code worked fine. But recently it stopped working. When I launch a cell with this code, a 403 error message appears. How can I fix this?

Using Chrome
Internet search did not bring any results

**Comment by sagelywizard** [comment]
Hello! We migrated to a different TPU architecture (see https://github.com/googlecolab/colabtools/issues/4481 for details), so I suspect that's the issue you're encountering.

So, there's two problems:
1. That wheel was specifically for the "TPU Node" architecture, which we no longer support. "TPU Node" architecture meant that your TPU was hosted on a separate machine than your notebook. We migrated to the newer "TPU VM" architecture, where the TPU is attached to the VM hosting your notebook.
2. The wheel you're trying to install an old/deprecated wheel (not owned by our team. That's managed by the PyTorch/XLA folks). It was specifically for the TPU Node architecture, which we no longer support. I believe that they removed it, because we no longer support the old/deprecated architecture.

We preinstall a supported version of PyTorch/XLA. I'd recommend porting your notebook to use the preinstalled version of PyTorch/XLA on TPU.

**Comment by alekseybaev** [comment]
> Здравствуйте! Мы перешли на другую архитектуру TPU (подробности см. в #4481 ), поэтому я подозреваю, что проблема именно в этом.
> 
> Итак, есть две проблемы:
> 
> 1. Это колесо было специально для архитектуры "TPU Node", которую мы больше не поддерживаем. Архитектура "TPU Node" означала, что ваш TPU размещался на отдельной машине, а не на вашем ноутбуке. Мы перешли на более новую архитектуру "TPU VM", где TPU подключается к виртуальной машине, на которой размещен ваш ноутбук.
> 2. Колесо, которое вы пытаетесь установить, старое/устаревшее колесо (не принадлежит нашей команде. Им управляют ребята из PyTorch/XLA). Оно было специально для архитектуры TPU Node, которую мы больше не поддерживаем. Я считаю, что они удалили его, потому что мы больше не поддерживаем старую/устаревшую архитектуру.
> 
> Мы предустанавливаем поддерживаемую версию PyTorch/XLA. Я бы рекомендовал портировать ваш ноутбук, чтобы использовать предустановленную версию PyTorch/XLA на TPU.

Hi! Thanks for the answer and recommendation. I don't understand what your recommendation to port my nootbok?

**Comment by sagelywizard** [comment]
Hi alekseybaev!

I'm suggesting that you remove `!pip install cloud-tpu-client==0.10 torch==2.0.0 torchvision==0.15.1 https://storage.googleapis.com/tpu-pytorch/wheels/colab/torch_xla-2.0-cp310-cp310-linux_x86_64.whl`. Why? That version of PyTorch/XLA has been deprecated and removed. That's why you're seeing an error. If you remove that, your notebook should use the recent version of PyTorch that we preinstall on the system.

You'll need to update your notebook to use a more recent version of PyTorch/XLA. It may require some work to migrate your notebook from PyTorch 2.0.0 to a more recent version of PyTorch.

I can't give generic recommendations on how to do this migration, since it depends on the details of your notebook. If you encounter issues migrating your notebook, I'd recommend asking for help on StackOverflow or with the PyTorch/XLA folks.

Hope that's helpful!

**Comment by alekseybaev** [comment]
Thank you! I will try to implement your recommendations

**Comment by DarseZ** [comment]
have you solved this issue? i am running similar command in google colab, but cannot make it work...
