### ISSUE TITLE
Colab Subscription Issue: Account Shows as Unsubscribed Despite Payment, Frequent Session Crashes

### ISSUE THREAD

**Issue by IT21042324** [googlecolab/colabtools#4771]
I recently purchased a Colab subscription on August 10th. Despite being charged and having the additional units credited to my account, my status still shows as unsubscribed. Additionally, my Colab session continues to crash every 15 minutes, which is highly disruptive. I expected my account status to reflect my subscription, providing uninterrupted session time and other benefits associated with the paid plan. I am using Chrome Browser. 

I kindly request that you either resolve this issue immediately or provide a full refund. As a student with limited financial resources, a prompt resolution is crucial. If a technical solution is not possible, please ensure that a full refund is issued so that I can purchase a new Colab subscription using a different Google account. I have been unable to use the service due to this issue, and despite several emails over the past two days, I have not received any response. This lack of communication is disappointing, and I urge you to address this matter promptly.

**Comment by colaboratory-team** [comment]
Thanks for using Colab. Assuming the similar in-product feedback we found was from you, we see that what you purchased on August 10th is not a Colab subscription (Pro or Pro+, with monthly recurrences), but a one-time pay-as-you-go purchase. This is why your status still shows as unsubscribed, and this is working as intended (pay-as-you-go purchasers are considered unsubscribed). Also for the same reason, we can see that your TPU sessions were disconnected due to lack of recaptcha responses after a certain duration (this policy is applied to all unsubscribed users of TPU or GPU). Hope this helps clarifying your issues. Thanks again.

**Comment by IT21042324** [comment]
Hello,

I paid to use your service, didn’t I? So why am I getting disconnected?
What do you mean by CAPTCHA prompts? There were no CAPTCHA prompts that I
had to answer, and I don’t want any service that requires me to train a
deep learning model by answering CAPTCHAs every 10-15 minutes. To be
honest, there were no CAPTCHA messages at all. If I have to use the GPU and
answer CAPTCHAs for 5-10 minutes, please explain why there’s even a payment
option for this service. I could easily use the free version, which might
at least give me 20 minutes of uninterrupted usage.

Also, the resources keep reducing by themselves without me even opening
Google Colab. Yesterday, it was in the 160s, and now it’s in the 150s. I
have no idea how this is even happening.

Please provide a proper, acceptable response. Otherwise, I would like a
refund. I’ll be looking for a better service elsewhere. I hope you at least
have the decency to offer a refund.

Thank you for nothing.
