### ISSUE TITLE
limitations 

### ISSUE THREAD

**Issue by beraer** [googlecolab/colabtools#4805]
i'm a basic cs student and i try to learn basic ml structures. i was uploading file for horse-or-human dataset, and colab limited my GPU usage. i thought it's temporary but after 4 days still same issue. so they kinda banned me to use again. bro what kinda policy is this? really I'm just a student, and I'm okay to use max 12 hours, but even I didn't use for 12 hours. it's nonsense!

**Comment by EvanWiederspan** [comment]
We are not able to address resource assignment issues from GitHub. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. If you encounter problems repeatedly, we'll need your account details in order to address any issues you're observing. Please submit feedback in product within Colab at Help > Send feedback
