### ISSUE TITLE
Upgrade polars to 1.7.x or later

### ISSUE THREAD

**Issue by Zaf4** [googlecolab/colabtools#4843]
Currently, default `polars` version in colab is 0.20.2 which was upgraded last in 2024-01-29.

Upgrading it will be useful to have many features implemented in the meantime.

**Comment by metrizable** [comment]
@Zaf4 Thanks for the request and thanks for using Colab.

Since the `polars` project [yanks packages frequently](https://pypi.org/project/polars/#history), we've chosen to pre-install versions of `polars` that are behind the most recent, and that have shown to be stable for a while.

Just to add note, we've [recently upgraded](https://github.com/googlecolab/backend-info/commit/1ff56e9c489ccad27ff6180a2e6503622ac19ec2#diff-50ad98ca28a70b8ef1f29b98c8f9a8166c902329a68d2abe996105cb0ee911afR320) to `polars==1.6.0`. As the 1.7.x series stabilizes, we'll likely upgrade to it, too.

**Comment by metrizable** [comment]
We've upgraded to `polars` 1.7.1. Resolving.
