### ISSUE TITLE
Upgrade Pandas to 2.2.2

### ISSUE THREAD

**Issue by metrizable** [googlecolab/colabtools#4870]
### Upgrade to Pandas 2.2.2

The Pandas version pre-installed in the Colab runtime has been upgraded to 2.2.2. The 2.2.x series was released in [Jan 2024](https://pypi.org/project/pandas/#history) and version 2.2.2 brings in several features, bug fixes, optimizations, and deprecations ([docs](https://pandas.pydata.org/docs/whatsnew/index.html#version-2-2)).

Of note, Pandas 2.2.2 is [compatible with](https://pandas.pydata.org/docs/whatsnew/v2.2.2.html#pandas-2-2-2-is-now-compatible-with-numpy-2-0) a forthcoming upgrade to `numpy` 2.0. We're also now pre-installing the optional `bottleneck` package, a collection of fast `numpy` array functions, which Pandas can use, if present, to [support accelerating](https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#accelerated-operations) certain types of operations.

The upgrade to Pandas 2.2.2 keeps the version pre-installed in Colab up-to-date with the current scientific computing ecosystem with plans for future upgrades.

**Comment by jlchang** [comment]
Pandas 2.2.2 seems to have a plotting bug. For [this tutorial](https://broadinstitute.github.io/2024-09-27-python-intro-lesson/data-visualisation.html#plotting-with-pandas), running `albany['circulation'].plot()` renders:
<img width="585" alt="Screenshot 2024-10-04 at 5 12 09 AM" src="https://github.com/user-attachments/assets/0ed0f0b1-c6ef-4cfb-aabe-d1b683ff1320">
instead of:
<img width="597" alt="Screenshot 2024-10-04 at 5 14 11 AM" src="https://github.com/user-attachments/assets/aa28c8ab-47bb-4499-850a-c789064f3dc1">
Both `2.0.3` and `2.2.3` versions of Pandas behave correctly. Can we upgrade Pandas to 2.2.3 for Colab?

**Comment by tueda** [comment]
The current runtime pre-installs seaborn 0.13.1, which has compatibility issues with pandas 2.2. See the [seaborn 0.13.2 release notes](https://github.com/mwaskom/seaborn/releases/tag/v0.13.2).

**Comment by jlchang** [comment]
According to the pandas team, the [new behavior is a feature and not a bug](https://github.com/pandas-dev/pandas/issues/59960#issuecomment-2395060458). The logic behind the change is reasonable, the change in plotting behavior was just unexpected and not well documented. Going forward, one should .sort_index().plot() to get the same plot as .plot() used to generate.
