### ISSUE TITLE
Unable to Run Notebooks Offline Despite Subscription

### ISSUE THREAD

**Issue by Adithya098** [googlecolab/colabtools#4896]
Describe the current behavior
I am subscribed to Colab Pro+, and I expected to run notebooks offline without an internet connection. However, when I disconnect from the internet, the runtime also disconnects, and I can no longer run my Colab notebooks.

Describe the expected behavior
I should be able to run my Colab notebooks offline, without requiring an internet connection, as per the advertised functionality of Colab Pro+.

What web browser you are using
Chrome

Additional context
I observed this today after I bought the collab pro+ 2 days ago.

**Comment by katlyn-edwards** [comment]
Hmm, are you referencing "Background Execution"?

https://colab.research.google.com/signup doesn't mention "offline" anywhere. 

Background execution is different -- specifically it's saying that it will continue (on our servers) to execute the code and will update the notebook with the output, so that when you re-open the tab, the data / output is not lost. 

If you want to work offline, you might want to look into using your local machine - https://research.google.com/colaboratory/local-runtimes.html

**Comment by Adithya098** [comment]
Hi Katlyn,

Thank you for your quick response and for explaining the difference between offline functionality and background execution in Colab Pro+. I now understand that Colab does not support offline execution but rather background execution, where the code continues running on your servers.

Just to confirm, does this mean I can close the browser tab or even shut down my computer/lost connection to internet, and when I reopen the notebook later, I will still find the code execution progress or results updated and preserved? 

Additionally, are there any limitations or time constraints related to background execution, such as how long the notebook will continue running after I close the tab?

Thanks for your help in clarifying this!

Best regards,
Adithya Ragothaman

**Comment by riskiidice** [comment]
Due to the background execution , That mean I can close browser right ?

**Comment by EvanWiederspan** [comment]
Please see our FAQ entry about this: https://research.google.com/colaboratory/faq.html#idle-timeouts

But yes, background execution will keep your notebook executing even after your browser disconnects, for as long as the VM is around
