### ISSUE TITLE
when copying data from Google Drive to Colab OOM happened

### ISSUE THREAD

**Issue by Drfengze** [googlecolab/colabtools#4932]
<img width="137" alt="Screenshot 2024-11-07 at 1 11 52 PM" src="https://github.com/user-attachments/assets/d420afa2-d4a1-4c84-b21d-16c9225732fd">
When I was copying data from Google Drive to Colab OOM happened, which could cause the whole page crash.  A possible solution is to remount Google Drive, but most time I have to reload the whole program. 

```
 for i in range(len(file_ls) - 1):
        # Copy files to temp directory
        temp_files = []
        for file in tf_files[file_ls[i] : file_ls[i + 1]]:
            dest = shutil.copy(file, temp_dir)
            temp_files.append(dest)
```

**Comment by Drfengze** [comment]
It happened for 3 years again and again 
https://github.com/googlecolab/colabtools/issues/3441

**Comment by EvanWiederspan** [comment]
As noted in that other issue, this appears to be separate from the `Transport Endpoint Not Connected` issue, as that one did not involve OOM-ing.

We can't diagnose with just that code snippet. How much data are you trying to copy? Can you copy just a few files at a time and process them instead of trying to copy all of them first?

**Comment by Drfengze** [comment]
I indeed copy just a few files at a time and process them
