### ISSUE TITLE
Crashes after 3 cell executions

### ISSUE THREAD

**Issue by luc-buysse** [googlecolab/colabtools#4936]
After 3 cell executions, my session crashes. The first cell I am executing is always the first one: pip installations, please find below its full content. The second one is imports. The 3rd one is constants definitions, its execution should be instant, but instead it runs forever. There is nothing in this cell that could justify running indefinitely.

I have tried running this notebook on google chrome and microsoft edge, I tried 7-8 times, it did the same thing everytime.

Please find at this address a notebook to reproduce this bug: [colab_crash_bug_3rd_cell.zip](https://github.com/user-attachments/files/17670554/colab_crash_bug_3rd_cell.zip)

**Comment by EvanWiederspan** [comment]
Thanks for the report; for the future, it's easier for us if you just provide a link to a publicly-shared Drive notebook

But it seems that you're running into https://github.com/googlecolab/colabtools/issues/4911 due to your use of the `warnings` package, removing that should fix your issue while we investigate more

**Comment by luc-buysse** [comment]
Thank you for your quick reponse! It seems like it was indeed the problem!

**Comment by luc-buysse** [comment]
Thank you for your quick reponse! It seems like it was indeed the problem!
