### ISSUE TITLE
GPU out of memory issue

### ISSUE THREAD

**Issue by navyatub** [googlecolab/colabtools#524]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
   I am trying to run a NN model for satellite images(taken very less data less than 1GB) on colab GPU
- Describe the expected behavior:
   When the training starts, within a min, it terminates with out of memory issue

- The web browser you are using (Chrome, Firefox, Safari, etc.):
    Chrome
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
     https://colab.research.google.com/drive/1LA8yCDPZgCT_szdGEpnbSDBZHEFYMPxb#scrollTo=3dCDGacZ0P5I

**Comment by colaboratory-team** [comment]
The notebook isn't shared, so we aren't able to see its contents.

In general, I'd recommend asking library specific questions like this on Stack Overflow where domain experts are more likely to see the question and be able to offer help. This seems like an issue with the code being executed rather than Colab itself.
