### ISSUE TITLE
%tensorflow_version doesn't update after !pip install 2.0 beta

### ISSUE THREAD

**Issue by korakot** [googlecolab/colabtools#590]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I install update tensorflow to 2.0 beta version. 
Then I list all installations and it still shows 1.13.1 and 2.0.0a0.

- Describe the expected behavior:
It should show 2.0.0b0 version as installed.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1_JQHpzhMy770qySyKkeT4UbVUGRZRgtH

**Comment by rpep** [comment]
If you run only the cell which imports tensorflow after restarting the runtime, you get that version:
```
>>> import tensorflow as tf
>>> tf.__version__
'2.0.0-beta0'
```

**Comment by sjamesr** [comment]
The purpose of `%tensorflow_version` is to remove the need to run `pip install`, and the two are not compatible. You should choose one or the other.

It's hard to add checks for this situation to `%tensorflow_version`, because it does not actually import tensorflow itself, which would be needed to check that the appropriate version of TF is installed.

**Comment by metrizable** [comment]
@korakot Colab no longer supports TensorFlow version 1.x and pre-installs version 2.11.0.
