### ISSUE TITLE
Rendering of LaTeX output from cells is not working

### ISSUE THREAD

**Issue by rpep** [googlecolab/colabtools#594]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
In Google Collab, when an object which has a \_repr\_latex\_ function defined is viewed, it takes precedence over the \_\_repr\_\_ function, but no LaTeX is rendered and the text is returned.

- Describe the expected behavior:
In an ordinary Jupyter Notebook environment, the function \_repr\_latex\_ is called, and the returned LaTeX is rendered.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Tested in Chrome, Safari

- Link to self-contained notebook that reproduces this issue:
https://colab.research.google.com/drive/16AXej2oJrvWrI_S5IpNidMvSw95ZLjAY

**Comment by blois** [comment]
See the workarounds in https://github.com/googlecolab/colabtools/issues/142

Here's an example of your notebook with that applied:
https://colab.research.google.com/gist/blois/2e6a1299b8fd5704974dc67f47323deb/copy-of-latex-render-fail.ipynb

Arguably Colab should probably not be rendering the LaTeX mime-type as text since it's not typesetting it, but doing so does allow manual loading of MathJax.

**Comment by blois** [comment]
MathJax is loaded in the main frame, but Colab isolates all outputs into separate iframes- primarily because MathJax is quite large and this would add significant overhead to the output rendering time. We could (and possibly should) load it on-demand when rendering `text/latex` outputs.

The next issue is around fidelity of the rendering- 'text/latex' is loosely defined and MathJax is one implementation of it. We have this issue in text cells as well- the math rendering in markdown is essentially spec'd as 'whatever MathJax does', where upgrades or switching engines to something like KaTeX will break rendering of content. This is essentially covered in https://github.com/jupyter/nbformat/issues/80 which mostly discusses Markdown- but the issue is much more difficult for the math within the markdown.

So we already have this problem in markdown cells, why not apply it to outputs as well? Primary answer is that there is much more demand for canonical support of math in markdown text cells and we'd like to limit exposure to this problem where possible.

Your feedback about compatibility is appreciated and this may be something that we should reconsider.

**Comment by rpep** [comment]
Thanks for the detailed explanation; I think I understand better now. This definitely is more complicated than I had realised!

**Comment by blois** [comment]
This should now be working.

**Comment by rpep** [comment]
Great, thanks @blois!

**Comment by quattro** [comment]
latex in docstrings now raises a bunch of warnings.

```python
  def log_partition(eta: ArrayLike) -> Array:
    """
    Computes the log partition function (i.e. $A(\eta)$) for an implementation
    of ExpFam with natural parameters $\eta$.

    eta: ArrayLike, the natural parameters to evaluate under the log partition.

    Returns:
      The value of the log partition function for each observation under an
      implementation of ExpFam.
    """
    ...
```

will output `<>:46: SyntaxWarning: invalid escape sequence '\e'`
