### ISSUE TITLE
Wrong GPU device reference in an example

### ISSUE THREAD

**Issue by soswow** [googlecolab/colabtools#610]
Open https://colab.research.google.com/notebooks/gpu.ipynb#scrollTo=3IEVK-KFxi5Z example.

Running current version doesn't yield any improvement between GPU and CPU.
I believe line 
```python
with tf.device('/gpu:0'):
```
Should be 
```python
with tf.device('/device:GPU:0'):
```

**Comment by craigcitro** [comment]
Thanks for the report!

It turns out that both `/gpu:0` and `/device:GPU:0` are valid, though I agree that the latter seems to be preferred (as it's the value returned by `tf.test.gpu_device_name()`).

However, the slowdown you're seeing is something different: it turns out that the GPU needs a single run to warm up cuDNN: https://stackoverflow.com/a/45067900; if you do that first, you see the speedup.

I'm updating the notebooks, and will close this once that lands.

**Comment by craigcitro** [comment]
OK, updates should be live.

Thanks again!
