### ISSUE TITLE
regarding c files

### ISSUE THREAD

**Issue by vainaixr** [googlecolab/colabtools#702]
how to look for bytecode instructions?

!find -iname '*.c' -print0 | xargs -0 grep BINARY_MULTIPLY

returns nothing.

**Comment by metrizable** [comment]
@vainaixr Thanks for filing the issue. Since Colab has not set [`PYTHONDONTWRITEBYTECODE`](https://docs.python.org/3.10/using/cmdline.html#envvar-PYTHONDONTWRITEBYTECODE) (nor started the Python process specifying `-B`),f Python's bytecode caching is stored in the standard `__pycache__` directories resident with their associated modules on the `sys.path` (for example, within `/usr/local/lib/python3.10/dist-packages/`).
