### ISSUE TITLE
Colab not working

### ISSUE THREAD

**Issue by chidibede** [googlecolab/colabtools#745]
1.
**
Error
Could not load the JavaScript files needed to display output.
This is probably because your Google account login access has expired or because third-party cookies are not allowed by your browser.

Please reload this page.
**

I have allowed third party access, still nothing. I used it without problems yesterday but I cannot use it today. 
I have also tried running codes and they do not work, after some minutes, the error above will show. 
https://colab.research.google.com/drive/1Xk0A8UR94EssVuqvRDPswLuztBhqFSoT

2. In addition, I used another google account and it works perfectly well. What is happening? Why can't I use my main account?

3. And now, it has stopped working
4. Apparently when the runtime is restarted, it starts working sometimes, please how can I permanently solve this issue

**Comment by chidibede** [comment]
In addition, I used another google account and it works perfectly well. What is happening? Why can't I use my main account?

**Comment by chidibede** [comment]
And now, it has stopped working

**Comment by blois** [comment]
One common cause of this is blocking Javascript executing in a cell's output- you can see this in Chrome's task manager where there will be a process taking up 100% of the CPU. When that happens you can either kill the task in task manager or restart chrome with chrome://restart.

Otherwise it could be caused by a browser extension. In this case incognito mode is usually the best approach to try without extensions.

**Comment by chidibede** [comment]
Ok Thanks. It's been solved.
