### ISSUE TITLE
timeout issue when load 60 thousand images from google drive

### ISSUE THREAD

**Issue by forever208** [googlecolab/colabtools#751]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
time out issue when I tried to load 60 thousand images from google drive. I saved the image in one subfolder and the size of a single image is 10k.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by colaboratory-team** [comment]
This is likely https://research.google.com/colaboratory/faq.html#drive-timeout
Either break up the folder into nested subfolders so that no single folder has too many files, or store the images in Drive inside a zip file and unzip it to the VM as part of your notebook making sure to _avoid_ the Drive-mounted directory as the target of the unzip.
