### ISSUE TITLE
colab automatically restarts in a random time?

### ISSUE THREAD

**Issue by molo32** [googlecolab/colabtools#807]
This week, my colab restarted me every so often and I lost training. Every time it restarts I must reload models and mount google drive etc.

also probe close tab and reopen the notebook and the session is also restarted, I must reload everything, it is supposed to last 90 minutes even if the tab is closed, what happens?
How do I solve this?

**Comment by tnovikoff** [comment]
By "restarted" do you mean disconnected, e.g. due to idle timeout? If so, this is normal. 

See [Colab FAQ](https://research.google.com/colaboratory/faq.html) for more details

**Where is my code executed? What happens to my execution state if I close the browser window?**
Code is executed in a virtual machine dedicated to your account. Virtual machines are recycled when idle for a while, and have a maximum lifetime enforced by the system.
