### ISSUE TITLE
The cartopy version is outdated

### ISSUE THREAD

**Issue by wangjinyu321** [googlecolab/colabtools#833]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
I can only install the default catopy version 0.14.2, which have bugs as described in https://github.com/SciTools/cartopy/issues/1374

- Describe the expected behavior:
Allow the installation of newer version

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):https://colab.research.google.com/drive/1dTQDKdjiU5tdNTmJGGobj9BsDgPi1X_8

**Comment by noritada** [comment]
I also encountered cartopy's issues and found a workaround when I installed cartopy using apt as suggested officially. I'd like to share that workaround to install the latest version as follows:

## Workaround 1: if you are satisfied with Shapely 1.6.3
```
!grep '^deb ' /etc/apt/sources.list | \
  sed 's/^deb /deb-src /g' | \
  tee /etc/apt/sources.list.d/deb-src.list
!apt-get -qq update

!apt-get -qq build-dep python3-cartopy
!pip uninstall -y shapely

!pip install --no-binary cartopy cartopy==0.17.0
```

## Workaround 2: if you want to use the latest version of Shapely
```
!grep '^deb ' /etc/apt/sources.list | \
  sed 's/^deb /deb-src /g' | \
  tee /etc/apt/sources.list.d/deb-src.list
!apt-get update

!apt-get -qq build-dep python3-cartopy
!apt-get -qq remove python-shapely python3-shapely

!pip install --no-binary shapely shapely --force
!pip install --no-binary cartopy cartopy==0.17.0
```

## Resolved issues

Above workarounds can resolve following issues:

- `gridlines()` causes an error (as described in https://github.com/SciTools/cartopy/issues/1374, already fixed in v0.16.0 thanks to https://github.com/SciTools/cartopy/pull/773)
- `coastlines()` triggers a crash (as reported in https://github.com/SciTools/cartopy/issues/871 and https://github.com/SciTools/cartopy/issues/1490)
