### ISSUE TITLE
Text cells only detect LaTex $ delimiters but support \( / \[ delimiters when $ present

### ISSUE THREAD

**Issue by an1lam** [googlecolab/colabtools#839]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
If I have a text cell in which I want to use LaTex and only use "\\(" / "\\[" as delimiters, Colab won't format the enclosed math as LaTex. However, if I add even a single "$" / "$$" delimiter, Colab formats all of the LaTex text in the cell including the text that uses the "\\(" / "\\[" delimiters.

- Describe the expected behavior:
I'd expect Colab to be able to detect the presence of LaTex based on delimiter type 1 *or* delimiter type 2, not only delimiter type 2.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
[Here you go!](https://colab.research.google.com/drive/1AP8n3NH31luVPsjFHBxugTiilnAW8rgv)

**Comment by tnovikoff** [comment]
Tracking internally at b/143779431

In general to use LaTeX only use $ rather than other delimiters. 

What's going on in the second cell looks like a bug, where the presence of $ in the second half of the second cell is affecting what is above it within that cell. 

See 
https://colab.sandbox.google.com/notebooks/basic_features_overview.ipynb 
and 
https://colab.sandbox.google.com/notebooks/markdown_guide.ipynb
for general guidance on using LaTeX in Colab.

I am curious why you tried using other delimiters, as this is something we could consider in the future.

**Comment by an1lam** [comment]
Wait but just to be clear,  the other delimiter options do in fact work (that's what the second cell is showing). It's just conditional on having at least one "$".

My default delimiters are "\(" and, as a pesky engineer, I figured I'd try it and see if it worked. They are also the recommended delimiters for normal LaTex, which is dropping "$" delimiters in the next major version I believe.

Sure, I'm happy to only use "$", but figured I'd give a heads-up that the other alternatives *almost* worked perfectly.

**Comment by tnovikoff** [comment]
Duly noted, thank you for the feedback! :-)
