### ISSUE TITLE
DRIVE MOUNT-MOUNT FAILED

### ISSUE THREAD

**Issue by pamej87** [googlecolab/colabtools#869]
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
When using the code:
from google.colab import drive
drive.mount._DEBUG = True
drive.mount('/content/drive', force_remount=True)

This error happend:

    220             ': timeout during initial read of root folder; for more info: '
    221             'https://research.google.com/colaboratory/faq.html#drive-timeout')
--> 222       raise ValueError('mount failed' + extra_reason)
    223     elif case == 2:
    **224       # Not already authorized, so do the authorization dance.

ValueError: mount failed**

I have already tried print(getpass.getpass()) and it works.

- - The web browser you are using (Chrome, Firefox, Safari, etc.):
CHROME
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

https://colab.research.google.com/drive/16U4hZaLTD7NYG-5aoJxsJchSdtovZj0d

**Comment by colaboratory-team** [comment]
Did you try the directory restructuring suggested at https://research.google.com/colaboratory/faq.html#drive-timeout ?

**Comment by Nabagata** [comment]
I had a dataset of 90k images and I had unzipped it in one of the subdirectories. However, after disconnecting from the notebook, I noticed it was moved to the main drive directory.
I haven't been able to connect to colab ever since and always getting mount failed error as there are too many files in the main directory.

I want to delete all the image files from the main directory but for that I'll need to connect to colab at least once and write a script to delete or reorder all the jpeg/png files from main directory. 
Deleting manually isn't possible and is taking a lot of time and sometimes the drive webpage gets stuck if I try to select more than 500 files for deleting. I want to reorder the directory structure as mentioned in the [instructions](https://research.google.com/colaboratory/faq.html#drive-timeout)

Please suggest some way out of this issue.

**Comment by chenhao1umbc** [comment]
It is not working... I only have 2 files and 3 folders under /content/My Drive/... I tried empty the trash, still not working.
Yesterday, it worked. Now it is Sep 4th, 10pm EST.

**Comment by craigcitro** [comment]
@chenhao1umbc I suspect you're hitting #1540: you need to manually copy the oauth2 code instead of hitting the copy button.

**Comment by chenhao1umbc** [comment]
Yeah, it seems to be so. I manually copy the link, this time it worked...
