### ISSUE TITLE
table does not show properly

### ISSUE THREAD

**Issue by vainaijr** [googlecolab/colabtools#993]
- Describe the current behavior:
all the items get displayed in one row in table

- Describe the expected behavior:
table shows properly

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1pV5x0Oe_XqUNMJt8leBM9kAnDADN3RUD

**Comment by colaboratory-team** [comment]
``prof.key_averages().table(sort_by="self_cpu_time_total")``  returns a string, the ``repr`` of which will be printed on one line. This is a Python behavior not specific to Colab, which you can confirm by running something like the following:
```python
>>> s = "123\n456\n789"
>>> s
'123\n456\n789'
```
In Python, if you want to print a string and have newline characters display as new lines rather than their string representation, you can use the print function:
```python
>>> print(s)
123
456
789
```
In your notebook, you can do the following to print the table:
```python
print(prof.key_averages().table(sort_by="self_cpu_time_total"))
```
